### ISSUE TITLE
Can't pass a boolean capability to the Selendroid WebDriver

### ISSUE THREAD

**Issue by sglebs** [fhoeben/hsac-fitnesse-fixtures#10]
Hi @fhoeben ,

I want to test selendroid http://selendroid.io/setup.html and for that I need to tell it to run things in the emulator, so I am using this:

```
|script              |selenium driver setup   |
|connect to driver at|${url}|with capabilities|!{aut:io.selendroid.testapp, emulator: true}|
```

Unfortunately I get this error in Selendroid:

```
Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean
```

and that happens because of this code in Selendroid:

```
  public Boolean getEmulator() {
    if (getRawCapabilities().get(EMULATOR) == null
        || getRawCapabilities().get(EMULATOR).equals(JSONObject.NULL)) return null;
    return getBooleanCapability(EMULATOR);
  }

  // throws exception if user didn't pass the capability as a boolean
  private Boolean getBooleanCapability(String key) {
    Object o = getRawCapabilities().get(key);
    if (o == null) {
      return null;
    } else if (o instanceof Boolean) {
      return (Boolean) o;
    } else {
      throw new ClassCastException(String.format(
          "DesiredCapability %s's value should be boolean: found value %s of type %s", key, o.toString(), o.getClass()
              .getName()));
    }
  }
```

So, I need to put a * boolean* in that Hashtable, and not a string. But it does not seem to be possible to do this with FitNesse. Maybe this is why Xebium takes a JSON String?

If that is the case, perhaps you should also support a JSON-based API as well? I used to support it in my test fixture, but recently changed it to be like yours. Look at the red code in https://github.com/sglebs/BetDevFitNesse/commit/f46d9ed0db6348059a6395fecff74d4590fd1e54#diff-9990a6b7571fd450ab906375e1f1f9da to see how I was supporting the JSON-based capabilities.

Any other suggestions?

**Comment by fhoeben** [comment]
I think adding an overload that takes a JSON string is possible. You could create a subclass or send me a pull request with a fix.

**Comment by fhoeben** [comment]
But I believe Selendroid really should use `Capabilities.is()` instead of having their own Boolean value retriever...

**Comment by sglebs** [comment]
I agree with you. Let's see what they say.

Your idea of automatically converting is also good.

**Comment by sglebs** [comment]
I created a pull request: https://github.com/fhoeben/hsac-fitnesse-fixtures/pull/12

This allows one to use JSON and therefore control the type of each parameter passed to hsac.

**Comment by fhoeben** [comment]
Fixed by merging pull request, BUT

I did change the name of the method, because it was undetermined which version would be used (hash or json). So usage is:
```
|script          |selenium driver setup   |
|connect to driver at |${GRID_HUB}|with json capabilities|{aut:"io.selendroid.testapp", emulator: true} |
```
