### ISSUE TITLE
Question: How to test false negative that cause failures

### ISSUE THREAD

**Issue by bzon** [fhoeben/hsac-fitnesse-fixtures#100]
Testing for false negatives e.g checking if response status is 400 fails the test.

<img width="250" alt="screen shot 2016-11-16 at 4 56 57 pm" src="https://cloud.githubusercontent.com/assets/19391568/20351913/d18159c4-ac1d-11e6-976c-c899cbeb4222.png">

**Comment by fhoeben** [comment]
Add a 1st cell to the line with the post: `|reject` this is the standard Slim script syntax for testing something which returns falls (without this first cell there actually is an implicit `|ensure` cell)

**Comment by bzon** [comment]
Thanks! I think this should be documented somewhere in the Http test page. :)

Closing this one.

**Comment by fhoeben** [comment]
Pull requests are welcome....
