### ISSUE TITLE
Question: How to rename "|show"

### ISSUE THREAD

**Issue by danielmenezesbr** [fhoeben/hsac-fitnesse-fixtures#101]
Is possible to rename "|show"?
eg.
|show        |take screenshot   |Foto_3_groot                                        |

I wish to type:
|mostrar        |take screenshot   |Foto_3_groot                                        |

How to do it?

**Comment by fhoeben** [comment]
This is more a FitNesse question than for my fixtures. But...

You can create your own plugin with a SlimTable extending ScriptTable (https://github.com/unclebob/fitnesse/blob/master/src/fitnesse/testsystems/slim/tables/ScriptTable.java), where you override the methods that define the keywords used by script tables (i.e. `getShowKeyword()` for show).
