### ISSUE TITLE
Version description - 2.10.1

### ISSUE THREAD

**Issue by danielmenezesbr** [fhoeben/hsac-fitnesse-fixtures#105]
In description [1], instead of "New in 2.10.0", it should be "New in 2.10.1"".
[1] https://github.com/fhoeben/hsac-fitnesse-fixtures/releases/tag/2.10.1

...
New in **2.10.0**:

MockXmlServerSetup allows response headers to be configured, fixing #62.
NgBrowserTest allows subclasses to define method that do not require waiting for Angular using @NoNgWait, #102 .
Workaround for unclebob/fitnesse#989 in sample wiki content
...

**Comment by fhoeben** [comment]
Thanks, fixed
