### ISSUE TITLE
feature request: to check the <a> tag behind a screen link

### ISSUE THREAD

**Issue by keetron** [fhoeben/hsac-fitnesse-fixtures#111]
Feature request: To have a command that will check the <a> tag behind an element.
Right now I click on a link, verify the tab URL, click back and continue whatever it was I wanted done. It would be better to have:
|check|somescreenthing|link value for|http://awesomedomaingoeshere.com|
Which would return true if they match.
Alternatively, a command to read the <a> tag:
|link value for|somescreenthing|

Maybe both?

In a way, this is a to-do list for myself to remind me what I want added.

**Comment by fhoeben** [comment]
Pull request #115 allows you to do this. Is a higher level method still needed/useful, or is the technical approach sufficient?

**Comment by keetron** [comment]
Yeah, I figured as much which is why I think the addition from Tom is very valuable.
Still I stand by my comment about readability. While it can be caught using scenario's, that also lowers transparency (somewhat).
