### ISSUE TITLE
feature request: Count the occurrences of a screen element or text

### ISSUE THREAD

**Issue by keetron** [fhoeben/hsac-fitnesse-fixtures#112]
I would love to have some sort of counter for screen texts

|check count|1|for|HeDoesntLookLikeAToad|
|check count|3|for|ItGotBetter|
both would return true or false.

and alternatively or additional

|count|HeDoesntLookLikeAToad|
would return 1

|check count|3|for|ItGotBetter|
would return 3

Same as my other issues, a small to do list for myself for things to add to HSAC.

**Comment by fhoeben** [comment]
I would suggest a method that returns the number available on the page, so that you can a do a check and see the actual value (e.g. 2) returned and not just a red line that the count was not 1.

e.g.
```
|script|browser test|
|open|http://mypage|
|check|number of times|It got better|is present|3|
```

**Comment by fhoeben** [comment]
What do you think of my attempt at this in https://github.com/fhoeben/hsac-fitnesse-fixtures/tree/countTexts?

It still needs documentation, but I believe the acceptance test wiki page shows what is possible....
