### ISSUE TITLE
tooltip checker

### ISSUE THREAD

**Issue by vincienl** [fhoeben/hsac-fitnesse-fixtures#114]
Hi,

Is there a possibility to check text in multiple tooltips on a page? which look like this one? problem is that classes are the same, only the title is different.

> "img src="/vito-static/images/css/information_small.gif" class="ra_bh_tooltip" alt="info" title="Het adres waarnaar de pas wordt verzonden. Dit kan een adres van de klant zijn, of een adres van de bank. Als klantadres kan gekozen worden voor het rekeningadres of een adres van de organisatie."
<span id="_tooltip" class="infotext">Het adres waarnaar de pas wordt verzonden. Dit kan een adres van de klant zijn, of een adres van de bank. Als klantadres kan gekozen worden voor het rekeningadres of een adres van de organisatie.</span>"

**Comment by keetron** [comment]
That text is very different than the one I got in my mailbox.

Vito, sounds familiar for some reason.

**Comment by fhoeben** [comment]
My mail looks very different too. How did you pull that off?

There are multiple instances I gather, with the same class. Do these tooltips live in some kind of 'context' that you could use? How would you like to define them in end-user terms?
From a purely technical point of view: Would an xpath be acceptable? I'm thinking `xpath=(//img[@class='ra_bh_tooltip'])[1]` for the first and `xpath=(//img[@class='ra_bh_tooltip'])[2]` for the second. Ugly and fragile, but maybe acceptable when hidden in scenario?

**Comment by vincienl** [comment]
the first post was with a stupid copy paste action ;-)

thanks for the tip!!!!!!

**Comment by keetron** [comment]
If you name the scenario's something like: "check first tooltip for text" and "check second tooltip for text" it will be clear later what it does without reading the scenario itself.

**Comment by vincienl** [comment]
yeah that's the plan indeed :-)

**Comment by vincienl** [comment]
but did not work... When I play around with it i get 2 responses (both red)

1 - []
2-[null]

**Comment by keetron** [comment]
Can you post your fitnessr code?
Just the line with the test should be enough.

Op 23 feb. 2017 7:27 p.m. schreef "vincienl" <notifications@github.com>:

**Comment by vincienl** [comment]
1 - check	value of	xpath=(//img[@class='ra_bh_tooltip'])[1]	[] expected [Indien een wettelijk vertegenwoordiger of medewerker niet verschijnt in de lijst, dan is deze (nog) niet bekend bij de Rabobank. Bezit de wettelijk vertegenwoordiger of medewerker 2 (maximum) OnlineKeys, dan is deze niet meer selecteerbaar.]

will give the other ones in a sec

**Comment by vincienl** [comment]
check	value of	xpath=(//img[@class='infotext'])[1]	[null] expected [Indien een wettelijk vertegenwoordiger of medewerker niet verschijnt in de lijst, dan is deze (nog) niet bekend bij de Rabobank. Bezit de wettelijk vertegenwoordiger of medewerker 2 (maximum) OnlineKeys, dan is deze niet meer selecteerbaar.]

**Comment by vincienl** [comment]
I think codewise it would be the same as the old RECO LB

**Comment by keetron** [comment]
Yeah, it is becoming very close to being work now, I will be back in the
office on Monday. ;-)

Op 23 feb. 2017 7:50 p.m. schreef "vincienl" <notifications@github.com>:

**Comment by vincienl** [comment]
haha no problem ;-) i'll give it some tries! have a nice weekend

**Comment by fhoeben** [comment]
(As far as I know) `value of` will not get you the value of a title attribute (as it is not something shown on the screen immediately). So that might explain why it does not work....

The title attribute can be used as a 'place' when clicking, or retrieving the value of an element. So the following should work, for instance:
```
|click|Indien een wettelijk vertegenwoordiger of medewerker niet verschijnt in de lijst, dan is deze (nog) niet bekend bij de Rabobank. Bezit de wettelijk vertegenwoordiger of medewerker 2 (maximum) OnlineKeys, dan is deze niet meer selecteerbaar.|
```
BUT that is not what you want, if I understand your question correctly....

I see a couple of paths going forward:
 
1. You rewrite the application to show elements when the mouse pointer is on the selected image, and then write a test using 'hover over' and 'value of'. An example of what the html and test could look like is provided in the project's acceptance tests  [HsacAcceptanceTests.SlimTests.BrowserTest.HoverOverTest](https://github.com/fhoeben/hsac-fitnesse-fixtures/blob/master/wiki/FitNesseRoot/HsacAcceptanceTests/SlimTests/BrowserTest/HoverOverTest.wiki). The nice thing of this approach is that you get full control over what the tooltip looks like, instead of relying on what the user's browser does for a title.
2. You create your own method in a custom fixture, subclass of BrowserTest, to get the tooltip/title value. Something along the lines of `tooltip of <place>`.
3. You create a pull request adding a `tooltipOf()` method to BrowserTest itself.

I assume option 1 is not going to be realistic, so 2 and/or 3 will be your best bets. Option 2 will get your tests up and running immediately. Option 3 will relieve you of the burden to maintain the code yourself in the longer run (but will require some additional work such as updating the documentation and adding an acceptance test)...

**Comment by tcnh** [comment]
I have a method 'valueOfAttributeOn(String attributeName, String location)' that's does what you need. 

You can then use:
| check | value of attribute | title | on | xpath=(//img[@class='ra_bh_tooltip'])[1] | title text.... |

I'll try to share IT in a PR tomorrow morning.

**Comment by keetron** [comment]
Your solution is much of what the plugin needed to be versatile, Tom. With this a lot of details captured in attributes can be added to a regressionset, making it finer grained while staying robust.

There is of course a however in this and I would like to bounce some thoughts around. Looking at HSAC and the philosophy behind it, the plugin aims to achieve the goals of readable tests that are easy to maintain for those new to the testset. To this end, a lot of the methods in the Browser Test class are set up to make sense of what is happening, in wording as well as workings. Sometimes technical things are needed, such as technical selectors to enable higher level test coverage and these are added in Browser Test.

The PR you submitted fits best in the second category, a technical solution to a practical problem. To be able to add this test, one needs to dive into the code and create a true regression test that will take the existing HTML as a base, not the specs.

Specs will say: "There should be a hover tooltip saying FOO when mousing over element BAR."
The tests I expect to write with BrowserTest would look something like this:
`|check tooltip for|BAR|reads|FOO|`
Your solution is very good, it allows me to write some other tests that have been bugging me for a while, but it would be best if it wasn't the end point but rather a starting point.

**Comment by tcnh** [comment]
Hi Koen, I agree on your hesitation on this. That's also the reason that I don't usually submit PR's for this type of additions, but keep them in my project-specific extensions. On the other hand, I've never seen any webapp that was built so consistently that I could do all the UI testing without the need for technical locators or this type of additions at some point, so it would make sense to include them in the base fixtures. (Possessing this 'power' means you need to wield it wisely ;-) )

One doesn't rule out the other by the way. One could add some 'convenience' methods that are more user oriented, such as "tooltipFor(String place)" or (ok, maybe a bit technical, but useful for checking validation messages, etc) cssClassOf(String place). That takes the technical stuff out of the ScenarioLibrary.

**Comment by keetron** [comment]
#111 
"linkFor(StringPlace)"

There is a few typical additions I would like to see in HSAC and just now, returning from my run, I figured out how to do this. Thank you for the inspiration. 👍

**Comment by vincienl** [comment]
And now the noob question... which Hsac value do i need to put in de pom.xml?

**Comment by fhoeben** [comment]
Currently you would need to use the current -SNAPSHOT version as found in the pom.xml in GitHub.

I'll see whether I can make a release this weekend...

**Comment by fhoeben** [comment]
You can use 2.11.2:

`tooltip for <place>`: Retrieves the value of the tooltip that is shown when the mouse is placed on the place (the 'title' attribute)
