### ISSUE TITLE
BrowserTest extension

### ISSUE THREAD

**Issue by violinner** [fhoeben/hsac-fitnesse-fixtures#116]
I would like to extend nl.hsac.fitnesse.fixture.slim.web.BrowserTest to add some lines to the output table when the test table is completely processed.  Is there an available API to get write more rows to the table?

**Comment by fhoeben** [comment]
Not at the fixture level, as far as I know.

What you could look at is make your own SlimTable (like I did with 'storyboard' and 'table template', in https://github.com/fhoeben/hsac-fitnesse-plugin). At that Slim level you have full control over the table.
