### ISSUE TITLE
Question: Http Test to bypass insecure https url

### ISSUE THREAD

**Issue by bzon** [fhoeben/hsac-fitnesse-fixtures#123]
Hi @fhoeben how can we bypass an insecure https website when using http test fixture?

```bash
|script       |json http test|
| get from | https://xyz.com |
```

I'm getting Caused by: javax.net.ssl.SSLPeerUnverifiedException: Host name 'xyz.com' does not match the certificate subject provided by the peer ...

**Comment by fhoeben** [comment]
At the moment there is no support to bypass the verification.
You have to either: test without SSL, or get a certificate which matches the host your testing against.

I see no real value of testing a secure connection which is not actually verified :-)

Technically this could be addressed in Java code, but ...

**Comment by bzon** [comment]
Alright got it. Thanks!

**Comment by boredland** [comment]
I would appreciate if that could be implemented. On testing systems, sometimes getting ssl right is a bigger problem. We could ease that pain. If we'd reopen this issue, one could easily open a bounty on bountysource etcpp.

**Comment by boredland** [comment]
Thanks, added a little bounty.

**Comment by ybermejo** [comment]
Hi @fhoeben , I already have the certificate of the host I'm going to test but I don't how to use/import it to fitnesse. How to use that?

> At the moment there is no support to bypass the verification.
You have to either: test without SSL, or get a certificate which matches the host your testing against.

I see no real value of testing a secure connection which is not actually verified :-)

Technically this could be addressed in Java code, but ...

**Comment by tcnh** [comment]
> I already have the certificate of the host I'm going to test but I don't how to use/import it to fitnesse. How to use that?

Just use the pkcs12 file as a java keystore.

When you run your test from the wiki:
```!define COMMAND_PATTERN {java -Djavax.net.ssl.keyStore=/path/to/keystore.p12 -Djavax.net.ssl.keyStoreType=pkcs12 -Djavax.net.ssl.keyStorePassword=keystorePW -cp %p %m}```

When you run from command line e.g. Jenkins:
```clean test-compile failsafe:integration-test failsafe:verify -DfitnesseSuiteToRun=TestSuite -Djavax.net.ssl.keyStore=/path/to/keystore.p12 -Djavax.net.ssl.keyStoreType=pkcs12 -Djavax.net.ssl.keyStorePassword=keystrePW```

**Comment by ybermejo** [comment]
Hi @tcnh, how to import required certificates in pkcs12 file?

**Comment by tcnh** [comment]
What kind of file doe you have now? pem file?
In that case, something like `openssl pkcs12 -export -in cert.pem -inkey key.pem -out cert.p12`

**Comment by ybermejo** [comment]
i have .jks, .cert and .key files.

**Comment by tcnh** [comment]
try using the jks. keyStoreType becomes JKS too, then

**Comment by ybermejo** [comment]
another question. i have 2 .jks files, for keystore and truststore. am i going to use the keystore alone?

**Comment by tcnh** [comment]
Depends on if the truststore is really needed. You can add it with `-Djavax.net.ssl.truststore=/path/to/truststore.jks -Djavax.net.ssl.truststoretype=JKS`

**Comment by ybermejo** [comment]
can you check my codes below? still having an error.

> !define TEST_SYSTEM {slim}
!define COMMAND_PATTERN {java -Djavax.net.ssl.keyStore=C:\Users\userName\Downloads\Project\certificates\DEV\keyStorename.jks -Djavax.net.ssl.keyStoreType=JKS -Djavax.net.ssl.keyStorePassword=keyStorepass -Djavax.net.ssl.truststore=C:\Users\userName\Downloads\Project\certificates\DEV\truststorename.jks -Djavax.net.ssl.truststoretype=JKS -Djavax.net.ssl.truststorePassword=truststorepass -cp %p %m}

**Comment by tcnh** [comment]
try to use /Users/userName/Downloads/Project/certificates/DEV/keyS as your path. Windows paths are notoriously unreliable.

**Comment by ybermejo** [comment]
Hi @tcnh , it works! :) Just changed the reserved words into camel case format (trustStore) as what Fitnesse accepts. Many thanks man!

> -Djavax.net.ssl.trustStore=C:\Users\userName\Downloads\Project\certificates\DEV\truststorename.jks -Djavax.net.ssl.trustStoreType=JKS -Djavax.net.ssl.trustStorePassword=truststorepass
