### ISSUE TITLE
set value for Fields with period in the name fail

### ISSUE THREAD

**Issue by jasonmcintosh** [fhoeben/hsac-fitnesse-fixtures#127]
The system tries to treat them as a map, so if you have for example:

https://myhost/api?field.key=1234

The http fixture converts that period to become a document instead of a regular field.

**Comment by fhoeben** [comment]
That's no good. I'll try to make a fixed version today.

I assume you can use the workaround to place the value directly in the URL to get?

**Comment by jasonmcintosh** [comment]
I think your fixes are a bit more elegant than the method I was going to do a pull request on - I had a fix that added a new method to MapHelper which allowed you to say "ignoreDots" :)  

|set value|foo|for|bar.field|ignore dots|

but overall think yours works really well!  Thanks!
