### ISSUE TITLE
HTTP test from behind the proxy

### ISSUE THREAD

**Issue by TimoDeriga** [fhoeben/hsac-fitnesse-fixtures#128]
We are trying to use Fitnesse on a VM machine, but can't reach the endpoint because of proxy settings.
Is it possible to use http test from behind the proxy server?

Regards,

Timo Deriga

**Comment by tcnh** [comment]
You'll need to set the proxy server settings in FitNesse's COMMAND_PATTERN special variable.
Default value is: **java -cp %p %m**

To use 127.0.0.1:8888 as proxy, set it using:
**!define COMMAND_PATTERN {java -Dhttp.proxyHost=127.0.0.1 -Dhttp.proxyPort=8888 -cp %p %m}**

This will cause any fixture that makes http connections to run them through your proxy server.
