### ISSUE TITLE
Would like to be able to comment out test cases

### ISSUE THREAD

**Issue by benjammin17** [fhoeben/hsac-fitnesse-fixtures#13]
I have about 70 cases inside |send request|. I would like to be able to comment out a line that I know will fail until the bug is fixed.

**Comment by fhoeben** [comment]
What are you referring to?

FitNesse allows you to comment out script table rows by starting them with `|note|`, or you could use `|reject|` to actually check a method returns `false`

**Comment by benjammin17** [comment]
In your example, you have:
|send request       |
|zip  |City         |
|10007|New York     |
|94102|San Francisco|


What if I had several more, but for the time being, I wanted to not run Dallas
|send request       |
|zip  |City         |
|10007|New York     |
|75201|Dallas|
|30301|Atlanta|
|94102|San Francisco|

**Comment by fhoeben** [comment]
What you are looking for is a way to comment out rows in a decision table. The decision table is a standard FitNesse Slim table. Please file the request there.
