### ISSUE TITLE
How can i check font-size, font-weight, font-color, background color, margin, button size, and position using browser test?

### ISSUE THREAD

**Issue by haroldmalaki** [fhoeben/hsac-fitnesse-fixtures#131]

**Comment by fhoeben** [comment]
At the moment, you can't.

How are these defined? Using CSS file or by style attributes on the elements? In the latter case you can maybe get at them using `value of attribute <attribute> on <place>`.

Are you aware of other testing tools that provide access to this information, using Selenium?

**Comment by haroldmalaki** [comment]
Using CSS file. Thanks fhoeben.
