### ISSUE TITLE
REQ: Disable Webrivers download

### ISSUE THREAD

**Issue by teunisnl** [fhoeben/hsac-fitnesse-fixtures#133]
What:
A way to disable the webdrivers install part.

Why:
Now that the webdrivers are separated I see my CI constantly re-downloading the webdrivers which it does not even use at all, due to the fact that all my test are running on a Selenium-Grid.
So it would make alot of sence to have a way to disable this part.

**Comment by fhoeben** [comment]
Why would CI download web drivers? You don't need to build the project, you can base your tests on the project (see https://github.com/fhoeben/sample-fitnesse-project)?

Then the web drivers are still retrieved before test (you could prevent that by altering the pom to only unpack them from standalone.zip based on a Maven profile which is not active ), but these are retrieved from the standalone.zip, which is cached in the local maven repository (so no network traffic).

If you do want to build the project itself, you could alter the pom.xml to only download based on a Maven profile.

**Comment by teunisnl** [comment]
Started with a clone of this repo and kinda continue forward,
Looked briefly at the archtype version, but kinda missed not having direct access to the source.
Still need to alter scrollTo alot due too issue: #38 (the amount sites that have these are growing)

Option to move install-drivers as a Profile is good option, but option to disable would be better.

**Comment by tcnh** [comment]
When using the archetype, you can still extend browser test if you need to override or extend its methods.. Much easier to upgrade to newer versions too (just update version number in pom)

**Comment by fhoeben** [comment]
Which Java environment do you use (or none)? I use IntelliJ and it has an easy click to 'download source' for a class in a dependency and get to the source that way.
You of course cannot change anything that way, only by having a subclass, but the insight and debugging is there.

I advocate the 'sample project', or starting from archetype: since upgrading is easier (including getting of updated samples) and its more clear (in version control) what is the content of your test suite/project.

**Comment by fhoeben** [comment]
I migrated all my test projects (and those of my customers) in less than half an hour per project. 
(Create a new branch in the test project, delete everything which is copied from this fixture project, so you only have left what is specific for your tests, commit, unzip the contents of the sample project over your test project, review the changes to the pom (revert group/artifact/version changes, add project specific dependencies, review any other changes and commit).

 I believe it is worth it...

**Comment by teunisnl** [comment]
Well guess ill clear some time to have better look into the archtype project.

**Comment by teunisnl** [comment]
Moved the project to an archetype version, extended the BrowserTest to make my own scrollTo
to bad the waitAfterScroll is private; so the only concern i would have remaining is to have good look at private/protected stuff.

But seems to be a better approach so i will be using from now on.

**Comment by fhoeben** [comment]
If you feel a method should be protected instead of private. Just send in a pull request, I don't think I'll object....

**Comment by fhoeben** [comment]
There now is a way to disable the selenium driver download during the build of this project: set maven property 'webdriver.download.skip' to `true`
