### ISSUE TITLE
timeout on XmlHttpTest

### ISSUE THREAD

**Issue by keetron** [fhoeben/hsac-fitnesse-fixtures#134]
I already did my research and found that there is a similar question here: #119 and also found that the timeout in BrowserTest is a Selenium setting so not applicable here.

The difficult part seems to be that we have a series of SOAP calls that we want to execute consecutively and today we are lucky in that the service only gives an OK response after completion of the task but tomorrow I might not have this luxury.

Would it really be that hard to add a timeout to the test execution of HttpTest? Is it handled by the Slim framework and if yes, can we add a virtual runner or something? In a way, I am throwing stuff at the wall now, what sticks?

**Comment by fhoeben** [comment]
I'm not 100% sure what you are asking? Are you looking for a way to abort a test if the server returns no response after x seconds?

Or are you looking for a way to poll for a call to truly be processed if a service replies quickly (but the actual job is not yet done)? That is possible.

You can check the amount of time taken for a response, but that is not what you need, correct?

**Comment by keetron** [comment]
Test is: A SOAP call is made to a service and after some time this service responds with 200 (or 500 or something). The service will not respond if something goes very wrong or if a job that we start by using this service takes hours. I want to limit the time the test waits and if it fails, cut off the test completely.
We have another solution at this time, I was mostly discovering how hard it would be to have a timeout in this location.

**Comment by fhoeben** [comment]
You could look at configuring your own HttpClient to be used in your installation, should not be too hard. Or you could write your own subclass of `XmlHttpTest` and add a method using the project's `TimeoutHelper` to add a method to make a post with a timeout. Something like:
```
    private static final TimeoutHelper TIMEOUT_HELPER = new TimeoutHelper();
    public boolean postToWithTimeout(final String body, final String url, int timeout) {
        return TIMEOUT_HELPER.callWithTimeout("postWithTimeout", timeout, new Callable<Boolean>() {
            @Override
            public Boolean call() throws Exception {
                return postTo(body, url);
            }
        });
    }
```

**Comment by bzon** [comment]
@keetron what is your current workaround/solution for this?

@fhoeben This will be really helpful for testers with no actual java programming background if this can be a feature soon.

**Comment by fhoeben** [comment]
How would you like to configure/call this from the wiki. The more specific you indicate what you want/need the more likely it is to be built....

**Comment by bzon** [comment]
In my current project, a single test page should be completed by x amount of time. If the test is running for more than x time, we just want to fail it automatically.

For example, getting a 5xx response can make the test run for 10 minutes or more, and we just want to end it and make the test fail if it has not completed within 1 minute or less. 

I know that this should be already something that must be fixed on the environment or application side but in our world, teams are working in different timezones and there are separation of concerns where testers can't always communicate with the ops/devs.

What I initially thought of is inside the script table, we should be able to do the following:

```
|script|json http test|
|fail when not completed in|360|seconds|
|get from|http://example.com|
```
or

```
|script|browser test|
|fail when not completed in|360|seconds|
|open|http://www.google.com|
```

Thanks!

**Comment by keetron** [comment]
@bzon Actually it is no real work around, the service we call has two types:
- Call service and respond if understood
- Call service and respond only after task is completed

This call executes a workflow in PowerCenter, so some time might pass and the service is called "WaitForWorkflow". But it got me thinking there must be some timeout in place, right?

However what you day is that you get a 5xx respond but the test continues even though you do not want it to. Would it not be better to have something in place that stops the testpage if a certain code is retrieved or if a response is given that is not a certain code, similar to `wait for visible`?

**Comment by fhoeben** [comment]
Stopping on a certain condition is already possible, see `StopTestFixture` (maybe use it as a library to incorporate its methods in script table using another fixture).

Waiting for the task to be completed seems like something you would be better of to 'poll' for (i.e. check whether it is completed by doing a call (repeatedly)), or by registering a 'callback' that the service called will invoke when the task is completed...

**Comment by fhoeben** [comment]
Release 4.10.0 allows you to configure both a (initial) connect and socket read timeout for HttpTest (and its subclasses, such as XmlHttpTest) via HttpClientSetup fixture.

So I believe the original problem a server that does not respond for hours is addressed.
