### ISSUE TITLE
click by ID is straightforward with the Xebium bridge but complicated with hsac

### ISSUE THREAD

**Issue by sglebs** [fhoeben/hsac-fitnesse-fixtures#14]
Hi @fhoeben 

I ran this:

```
|Import                            |
|nl.hsac.fitnesse.fixture.slim     |
|nl.hsac.fitnesse.fixture.slim.web |

|script              |selenium driver setup   |
|connect to driver at|${url}|with capabilities|{"bundleId":"com.apple.Automator"}|

| script| browser test |
| click | id=_NS:40   |
```
These are the REST requests:
```
127.0.0.1 - - [18/Jun/2015 16:11:14] "POST /wd/hub/session HTTP/1.1" 200 87
127.0.0.1 - - [18/Jun/2015 16:11:14] "POST /wd/hub/session/1434654674693/timeouts HTTP/1.1" 200 57
127.0.0.1 - - [18/Jun/2015 16:11:14] "POST /wd/hub/session/1434654674693/timeouts/async_script HTTP/1.1" 200 57
127.0.0.1 - - [18/Jun/2015 16:11:15] "GET /wd/hub/session/1434654674693/window_handles HTTP/1.1" 200 63
127.0.0.1 - - [18/Jun/2015 16:11:16] "GET /wd/hub/session/1434654674693/window_handle HTTP/1.1" 200 61
127.0.0.1 - - [18/Jun/2015 16:11:16] "POST /wd/hub/session/1434654674693/elements HTTP/1.1" 200 54
127.0.0.1 - - [18/Jun/2015 16:11:16] "GET /wd/hub/session/1434654674693/screenshot HTTP/1.1" 404 798
127.0.0.1 - - [18/Jun/2015 16:11:16] "DELETE /wd/hub/session/1434654674693 HTTP/1.1" 200 53
```

This is the error:

```
Command duration or timeout: 41 milliseconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '2.45.0', revision: '5017cb8e7ca8e37638dc3091b2440b90a1d8686f', time: '2015-02-27 09:10:26'
System info: host: 'Marcio-Marchinis-MacBook-Pro-Silver.local', ip: '192.168.130.30', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.3', java.version: '1.8.0_40'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Capabilities [{bundleId=com.apple.Automator, platform=ANY}]
Session ID: 1434654674693
*** Element info: {Using=xpath, value=(//label/descendant-or-self::text()[normalize-space(.)='id=_NS:40']/ancestor-or-self::label)[1]}
```

Note that despite the fact that I am asking for a click by ID, the request being sent to the web driver is more complex (xpath). Unfortunately this web driver I am using does not support xpath as a locator.

With the Xebium bridge I tried this:

```
|Import                            |
|nl.hsac.fitnesse.fixture.slim     |
|nl.hsac.fitnesse.fixture.slim.web |
|nl.hsac.fitnesse.fixture.slim.web.xebium |

|script              |selenium driver setup   |
|connect to driver at|${url}|with capabilities|{"bundleId":"com.apple.Automator"}|

| script | hsac selenium driver fixture |
| ensure | do | click | on | id=_NS:40 |
| stop browser |
```

The requests received were:

```
127.0.0.1 - - [18/Jun/2015 16:16:08] "POST /wd/hub/session HTTP/1.1" 200 87
127.0.0.1 - - [18/Jun/2015 16:16:08] "POST /wd/hub/session/1434654968777/timeouts HTTP/1.1" 200 57
127.0.0.1 - - [18/Jun/2015 16:16:08] "POST /wd/hub/session/1434654968777/timeouts/async_script HTTP/1.1" 200 57
127.0.0.1 - - [18/Jun/2015 16:16:09] "GET /wd/hub/session/1434654968777/window_handles HTTP/1.1" 200 63
127.0.0.1 - - [18/Jun/2015 16:16:10] "GET /wd/hub/session/1434654968777/window_handle HTTP/1.1" 200 61
127.0.0.1 - - [18/Jun/2015 16:16:10] "POST /wd/hub/session/1434654968777/timeouts HTTP/1.1" 200 57
127.0.0.1 - - [18/Jun/2015 16:16:10] "POST /wd/hub/session/1434654968777/timeouts/async_script HTTP/1.1" 200 57
127.0.0.1 - - [18/Jun/2015 16:16:10] "POST /wd/hub/session/1434654968777/elements HTTP/1.1" 200 75
127.0.0.1 - - [18/Jun/2015 16:16:10] "GET /wd/hub/session/1434654968777/element/_NS%3A40/displayed HTTP/1.1" 200 56
127.0.0.1 - - [18/Jun/2015 16:16:10] "POST /wd/hub/session/1434654968777/execute HTTP/1.1" 200 56
127.0.0.1 - - [18/Jun/2015 16:16:10] "GET /wd/hub/session/1434654968777/element/_NS%3A40/displayed HTTP/1.1" 200 56
127.0.0.1 - - [18/Jun/2015 16:16:10] "GET /wd/hub/session/1434654968777/element/_NS%3A40/enabled HTTP/1.1" 200 56
127.0.0.1 - - [18/Jun/2015 16:16:10] "POST /wd/hub/session/1434654968777/element/_NS%3A40/click HTTP/1.1" 200 56
127.0.0.1 - - [18/Jun/2015 16:16:10] "DELETE /wd/hub/session/1434654968777/cookie HTTP/1.1" 200 53
127.0.0.1 - - [18/Jun/2015 16:16:10] "POST /wd/hub/session/1434654968777/execute HTTP/1.1" 200 56
127.0.0.1 - - [18/Jun/2015 16:16:10] "DELETE /wd/hub/session/1434654968777 HTTP/1.1" 200 53
```

Note that it does perform the lookup based on ID. It never tries to do xpath.

How can I use hsac without the Xebium bridge and have it honor the strategy of an id-based lookup, without requiring xpath support on the remote engine?  Only with a custom BrowserTest subclass?

Thanks!

**Comment by fhoeben** [comment]
BrowserTest's `click` does not support the `id=` prefix for its place. 
The syntax would be (where finding by id is one of the steps tried in the heuristic):
```
| script| browser test |
| click | _NS:40   |
```

What behavior does that give?

**Comment by sglebs** [comment]
I tried  this:

```
| script| browser test |
| click | _NS:40   |
```

It gives this:

```
Command duration or timeout: 42 milliseconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '2.45.0', revision: '5017cb8e7ca8e37638dc3091b2440b90a1d8686f', time: '2015-02-27 09:10:26'
System info: host: 'Marcio-Marchinis-MacBook-Pro-Silver.local', ip: '172.23.70.56', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.3', java.version: '1.8.0_40'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Capabilities [{bundleId=com.apple.Automator, platform=ANY}]
Session ID: 1434711656260
*** Element info: {Using=xpath, value=(//label/descendant-or-self::text()[normalize-space(.)='_NS:40']/ancestor-or-self::label)[1]}
```

It does not look like by id is the first step in the heuristic.

**Comment by fhoeben** [comment]
You are right, I'm sorry.
BrowserTest only supports clicking from the wiki by either heuristic or by xPath. If you need another approach you'll have to write your own subclass.

By the way, the error message does not suggest the driver does not support xPath. To me it states it looked for an element but could not find it. Have you tried?
```
|click by xPath|//*[@id='_NS:40']|
```

**Comment by sglebs** [comment]
The web driver is mine. https://github.com/sglebs/webdriver-python
I will not support path in it. It is aimed at testing native MacOS apps, just like ios-driver and selendroid. I just want by id.

**Comment by sglebs** [comment]
I would suggest that hsac should have a SimpleBrowserTest with no heuristic and BrowserTest should inherit from it and add heuristics. This way you do not limit hsac users so much. Forcing to subclass is a pain, IMHO. Just my 2 cents.

**Comment by fhoeben** [comment]
I thought about having a base class that is more technical before. Biut the whole point starting this was the heuristic: not forcing testers to work with implementation details but with semantics, and end-user terms. Ids have never been a 'good' approach in the tests I did: they are purely technical: if a developer decides to change an id I don't want to be forced to do rework on my regression test set.

For your driver testing native apps: is there nothing more descriptive (more end-user) than an ID to be used in the tests? To me using such terms seems add odds with a tool like FitNesse: if those are the identifiers the whole test might be written in a unit test tool just as well (but maybe scenarios can aid sufficiently).
And for me writing a subclass to add the method is not such a big deal (seems a LOT smaller than your writing your own web driver). If you would really like it one could be added (just like clickByXPath that I also did not have until quite recently, for the same reason).

But I might do the base class, with all the Xeiium-like selector magic in a 2.0 release ;-)

**Comment by sglebs** [comment]
I think you will find that allowing people to bypass the heuristic if they so wish will broaden the hsac acceptance. You will have both ways right out of the box - perfect. I know of another person who turned away from hsac who would definitely reconsider. I am looking forward to it :-)

**Comment by fhoeben** [comment]
How do like the implementation in the 2.0-SNAPSHOT (in master).
You can now use references similar to Xebium's:

```
|script    |browser test                          |
|open      |$url                                  |
|check     |value of|id=a3 |And some more         |
|check     |value of|name=f|Piet                  |
|enter     |Hallo   |as    |css=input[value='Add']|
|note      |Quick check heuristic can also be used|
|check     |value of|Add   |Hallo                 |
|clear     |css=input[value='Add']                |
|click     |link=My link                          |
|is visible|xpath=//div[@aria-labelledby="a3"]    |
```
