### ISSUE TITLE
Bug: suiteFilter + selenium grid

### ISSUE THREAD

**Issue by teunisnl** [fhoeben/hsac-fitnesse-fixtures#141]
If i run a suite test on 'AllTests' with suiteFilter=regression; my selenium grid keeps dying
When i remove the 'regession' tag for 'S1' it runs fine
```
All Tests *
	S 1 * (regression)
		A 1 * (regression)
			Test Case_ 0001 +
			Test Case_ 0002 +
			Test Case_ 0003 +
		Happy Flow + (regression)
		Rainy Flow + (regression)
```

**Comment by fhoeben** [comment]
I use suiteFilters in combination with a selenium grid and it works. 
My guess is that one of that suites/tests you gave the tag causes the grid to die....


Maybe I can help you but I would need some more info: what are tests doing, what happens exactly when the grid "dies" (any messages, what is your grid setup, stuff like that)

**Comment by teunisnl** [comment]
```
Caused by: org.openqa.selenium.remote.UnreachableBrowserException: Error communicating with the remote browser. It may have died.
Build info: version: '2.53.0', revision: '35ae25b', time: '2016-03-15 17:00:58'
System info: host: 'xxxxx', ip: 'x.x.x.x', os.name: 'Windows Server 2012 R2', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_131'
Driver info: driver.version: RemoteWebDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, networkConnectionEnabled=false, chrome={chromedriverVersion=2.29.461591 (), userDataDir=C:\Windows\TEMP\scoped_dir10532_11617}, takesHeapSnapshot=true, pageLoadStrategy=normal, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=58.0.3029.110, platform=WIN8_1, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true, unexpectedAlertBehaviour=}]
```
I look into branch where i can show it, but my guess it has todo with the tag being on parent and child suite

**Comment by tcnh** [comment]
Can you try running the suite with filter through fitnesse's suiteResponder? If this leads tot the same result, my guess would be that something goes wrong in collecting the test pages. Also, could you try running without the regression tag on suite level?

**Comment by teunisnl** [comment]
Well guess i made this issue too fast.
runned same test against a local selenium grid and that works fine.

And seeing removing tags of suite level bypasses the issue.
So i would call it solved for now; tnx for any input.
