### ISSUE TITLE
Dynamic assertion for response body

### ISSUE THREAD

**Issue by kevindgzmn** [fhoeben/hsac-fitnesse-fixtures#142]
Hi @fhoeben ,
Good day to you. Does the hsac plugin have a feature or special type of fixture wherein it could loop through all the arrays in the the response body and after that it will check/assert the values in the response?

 Thank you so much for all the help and best regards.

**Comment by fhoeben** [comment]
No there is no support to loop (or for conditional, like 'if'). The reasoning is that each element in a response would have different expected value anyway, and that you should have repeatable test cases where you know exactly how many elements any sequence/array will have.

You can do some things which arrays/sequences by getting all matches to an xpath or json path, or by counting elements matching certain conditions.
