### ISSUE TITLE
add Authorization header to browser test open command

### ISSUE THREAD

**Issue by francescoforesti** [fhoeben/hsac-fitnesse-fixtures#143]
Hello, 
I am trying to test an application that requires authentication via a json web token,
is it possible to add an `Authorization: Bearer` header to the 
open command in Browser Test?
I've briefly looked through the documentation and some of the project code, but I
didn't find any hint on how to do that. Could You please help me?

Many Thanks!

**Comment by fhoeben** [comment]
BrowserTest does not support adding headers directly. How does an end-user add such an header when opening the application? Isn't there some kind of login page?

If you want to test json services I suggest using JsonHttpTest, which does support adding headers to its requests.

**Comment by francescoforesti** [comment]
Hello, thanks for the answer. Yes I understand, it is indeed really a corner case (I'm trying to test an enterprise/intranet application, where end users will be authenticated by sso, and developers are able to bypass the authentication by providing a JWT). 
Thanks again!

**Comment by fhoeben** [comment]
What I did in the past for SSO (but it worked with a cookie) was that there was a 'stub SSO login' page which my BrowserTest script opened first (it created the cookie) before going to the actual application to be tested.
Maybe something similar exists, or can be created, in your environment?

As far as I'm aware Selenium, which is the library browser test uses to control browsers, has no support for adding custom headers. So I don't believe there is an easy way to add such a header to requests sent by browser test.
