### ISSUE TITLE
Examples should be re-written to use different site

### ISSUE THREAD

**Issue by fhoeben** [fhoeben/hsac-fitnesse-fixtures#146]
Many of the example tests for BrowserTest use funds.nl (below HsacExamples.SlimTests.BrowserTests). Funda.nl introduced 'robot detection' which causes many of the example tests to fail, because the can't complete the captcha. This reduces their sample value.

The examples should just run, and pass. So they should be re-written to use another site (or otherwise ensure they pass).

**Comment by bzon** [comment]
More examples is always nice to have! Can I make a PR to contribute? :)

**Comment by fhoeben** [comment]
I was hoping for someone to offer to make a PR when I created this issue. So: yes, please.

More examples are welcome, but initially my goal was to replace the existing examples that no longer work (without manual completion of the captcha)

**Comment by fhoeben** [comment]
No more tests remain using funda.nl. 
@bzon if you prepared better samples than the ones I came up with a PR is still welcome....
