### ISSUE TITLE
Supporting configurable directories

### ISSUE THREAD

**Issue by paulk-asert** [fhoeben/hsac-fitnesse-fixtures#151]
When using `fitnesse.junit.FitNesseRunner` directly it allows configuration using some supporting annotations, e.g.:
```
@FitNesseRunner.FitnesseDir("fitnesse")
@FitNesseRunner.OutputDir("build/results")
```
It would be good if when using `HsacFitNesseRunner` that these options were still supported. Perhaps by trying to invoke the super methods (for `getOutputDir` and `getFitNesseDir`) and if successful using the returned values but otherwise catching the possible exception and returning the current hard-coded defaults?

**Comment by fhoeben** [comment]
Seems like a good idea to allow the locations to be changeable. Are annotations the most convenient way to achieve that, or should system properties be used (so that the locations can be changed without requiring separate Java classes)? 
Are you in a position to submit a pull request for this?

At the moment you can (of course) create your own subclass of the runner to get the behaviour of `getOutputDir` and `getFitNesseDir` you need.

**Comment by paulk-asert** [comment]
That is what I ended up doing:
https://github.com/paulk-asert/MakeTestingGroovy/blob/master/Slim/src/test/groovy/util/CustomHsacRunner.groovy

I think there is a use case for using system properties (to override whatever the defaults are) but that doesn't remove the need for some way to encode the result within the source code so that anyone in a team can checkout and run from version control without having to set up specific properties. Given that `FitNesseRunner.Suite` is already supported I'd suggest supporting the other FitNesseRunner sublasses so as not to need creating extra classes.

If you don't mind this suggestion I can hopefully create a PR in a couple of weeks time when I return home from conferences.

**Comment by fhoeben** [comment]
Sounds good, look forward to the pull request

**Comment by fhoeben** [comment]
I did some work myself in https://github.com/fhoeben/hsac-fitnesse-fixtures/tree/fix151.
Any thoughts?

**Comment by paulk-asert** [comment]
Sorry, the PR never made it to the top of my todo list. What you did looks good!

**Comment by fhoeben** [comment]
Merged to master
