### ISSUE TITLE
"set browser size to" (setWindowRect()) not functioning with Firefox

### ISSUE THREAD

**Issue by violinner** [fhoeben/hsac-fitnesse-fixtures#152]
Using hsac-fitnesse-fixtures version 3.0.0 and gecko version 0.17.0 and Firefox version 52.2.0 ESR,
changing the driver from "phantomjs" to "firefox", in the test: HsacAcceptanceTests/SlimTests/BrowserTest/CountTextOccurrenceTest, 
the command "|set browser size to|" throws an exception:

org.openqa.selenium.WebDriverException: setWindowRect
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'W7E1399288', ip: '172.24.220.196', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_121'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{moz:profile=C:\Users\f401665\AppData\Local\Temp\rust_mozprofile.MY1vJfqPySis, rotatable=false, timeouts={implicit=0.0, page load=300000.0, script=30000.0}, pageLoadStrategy=normal, platform=ANY, specificationLevel=0.0, moz:accessibilityChecks=false, acceptInsecureCerts=false, browserVersion=52.2.0, platformVersion=6.1, moz:processID=13220.0, browserName=firefox, javascriptEnabled=true, platformName=windows_nt}]

**Comment by fhoeben** [comment]
Seems similar to https://github.com/mozilla/geckodriver/issues/676, which has comments suggesting it is related to https://github.com/mozilla/geckodriver/issues/676 and will be fixed with Selenium 3.4.1

**Comment by violinner** [comment]
Firefox between version 52 ESR has no "setWindowRect()" method in the driver interface.  This is corrected in version 54, but the compatible Selenium 3.4.0 has shut-down problems.  Looking forward to the release of Firefox 54 ESR and Selenium 3.4.1, which should fix both the set-window-size-and-position, and have a clean test shutdown.
