### ISSUE TITLE
The request entity's media type 'application/x-www-form-urlencoded' is not supported for this resource

### ISSUE THREAD

**Issue by preetishah-27** [fhoeben/hsac-fitnesse-fixtures#156]
Hi,

Whenever I try to post to my web service using JSON Post, i always receive the response as:
{"Message": "The request entity's media type 'application/x-www-form-urlencoded' is not supported for this resource."}

But when I try the same through other tools like Postman, I receive the correct response. Can you please help me identify what I am missing.

Below is my request:
!define GOOD_BODY{{{{
json={"binnumber": "5223513312345467"}
}}}}
| script | json http test |
| post | ${GOOD_BODY} | to | http://10.77.32.147/lookupservice/cardproperties/ |
|set value | application/json | for header | Content-Type |
| show | request |
| show | response |
|show | response headers |

**Comment by fhoeben** [comment]
First of all: setting a header after you posted has no effect on the post, so your `set value` should always be above the post if you want it to be used. 

If that does not work as you need, you can also try setting the content type using `set content type` before doing the post:

```
!define GOOD_BODY{{{{
json={"binnumber": "5223513312345467"}
}}}}
| script | json http test |
| set content type | application/json |
| post | ${GOOD_BODY} | to | http://10.77.32.147/lookupservice/cardproperties/ |
| show | request |
| show | response |
| show | response headers |
```

When posting json you can can also you `post values as json`, which will automatically set the content type to 'application/json' with UTF-8:

```
| script | json http test |
| set value | 5223513312345467 | for | binnumber |
| post values as json to | http://10.77.32.147/lookupservice/cardproperties/ |
| show | request  |
| show | response |
| show | response headers |
```

**Comment by preetishah-27** [comment]
Thanks a lot. It worked!!
