### ISSUE TITLE
xpath selector working with browser test and not with ng browser test

### ISSUE THREAD

**Issue by NicolaiRoos** [fhoeben/hsac-fitnesse-fixtures#157]
xpath selector working with browser test and not with ng browser test

When swithing to "ng browser test" the xpath is not locatable anymore since "ng-model =" is added to the xpath. 

_invalid element state: Failed to execute 'querySelectorAll' on 'Document': '[ng-model="xpath=//*[@id="premiumQuestionsLamella-panel"]/div/div/form/div[1]/div/div[1]/rfs-input-date/div/rfs-form-errors/div/ul/li"]' is not a valid selector._ 

Is there a solution to prevent this while using "ng browser test"

**Comment by fhoeben** [comment]
It's a bug and I'll have a look at addressing it, shouldn't be too hard. But I'm afraid I won't have much time to do it next couple of weeks.

May I ask why you are using NgBrowserTest when you select using xpath? I would only use NgBrowserTest when selecting based on binding/model/repeater names. In all other cases BrowerTest will be quicker (and just as good at waiting for Angular, if you use `|set implicit wait for angular to| true|`).

**Comment by NicolaiRoos** [comment]
With the solution given
|set implicit wait for angular to| true| 

The need for ng browser test is gone (at this moment) I was not aware of this feature :)

Thanks!
