### ISSUE TITLE
Select command does not fail when element not present

### ISSUE THREAD

**Issue by lennyg1** [fhoeben/hsac-fitnesse-fixtures#159]
When a click fails, there's a nice error message with a screenshot. It's a timeout, but it's sufficient to immediately understand the issue that occured.

However, when I use Select For the command does not fail. Even if I input a completely random value/xpath/ID/CSS in the target field. Given I put an existing value from anywhere on the page in the value to select.

For example, I have two questions on a page that both have a yes and a no radiobutton. On that page, any select statement that has either a Yes or No as value to select, will always succeed according to the test results in FitNesse. Even if they do absolutely nothing at all and can't even find the element to select on.

Below: these cases all pass/pretend to work, as long as there is a Yes or No anywhere on the page. While I'm pretty sure there's no element on my page that can be found with _kwjdakljjwlkdjalkwjdlkwajkldawd_
```
|script                                                    |
|select|Yes|for|kwjdakljjwlkdjalkwjdlkwajkldawd            |
|select|No |for|aklsjdlkajsdkljalkjaslkjdaklsda            |
|select|No |for|id=thereisnoidlikethisoneanywhereonthispage|
```
The end result is that FitNesse tells me selecting Yes is green/succeeded on an element. While in reality, nothing happened.

 - After further testing. Seems like everything after the For gets ignored and it keeps selecting/clicking the first Yes or No it finds on the page.

**Comment by fhoeben** [comment]
You are right there is a 'bug' (at one time I considered it a feature when working with radiobuttons) that the fact that the 'input' is not found is ignored if the 'value' can be found on the page.
So if 'value' can be found, it is clicked and no error is thrown.

Although it will break backward compatibility I now see this as a bug, and it will be addressed in the near future.
As a workaround you can do an explicit 'wait for visible' on your target/input before selecting a value...

**Comment by fhoeben** [comment]
I fixed this issue in 'master' branch
