### ISSUE TITLE
Using ${PAGE_PATH} in a BrowserTest table

### ISSUE THREAD

**Issue by violinner** [fhoeben/hsac-fitnesse-fixtures#160]
Is there a way to put ${PAGE_PATH} in a BrowserTest table without getting a {?} after saving the page?

I added a "log" command to a subclass of BrowserTest, and would like to log the PAGE_NAME AND PAGE_PATH.  These are not in the Environment symbols, so it looks like the only access is through predefined variables.  Is there any other option to print these to a log through my logger?

**Comment by fhoeben** [comment]
I'm afraid I don't have a good solution for that.
You name you (top-level) suite page a non-wiki word (e.g. Mytests, and not MyTests), I don't think there is a technical necessity (anymore) for pages to be named according to wiki word convention, and that (in my simple test) removes the problem.

But I admit it is a workaround. The slim process (which contains your fixture) has no knowledge of page names. If you were to make your own slim table (like I did for 'storyboard') then in that class you do get access to the current page's variables.

**Comment by tcnh** [comment]
Just read this, but starting the table with
!|script|browser test|

instead of 
|script|browser test|

porevents fitnesse from trying to render any content as wikiwords.

Example:
![image](https://user-images.githubusercontent.com/2232710/29449951-11ba2888-83fd-11e7-870e-16c899a3fc70.png)

**Comment by fhoeben** [comment]
Great tip. I thought that the '!' would also prevent the variable from being expanded.

**Comment by violinner** [comment]
Can a subclass of BrowserTest expand ${PAGE_PATH}, so it can be automatically logged?

**Comment by fhoeben** [comment]
No. Only a slim table would have access to it.
