### ISSUE TITLE
How can we execute tests in parallel ?

### ISSUE THREAD

**Issue by roydekleijn** [fhoeben/hsac-fitnesse-fixtures#163]
Hi,

In order to speed up test execution I like to execute the scripts in parallel. 

How can we do that, without having multiple fitnesse/hsac instances?

Roy

**Comment by fhoeben** [comment]
As far as I know FitNesse itself is not thread safe. Having said that I've had great success running test in parallel by either:
  * Pressing Suite, one for each separate suite to be run in parallel, in multiple tabs open in parallel on a single machine (not my preferred approach)
  * Creating Jenkins builds that start multiple maven processes in parallel each running a separate suite. 

These approaches do give you multiple instances of the Slim processes running the tests, but is that so bad?
The second approach is made quite usable when you use the feature (Jenkins 2 and up I believe) to configure your job using a 'Jenkinsfile' in that file you can have a groovy script which describes what to do. Jenkins provides libraries to start multiple tasks in parallel and I used that to start multiple 'mvn' commands each with a different '-DfitnesseSuiteToRun' value, or include/exclude tags.
I admit it is not optimal division of work over multiple processes, but by running jobs in parallel like this I've been able to reduce mult-hour test sets to run in under half an hour. Which was good enough at that time....
I might have the Jenkinsfile/groovy functions to do this lying around somewhere. I'll have a browse later.

**Comment by roydekleijn** [comment]
But how does that affect the reporting? I do like to end up with a combined reporting.

**Comment by fhoeben** [comment]
Using the Jenkinsfile approach you get a single overview/graph/count in Jenkins of all tests run/passed/failed. The HTML reports are split according to the suites run. 

So if you see a failure you have to look at the test's prefix to see which HTML report will contain full details. But all the HTML reports are linked directly from main build page (you get a link/icon in the left hand view/column per suite)

**Comment by tcnh** [comment]
For onze report over multiple parallel runs, In use the allure listener.
 - mvn clean
 - run parallel test suites in allure profile
 - mvn site in allure profile

Gives a combined HTML dashboard containing all fitnesse result  pages per test case

**Comment by fhoeben** [comment]
@roydekleijn in case you are not aware of the listener: https://github.com/fhoeben/allure-fitnesse-listener

**Comment by roydekleijn** [comment]
ok, currently I use a MultiJob jenkins job, which invokes multiple job (pointing to the same workspace)

@tcnh  How would this mvn command look like? run parallel test suites in allure profile

**Comment by fhoeben** [comment]
What I do when running parallel with allure is (using the [allure profile in the pom.xml from the allure branch in the sample project](https://github.com/fhoeben/sample-fitnesse-project/blob/allure/pom.xml)):
 * `mvn clean test-compile`
 * in parallel for each `<suite>` to be parallized
   * `mvn failsafe:integration-test -P allure -DfitnesseSuiteToRun=<suite> <other options>`
 * Wait for completion of all suites
 * `mvn site -P allure`

After that the report is available in target/allure-report/index.html

**Comment by fhoeben** [comment]
I'm now working on an alternative way to run multiple suites in parallel and get a single overview report (with Allure). The overall outline will be:
 * Create multiple Java jUnit test cases, one per parallel suite, each annotated with `HsacFitNesseRunner`, each specifying a different `OutputDir` (under a single root)
 * Run these tests in parallel, in separate JVMs, using surefire's 'fork' option
 * Combine the generated reports using [`HtmlReportIndexGenerator`](https://github.com/fhoeben/hsac-fitnesse-fixtures/blob/allowHtmlReportMerge/src/main/java/nl/hsac/fitnesse/junit/reportmerge/HtmlReportIndexGenerator.java)

This way all the details of spinning up multiple JVMs, monitoring these, etc can be handled by surefire, and no extra library (like Allure) is needed to provide a single overview
