### ISSUE TITLE
Splitting/refactoring BrowserTest & SeleniumHelper

### ISSUE THREAD

**Issue by roydekleijn** [fhoeben/hsac-fitnesse-fixtures#164]
What is you idea of splitting/refactoring BrowserTest & SeleniumHelper, so it gets more readable and maintainable ?

I like to hear your opinion.

**Comment by fhoeben** [comment]
Making the classes smaller would be much better. BUT I don't think we should end up with many different fixtures to be used in the wiki. So I'm afraid BrowserTest will remain a bit of a beast.

I have been working for the last week or so to move all heuristics from SeleniumHelper to their own classes. Have you seen: https://github.com/fhoeben/hsac-fitnesse-fixtures/tree/heuristicsUsingSuppliers
What do you think of my efforts there?

But any help/suggestions in this area are welcome....

**Comment by roydekleijn** [comment]
One approach would be to have all public methods in BrowserTest (maybe excluding all deprecated stuff) and then having the actual implementation of the public methods and all private methods in separated concise classes.

What is your idea?

**Comment by fhoeben** [comment]
I don't think that split will make it much easier to understand maintain the code. It will just mean more jumping around to find what you are looking for. But maybe I'm wrong. I'm always willing to look at suggestions in a pull request.

I think I'm about done with refactoring the finding of elements to separate classes (the branch I pointed you to). For now I've had my fill of refactoring. So I'll probably merge these changes in this weekend.
I would caution you not to start refactoring on the master branch just now, as this will have quite an impact...

If you have further improvements (or suggestions to change, or do things differently than what I have planned via that branch) let me know.

**Comment by fhoeben** [comment]
I'll close this issue. Send me a pull request with any suggested refactorings
