### ISSUE TITLE
SecretMasker & hiding variables

### ISSUE THREAD

**Issue by tcnh** [fhoeben/hsac-fitnesse-fixtures#172]
Just wondering.. 
I noticed the SecretMasker class in Utils; would it be feasible to leverage this concept to hide variables containing i.e. API keys/passwords/etc. from test reports?

**Comment by fhoeben** [comment]
I use it to hide TestObject API key from the test report. So: yes.

**Comment by tcnh** [comment]
Cool! I'll play around a bit
