### ISSUE TITLE
Handling different application languages

### ISSUE THREAD

**Issue by jtenkate** [fhoeben/hsac-fitnesse-fixtures#173]
At my company Keylane we're building up a regression test for one of our systems, merely based on Browser test. For the UI-tests, we use the screen labels. The language differs between customers. One of the decisions we need to make is how to setup language support, i.e. how to create scripts that can be used with different languages. 

I was trying an approach with combining variables:  set a variable 'lang', combine it with a generic label to get the language specific variable name and use that to define a generic variable. 
For example selecting the gender of a person: in the scripts I want to user ${genderMale} instead of ${nl_genderMale} for lang=nl, or ${en_genderMale} for lang=en. Therefor, genderMale shoud be defined as: !define genderMale [${${lang}_genderMale}]
Unfortunately this doesn't seem to work.

Does anyone have suggestions for a working approach?

**Comment by fhoeben** [comment]
What I've seen done in the past:
- just use a variable ${genderMale} in your tests
- define your tests in a suite that does not define a value for genderMale
- define a suite per locale to be tests (e.g. NlTests), give it a 'symbolic link' to the suite containing all your tests (the one for the previous bullet) and have its root page define all variables in that specific locale

Using this you will have a suite per locale (e.g. NL, EN, FR, etc) but the tests are defined/maintained in a single location/suite. Per locale you only maintain the variables/symbols containing the label values for that locale.

But spreads the maintance  of the label definition across multiple files. You have to remember to add the value for all locales when defining a new label. And there is no nice overview listing all label values per locale.

To overcome this we can use a two step approach in your tests: we add one page that will generate the wiki suite pages per local described above (to be run first).
The single page contains a table describing all labels in all locales. When this page is run it will generate the wiki pages for each locale described above. After which the suites per locale can be run as usual.
Maybe not the nicest of approaches but it does work and gives a decent coverage of two important aspects:
* a single overview of the expected labels per locale
* the test reports contain the labels as experienced by the end-user


**As an alternative**, if your system only has a single codebase and labels per locale, you could also (I have personally done this in the past):
* Run your front-end tests against a system with 'test locale' where the elements on the screen do not have real end-user texts but something neutral (like the keys used internally to look up labels). And code/run your front-end tests using these texts. You are verifying the screen elements get their texts using the correct key.
* Have a back-end (soap, rest or database) test which retrieves all labels for a locale and verifies their values. This test checks that all labels are present for each locale and that the translations loaded match the expected value. This test can (usually also be easily and quickly run against an acceptance or production environment, which is often not the case for front-end tests)

I like the first approach as the tests show the end user texts and make more sense. The alternative gives quicker feedback for many locales without the need to run the full front-end suite for each locale.

**Comment by jtenkate** [comment]
Thanks for the feedback. I will try the first approach. Do you have (a link to) an example of to generate a wiki page by any chance?

**Comment by fhoeben** [comment]
I do not, but @DV3D might have...

The example I know of generates the wiki page using a a http post (via http test) to the wiki. I believe it would be easier to generate the .wiki files directly (using freemarker and file fixtures). I would probably create a (new/custom) fixture to define the table with all keys per locale (the map fixture makes it easy to define multiple maps with the same keys, one per locale, in a row based approach but I believe it would be better to have the locales as columns and the keys as rows). 

Maybe I will have some time to cobble something together later this week. If you get round to defining an approach let me know...

**Comment by jtenkate** [comment]
I'll discuss it with my colleagues who create the fixtures. I have a good idea of where to start now and will keep you posted. Thanks for your help.

**Comment by fhoeben** [comment]
I just merged in some code to facilitate this. Get the latest master and check out [HsacExamples.SlimTests.UtilityFixtures.GeneratedSymbolicLinkSuite](https://raw.githubusercontent.com/fhoeben/hsac-fitnesse-fixtures/master/wiki/FitNesseRoot/HsacExamples/SlimTests/UtilityFixtures/GeneratedSymbolicLinkSuite.wiki)
