### ISSUE TITLE
how to change template location

### ISSUE THREAD

**Issue by keetron** [fhoeben/hsac-fitnesse-fixtures#179]
I keep getting the message template not found. How do I set the template location anyway or find out where I should put a template when using freemarker fixture?

**Comment by fhoeben** [comment]
At runtime the templates must be in `wiki/fixtures/templates`. 

The best way to get them there is:
 * to place them in `src/main/resources/templates` and 
 * have your (IDE (e.g. IntelliJ) build the project, or run `mvn compile` from the command line.

At the moment this location is not configurable. The example page (FreemarkerFixture.wiki) does 'try' to document the runtime location, but reading it now I believe it is wrong (as it mentions a 'template' directory and not 'templates').

> The templates are loaded from the 'template' directory on the class path (e.g. /fixtures/template in a standalone installation).

**Comment by keetron** [comment]
I will figure something out, like putting the template where they are exxpected which is in `basePackagePath: "/templates/` according to Environments.java line 77 ;-)

https://github.com/fhoeben/hsac-fitnesse-fixtures/blob/cb7bceb9820fe187a240009896059318f0ced251/src/main/java/nl/hsac/fitnesse/fixture/Environment.java#L77

But hell, you know your code!

**Comment by fhoeben** [comment]
What do you think of the latest documentation in [FreemarkerFixture.wiki ](https://raw.githubusercontent.com/fhoeben/hsac-fitnesse-fixtures/master/wiki/FitNesseRoot/HsacExamples/SlimTests/UtilityFixtures/FreemarkerFixture.wiki)

**Comment by keetron** [comment]
It helped me find the location that the fixture is actually looking for after building. As you know, I use HSAC outside of FitNesse and putting the ftl in the main/resources/templates folder enables me to run the JUnit based tests because the maven build can find them there and will move them to target/classes/templates.

I will add a comment to the docs, I feel it is a bit verbose.

**Comment by tcnh** [comment]
> I use HSAC outside of FitNesse

Did you find a nice way to avoid having to depend on fitnesse? (i.e. is there some hidden slim-only artifact somewhere?)

**Comment by keetron** [comment]
It depends on what you consider nice. I included fitnesse and hsac as dependencies in the pom.xml and import the XmlHttpTest in my java classes as needed. Right now I use two classes: XmlHttpTest to be able to combine an xpath and an URL to an expected value in very few lines of code and FreeMarkerFixture to combine ftl templates to datamaps for test data setup.

Both of these are typical Rabobank stuff. Funny part is, I see your and Frieds name all over the place in the code I work with. Drop by, we can have lunch :smile:

**Comment by gabe2001** [comment]
hello @fhoeben - thank you for your work!
I do have an issue though: no matter what I do, I cannot "see" my Freemarker template. I'm placing it in ```fixtures/templates``` (pulled in from src/main/resources) and I keep getting the TemplateNotFoundException.
This runs on linux with java 11 - all the samples work fine.
Do you have any suggestions/pointers/ideas?

**Comment by fhoeben** [comment]
@gabe2001 maybe you should create a new issue describing you setup and wiki page exactly because just like this I cannot determine why it would go wrong.
The only thing I can think of just like this is that maybe there is a 'casing problem' in the template name? So for instance you try to load `my_template.ftl` and the template is actually called `My_template.ftl`.

**Comment by gabe2001** [comment]
I'm now thinking that the issue is with the unpacking of the JARs. The part is not working as described in the instructions. I'll try to figure out a solution for that issue first.
