### ISSUE TITLE
Unable to get installed on Centos using the chromedriver

### ISSUE THREAD

**Issue by heart-r** [fhoeben/hsac-fitnesse-fixtures#18]

**Comment by fhoeben** [comment]
No chromedriver executable is bundled for Linux (only for OS-X and Windows), is that the issue? 
If so, try adding a 'linux' directory below the 'webdrivers' directory (next to the osx directory) and placing a chromedriver executable for your platform there. Or use SeleniumDriverSetup's methods to start the browser using the driver class (if not already set, there is also a method to set system properties which will allow you to set the system property to point to the right installation location).
