### ISSUE TITLE
all json path matches

### ISSUE THREAD

**Issue by zgq1987** [fhoeben/hsac-fitnesse-fixtures#180]
why?
all json path matches
"[a-z]{8}"can not matche
{
    "code": "asdasdas",
    "params": []
}
How can I matche?

**Comment by fhoeben** [comment]
What are you trying to achieve, can you (preformat) what you do/use to make it more clear?
It looks like you are trying to apply a regular expression (`[a-z]{8}`) in a json path. That doesn't work.

You CAN however first use json path to get a value from a response, and then have slim check that value against a regular expression:
```
|check|json path|code|=~/[a-z]{8}/|
```
Was that what you are trying to do?

**Comment by zgq1987** [comment]
many Thanks!
others, how can I get the "phoneNo" 

|check|json path|phoneNo|=~/[a-z]{8}/|
this is get null

{
    "phones": [{"phoneNo": "3851467436"}, {"phoneNo": "3851467435"}],
    "age": "111",
    "name": "111",
   
}

**Comment by keetron** [comment]
the regular expression you are using is checking that there is an entry with the content containing of the lowercase letters `a` to `z` with a max number of 8. In this case, change it to `=~/[0-9]{10}/` to check on 10 numbers.
Regex is hard, like, really hard, so I understand your questions. Some basic understanding is super useful so I would suggest reading on this on the internets a lot:
http://www.rexegg.com/regex-quickstart.html
https://www.cheatography.com/davechild/cheat-sheets/regular-expressions/
https://en.wikipedia.org/wiki/Regular_expression

Unfortunately, I cannot find an easy step by step explanation, that is how hard it is. Master it and you are like a god among men.

**Comment by fhoeben** [comment]
@keetron is right that regular expressions are hard, BUT I believe the initial problem here is one of json path: How to get at the phoneNo value.
For that I would recommend reading up on json path, for instance on http://goessner.net/articles/JsonPath/, and then experimenting with an online tool like http://jsonpath.com, where you can supply your json and try different expressions (please note that officially a json path expression must start with `$.` which may be omitted when using my fixtures, but you must use in the online tool).

In your sample I believe you need something like:
```
|check|json path|phones[0].phoneNo|=~/^[0-9]{10}$/|
|check|json path|phones[1].phoneNo|=~/^[0-9]{10}$/|
```
