### ISSUE TITLE
Maps from variables are stored as (html) String instead of Map when nested

### ISSUE THREAD

**Issue by tcnh** [fhoeben/hsac-fitnesse-fixtures#182]
Nesting maps as input for a Freemarker template to generate complex xml requests yields some unsatisfying results.

Example:
[example.txt](https://github.com/fhoeben/hsac-fitnesse-fixtures/files/1548673/example.txt)

Expected: when using $data as an input to an ftl template, address1 and address2 are maps

Actual: address1 and address2 are passed to freemarker as fitnesse's html hash table representation. Causing Freemarker to throw an exception (expected Hash but found String).

Is there an easy workaround? Other than not nesting maps from the wiki?

**Comment by fhoeben** [comment]
I encountered this problem and believed I had addressed this, and even covered it in an acceptance test ([MapOfMapsFixture.wiki](https://fhoeben.github.io/hsac-fitnesse-fixtures-test-results/acceptance-test-results/HsacAcceptanceTests.SlimTests.UtilityFixtures.MapOfMapsFixture.html)). :-(

I'll have to look at it closer. Maybe you can compare what happens in that test to your page's execution to see what is different.

**Comment by fhoeben** [comment]
Sorry, I can't reproduce the problem. Can you show how you use it with a freemarker template? It seems to work for me.

I used template addresses.ftl.xml:
```
<addresses>
	<address1>
		<straat>${a.address1.straat}</straat>
		<huisnummer>${a.address1.huisnummer}</huisnummer>
	</address1>
	<address2>
		<straat>${a.address2.straat}</straat>
		<huisnummer>${a.address2.huisnummer}</huisnummer>
	</address2>
</addresses>
```

And page:
```
!|table: map of maps fixture     |
|          |HOME      |WORK      |
|straat    |testweg   |teststraat|
|huisnummer|1         |2         |
|postcode  |1234AB    |4321BA    |
|telefoon  |1234567890|0987654321|
|          |$homeAddr=|$workAddr=|

!|table: map of maps fixture|
|             |PERSON       |
|Name         |Mop          |
|address1     |$homeAddr    |
|address2     |$workAddr    |
|             |$data=       |

|script|map fixture|$data   |
|show  |value    |address1|

|script|freemarker fixture|
|set value|$data|for|a|
|$xml=|apply template|addresses.ftl.xml|
```

<img width="597" alt="screen shot 2017-12-11 at 21 40 19" src="https://user-images.githubusercontent.com/5467859/33852760-f6935b82-debb-11e7-96df-f05d6d763667.png">

**Comment by tcnh** [comment]
Had to simplify some stuff, the original template is a bit big :)

FTL:
```
<MyOrder>
	<MyContractID>${MyContractID}</MyContractID>
	<MyOrderLine>
		<aParty>
			<Location>
				<Description>${aParty.Location.Description}</Description>
				<Address>
					<DepartmentName>${aParty.Location.Address.DepartmentName}</DepartmentName>
				</Address>
			</Location>
		</aParty>
	</MyOrderLine>
<MyOrder>
```
Wiki page:
```
!|table: map of maps fixture          |
|                      |LOCATION      |
|Description           |Kleurencompany|
|Address.DepartmentName|Geel          |
|                      |$location=    |

!|table: map of maps fixture|
|             |PARTY        |
|Location     |$location    |
|             |$aParty=     |

|script      |mock xml server setup|
|add response|{{{<ok/>}}}          |
|$url=       |get mock server url  |

!|script         |xml http test           |
|template        |test.xml.ftl            |
|set value       |0012   |for|MyContractID|
|set value       |$aParty|for|aParty      |
|post template to|$url                    |
|show            |request                 |

|script|mock xml server setup|
|stop                        |
```

Exception:
```
Caused by: java.lang.RuntimeException: freemarker.core.NonHashException: For "." left-hand operand: Expected a hash, but this has evaluated to a string (wrapper: f.t.SimpleScalar):
==> aParty.Location.Address  [in template "test.xml.ftl" at line 8, column 59]
```
Debugging the test shows me that the value of aParty.Location.Address is:
```
<table class="hash_table">
    <tr class="hash_row">
        <td class="hash_key">DepartmentName</td>
        <td class="hash_value">Geel</td>
    </tr>
</table>
```

So it seems to happen if a nested map from a variable contains a map itself.

**Comment by fhoeben** [comment]
Nested maps inside the map might indeed be something causing issues. I'll see whether I can dive into this a bit further. 

I made a release this morning that changes some map handling, but I don't think it will address this issue. But can you retest, just to be sure?

As a workaround, would it be feasible to use 'map fixture' instead of 'map of maps'? I don't think that it will have problems with nested maps.

**Comment by tcnh** [comment]
I'll try if there's improvement with 3.12.

Using map fixture is also possible, but I like the column layout in map of maps (i.e. I have multiple parties that share the same structure, but are not repeating objects in the xml, so I can't loop through a single map containig them all)

**Comment by fhoeben** [comment]
I understand, the 'translated' view is why I made the maps of maps fixture.

But maybe a table template, or dymanic decision table usage of map fixture, can help you fill the similar structures in a 'nice' way. They will of course have a row instead of a column for each party.

The next fitnesse release (which is already present in Bintray, but unfortunately not yet Maven Central as far as I can tell) will make this an easier problem to tackle. The 'maps of maps' can have direct access to the variable's value instead of only a string (html) representation of it (which is what I believe is causing this issue).

**Comment by tcnh** [comment]
Cool! Your fix makes my life a lot easier today :)

**Comment by fhoeben** [comment]
Good to hear.
I expect I'll upload a release (with latest FitNesse) to Maven Central tonight.
