### ISSUE TITLE
BUG: 2 Browsers in Testcase

### ISSUE THREAD

**Issue by teunisv** [fhoeben/hsac-fitnesse-fixtures#188]
Example
```
|script          |selenium driver setup|
|start driver for|chrome               |
|show            |driver description   |

|script|browser test          |
|open  |https://www.google.com|

|script|selenium driver setup|
|stop driver                 |

|script          |selenium driver setup|
|start driver for|firefox              |
|show            |driver description   |

|script|browser test          |
|open  |https://www.google.com|

|script|selenium driver setup|
|stop driver                 |
```

(did work in 3.0.0)

**Comment by fhoeben** [comment]
What is the bug you are reporting exactly? When I read your test I expect chrome to be stopped and firefox to be started. I don't believe having two separate web drivers has ever worked.
The selenium webdriver is maintained in a singleton, so only one instance can be active in the JVM's process at any point in time. You can get a new one, but the old one (chrome in your example) is stopped when the new one (firefox in your example) is started.
Or are you experiencing that no firefox is opened?

How did you run your test? Via the wiki or via jUnit? If you override the selenium settings for a jUnit run all 'start driver for' rows are ignored and only the override config is used.

I thought about adding support for multiple browser sessions, but never needed it in the end.
Pull request to support this are welcome, but I believe there should we some explicit command to start the second browser and then to switch between which browser to use.

**Comment by teunisv** [comment]
nevermind, we use libaries alot, and forgot that if you use |script|something| it messes with library
