### ISSUE TITLE
Would it make sense to provide support for 'negative'  XmlHttpTest(s)?

### ISSUE THREAD

**Issue by djlestephane** [fhoeben/hsac-fitnesse-fixtures#19]
I just had to create this class because I could not get a green page
when a request caused a SOAP Fault which was in every respect the
response I wanted. Would it be considered if I submitted a pull request
for it with tests? 

        public class NegativeXmlHttpTest extends XmlHttpTest {
            @Override
            public boolean responseIsValid() {
                return ! super.responseIsValid();
            }

            @Override
            public String xPath(String xPathExpr) {
                return super.rawXPath(xPathExpr);
            }
        }

**Comment by fhoeben** [comment]
I have similar tests, and just use `raw xPath` instead of `xPath` in my `check` lines. Would that be an option for you?

Otherwise I would be looking for a way to switch the behavior using a method. Having a subclass for this seems overkill...

**Comment by djlestephane** [comment]
The problem I'm experiencing is right before `raw xpath`, when doing `post | ... | to`.
That line turns red when I execute the test, because the http status code is 500.
I want the http status code to be 500, and since that is what I expect, I want the line to turn green.
It's a negative test.

**Comment by fhoeben** [comment]
If you want to do a negative test, i.e. the 500 error code, just add 
```|reject``` before the ```|post|```
It's a standard Slim feature for negative tests :-)
http://fitnesse.org/FitNesse.FullReferenceGuide.UserGuide.WritingAcceptanceTests.SliM.ScriptTable

**Comment by djlestephane** [comment]
Thanks @fhoeben, I've checked your examples again, and it's very well explained in XmlHttpTest/content.txt
