### ISSUE TITLE
The fixture has @Before and @After as junit?

### ISSUE THREAD

**Issue by zgq1987** [fhoeben/hsac-fitnesse-fixtures#194]
T want to do some things  before the fixture and after the fixture ,how can I do it?

**Comment by fhoeben** [comment]
Just put some things on the wiki page before the 'script table' using the fixtures.
FitNesse also has features such as a SuiteSetUp, SetUp, TearDown and SuiteTearDown pages that are executed before/after a suite, or each page in a suite.

It depends on what/when you want to do....

**Comment by zgq1987** [comment]
Can I put it in the fixture. I don't want show it in the page

**Comment by fhoeben** [comment]
you can just subclass and do whatever you want

**Comment by zgq1987** [comment]
I want to start a server before the tableTest 
 begin, and stop the Server berfore the tableTest end.   just subclass? How do it

**Comment by fhoeben** [comment]
I do this in my acceptance test, see for instance [HsacAcceptanceTests.SlimTests.BrowserTest.AriaLabelledTest](https://fhoeben.github.io/hsac-fitnesse-fixtures-test-results/acceptance-test-results/HsacAcceptanceTests.SlimTests.BrowserTest.AriaLabelledTest.html) (also available in a local installation), but not with changes to the fixture but with a separate table on the page.

In general I can't help you how to start your server. But in your subclass you could add commands to the constructor to always start the server (constructor is called based on script's first row), or you could add a method to start and a method to stop (which you would then call from rows in the script)

Would it not be better to start the server for each test (in a SetUp page), or once for the entire set of tests (in a SuiteSetUp page)?

**Comment by zgq1987** [comment]
Many Thanks.I try it.
