### ISSUE TITLE
JSONHttpTest-DeleteWithBody

### ISSUE THREAD

**Issue by AgalyaKothan** [fhoeben/hsac-fitnesse-fixtures#195]
I don't see the option available to delete by passing body instead of header. Is it possible to add a method to do it?

**Comment by fhoeben** [comment]
I've never had to send a body with a DELETE. What needs to happen?

A quick google brings me to https://stackoverflow.com/questions/299628/is-an-entity-body-allowed-for-an-http-delete-request#answer-10015724

I see no real problem to have it be supported, but what would have to be sent, only body or also headers. What would a call from the wiki look like?

Can you (get someone to) create a pull request?

**Comment by AgalyaKothan** [comment]
Wiki should look like 
!define GOOD_BODY { {{{
json={"key":"value"}
}}} }

|script|json http test                                              |
|Delete  |${GOOD_BODY}         |from      |http://validate.jsontest.com/|
|show  |response                                                    |

Only body has to be sent. I dont have anyone to create pull request now. Help on this would be really appreciated.

**Comment by AgalyaKothan** [comment]
Body contains list of ids that needs to be deleted from the database.

**Comment by fhoeben** [comment]
Check. That would make this request a POST to a delete service. (Last time, we were both working for a company where standard REST policies said all service calls must be POST. DELETE and PUT should not be used. Why not stick to that? What's the advantage going for DELETE?)

**Comment by AgalyaKothan** [comment]
They revisited standard REST definition, we should have a same endpoint URL with different HTTP methods. For ex: create card should be /cards with HTTP.POST, get card details should be /cards with HTTP.GET and delete card should be /cards with HTTP.DELETE. 
In this case we are in need to use respective http status methods to differentiate the service calls from SPA.

**Comment by fhoeben** [comment]
What I think will be needed to properly support this is 3 methods added to the fixtures:

In HttpTest:
* `delete <url> with <body>`
* `delete <url> with template`

In JsonHttpTest:
* `delete <url> with values as json`

It doesn't seem like an awful lot of work, but it is work, and I don't know whether I'll get round to it shortly. Maybe you can have a shop around whether someone else has some time to create a pull request (I'm sure there are some people that understand Java around in your team).

@keetron, do you have some time to help @AgalyaKothan?

**Comment by AgalyaKothan** [comment]
Yes I can check...

**Comment by keetron** [comment]
Ok, considering I am lazy, I will take the method `postToImpl` and adjust it so it will do a `delete` instead of a `post`.
Let me fiddle with this, I think it is not even that complicated, only for the many little methods scattered about (which I understood is good coding)

**Comment by keetron** [comment]
#197 

There you go. I checked for unit tests but did not see any related to these functions to begin with.
Also ran the full suite, I ran into a couple of warnings but was unsure how to manage that as it was completely unrelated to what it was I changed.

**Comment by fhoeben** [comment]
Sending a DELETE with a body is not directly supported by the http client library we use (apache http client). We need to define our own 'method' class. See for instance: https://daweini.wordpress.com/2013/12/20/apache-httpclient-send-entity-body-in-a-http-delete-request/

**Comment by keetron** [comment]
Oh, this would complicate matter quite a bit.
I am not sure when I have time to rebuild the PR so I will retract it for
now.

**Comment by fhoeben** [comment]
Delete with body will be possible in 3.19.0
