### ISSUE TITLE
Wait for a value to change

### ISSUE THREAD

**Issue by violinner** [fhoeben/hsac-fitnesse-fixtures#198]
In the scenario that a button has been clicked, and the page will repaint concluding with a change in an element, i.e., <id=status> changes from "please wait a moment" to "all done", Is there a convenient way to wait for the change in BrowserTest?  WaitForVisible does not seem to cover this well.

**Comment by fhoeben** [comment]
I'm not sure I understand the question correctly. The page automatically refreshes until 'all done' is shown? In that case a '|wait for visible | all done|' seems a good fit.

Or do you mean you have to do something, e.g. click a button or use the browser's refresh button, to update the page, and then you want to see whether 'all done' is shown?
In that case: 'refreshUntilValueOfIs' or 'clickUntilValueOfIs' seems to fit the bill.

**Comment by tcnh** [comment]
You could experiment using `| is (not) visible (on page) | value |`
If refreshing doesn't cause issues, there is `| refresh until value of | place | is (not) | value |`
You could also (ab)use `| execute javascript | 0 | until value of | place | is | value |`

Creating a new method `| wait until value of | place | is | value |` should be pretty easy to create, too.

**Comment by violinner** [comment]
The element [id='status'] is updated from JavaScript on the page when an Ajax call is finished, so doing a page refresh is not appropriate.
I will write "| wait until value of | place | is | value |"  ( waitUntilValueOfIs(String place, String value) ), and declare victory.  thanks.

**Comment by violinner** [comment]
I have created a new method "| wait until value of | place | is | value |"
and would like to suggest it as a contribution in a new branch.

Is there a permission I should request to be able to create the branch?

**Comment by fhoeben** [comment]
@violinner you can fork the repository add a branch in your fork and then create a pull request.

Looking back at this issue I don't quite follow why 'wait for visible' is not appropriate. This will wait for the element to appear, so any background JavaScript should be fine. If you have to wait a long time you could use 'seconds before timeout' to configure a specific maximum time to wait.

Is there any particular reason why you can't just use `|wait for visible|all done|` or `|wait for visible|all done|in|id=status|` or `|wait for visible|xpath=//*[@id='status' and text()='all done']|`?

**Comment by violinner** [comment]
This works:

|wait for visible|Processing|in|id=status|
|wait for visible|done         |in|id=status|

Thanks again.

**Comment by violinner** [comment]
This is _very_ useful, thanks for the hint:
```
|$x=|value of|id=last_timestamp|
|| click "update with filter", then wait for timestamp to change: |
|wait for visible|xpath=//*[@id='last_timestamp' and text()!='$x']|
```
