### ISSUE TITLE
Do you support PUT

### ISSUE THREAD

**Issue by benjammin17** [fhoeben/hsac-fitnesse-fixtures#20]
If not would you have any plans to add it?

**Comment by fhoeben** [comment]
I don't support it at the moment and I have no plans to add it (all my environments don't use PUT but prefer POST). But I think it would be quite easy to add. 

I'm currently working on upgrading to the latest FitNesse, so I can't do it for you right now.

I would have no objection to incorporating a pull request...

**Comment by benjammin17** [comment]
The devs have added put support, but in my test environment, after an upgrade from 1.10 to 2.0, my plans no longer run. I cant find anything in your documentation to help. If we can figure out what we need to update then 
For example:

| script | json http test |
|table template|send request|
|set content type|application/json|

 Could not invoke constructor for TableTemplate[1]
 The instance decisionTable_1.setSetContentType. does not exist

**Comment by fhoeben** [comment]
I'm sorry to hear the tests no longer run. How did you upgrade your installation? Did you pull my changes, or did you download a new copy of the standalone installation and unzipped, or did you update a maven reference, or ...?

From your last comment I can't quite make out what your page looks like. Can you edit the comment to put the exact wiki content between 3 backticks (i.e. '\`\`\`'  and '\`\`\`', see GitHub's Markdown help)? So I can see the newlines (there should be an empty line before `|table template|send request|`), etc?

Have you got the file `hsac-fitnesse-plugin-1.11.1.jar` in the plugins directory of your wiki installation?

**Comment by benjammin17** [comment]
Yes I do have the plugin in the plugins directory.
We are running on a CentOS server with Java 8. We did an upgrade but I dont remember exactly what we did. 
I decided today to just start with a brand new installation (from hsac-fitnesse-fixtures-2.1.1-standalone.zip) and import our existing plans. We may need to take this step by step.
First, I noticed that you are not including nl.hsac.fitnesse.slim.interaction.InterceptingInteraction in your build. We have defined
!define slim.flags {-i nl.hsac.fitnesse.slim.interaction.InterceptingInteraction}

**Comment by benjammin17** [comment]
I'm getting closer.
I removed InterceptingInteraction (I noticed that it was a temp solution anyway).
Reformatting some of the tables (adding or removing empty columns that apparently were not needed before the upgrade) helped. This has fixed many of my tests. This new build may be more strict on rules of table structure?

**Comment by fhoeben** [comment]
`InterceptingInteraction` indeed is no longer needed with the latest FitNesse (2.1 of my project). I should have made that more explicit in the release notes.

I have not changed anything regarding table structure, but maybe the new FitNesse release is more strict in that respect?
Where do you need empty columns (I have not come across that myself)?

Any chance your PUT changes can be incorporated in the main project (can you, or your devs, make a 'pull request' for it)?

**Comment by benjammin17** [comment]
I'm going to start testing the PUT changes here in a bit when I get test plans updated for this latest fitnesse build. I'll let you know when we are successful.
As for what I had to change in my plans, for example, below, clear header values would throw an exception. Below is a portion of the case:

| script | json http test |

|table template|send request|
|set content type|application/json|
|clear header values||


I would get:
Method clearHeaderValues[1] not found in nl.hsac.fitnesse.fixture.slim.JsonHttpTest.

But after removing that extra blank column next to clear header values, the case went successful. I suppose this was just sloppy writing and copy/paste spread the sloppyness all over my plans. 
I also was missing a blank line between |script|json http test| and the variables above it. 
So it just seems they have become more strict on the formatting of test pages. For us we only have about 30, but should have about 100 this year.
