### ISSUE TITLE
GMail Oauth fixture

### ISSUE THREAD

**Issue by tcnh** [fhoeben/hsac-fitnesse-fixtures#200]
I've cooked up a utility fixture to fetch and get data from specific e-mails from a gmail account. Useful for testing confirmation links in e-mails, or password reset flows etc. It's a lot faster and less verbose than using imap(s) or smtp for this. It also removes the need for mail account credentials or endpoint configuration in test cases.

I could create a PR that adds this fixture, however it does add 3 Google API dependencies and has a pretty specific user manual (You need to configure your test Google account to enable the oauth API). So maybe a separate artifact in its own repo with its own readme is a better solution?

So, what would you say: PR or just move it to a separate maven package to optionally add as a dependency to test projects?

**Comment by fhoeben** [comment]
I guess you did not find the repo I created to get e-mails: https://github.com/fhoeben/hsac-fitnesse-email
Or did that lack functionality? It seems like a pull request there with extra features would be most logical choice?

**Comment by tcnh** [comment]
No, I didn't. Funny thing is that the interface is not very different. I have a few keywords your fixture doesn't expose and v.v. 

I'll see if I can find the time to integrate the two, so that we can choose how to connect and use the same keywords for both imaps and oauth.
