### ISSUE TITLE
click |Open| in row number|1| fails on time-outs

### ISSUE THREAD

**Issue by pvreeuwijk** [fhoeben/hsac-fitnesse-fixtures#209]
In our script, fitnesse opens a menu displaying orders.
The details of an unsend order can be viewed by clicking on the status:

|click | Open | in row number | 1|

The script expected a detail screen to be opened but a time-out is received instead. In the attached screenshot the page looks ok and the Open link is displayed.

driver info:
org.openqa.selenium.chrome.ChromeDriver

acceptInsecureCerts	false
acceptSslCerts	false
applicationCacheEnabled	false
browserConnectionEnabled	false
browserName	chrome
chrome	{chromedriverVersion=2.37.544315 (730aa6a5fdba159ac9f4c1e8cbc59bf1b5ce12b7), userDataDir=C:\Users\PVREEU~1\AppData\Local\Temp\scoped_dir12316_31396}
cssSelectorsEnabled	true
databaseEnabled	false
handlesAlerts	true
hasTouchScreen	false
javascriptEnabled	true
locationContextEnabled	true
mobileEmulationEnabled	false
nativeEvents	true
networkConnectionEnabled	false
pageLoadStrategy	normal
platform	XP
platformName	XP
rotatable	false
setWindowRect	true
takesHeapSnapshot	true
takesScreenshot	true
unexpectedAlertBehaviour	
unhandledPromptBehavior	
version	66.0.3359.181
webStorageEnabled	true

**Comment by fhoeben** [comment]
It sounds like browser test can not find 'Open' in the first row it encounters. For the 'in row number' commands to work the row must be a `tr` inside a `table` element, and 'Open' must be either the header text (`th`) of the cell containing the status, or a hyperlink with text 'Open', or an element with `title` attribute 'Open', or something with an `aria-label` attribute with value 'Open'

Can you share (part of) the html of the table containing the row with 'Open'?

If you can only share part of the html, are there more tables on the page (i.e. is it possible that browser test is looking at the first row of the 'wrong' table)?

**Comment by pvreeuwijk** [comment]
In the 1st row, 1st td there's a link, but the link text is in a div.
<td> <a> <div> Open </div> </a> <td>

The div might be spoiling things?

**Comment by fhoeben** [comment]
I don't believe the `<div>` should cause a problem. 
Can you reproduce the problem using a small sample HTML? Something like HsacAcceptanceTests.SlimTests.BrowserTest.GridTests.GridTest

The test below (which I based on your response) is green, no problem finding 'Open'... 

```

!define HTML { {{{
<!DOCTYPE html>
<html lang="en">
<body>
<table>
    <tr><td><a href="#"><div>Open</div></a></td><td>Joey</td><td>Black</td><td>Unknown</td><td>11-01-1975</td><td><button>Edit</button><button>Delete</button></td></tr>
</table>
</body>
</html>}}} }


|script      |mock xml server setup|
|add response|${HTML}              |
|$url=       |get mock server url  |

|script                |browser test                                                                                          |
|seconds before timeout|1                                                                                                     |
|open                  |$url                                                                                                  |
|click|Open|in row number|1 |


|script|mock xml server setup|
|stop                        |

```

**Comment by pvreeuwijk** [comment]
Hi,

Thanks for the help!
We've discovered in the end there's a new table in the header of our application. Rather unexpecteded. 
When we add a 'set search context to' to the script the command works again.
We can close this issue.
