### ISSUE TITLE
Unchecked checkbox to be default

### ISSUE THREAD

**Issue by suval** [fhoeben/hsac-fitnesse-fixtures#21]
I have a problem with browser test, everytime i run same test it keep the checkbox checked/unchecked depends on previous test. What should i do do make it always be unchecked?
(already made in browser not to save cookies and used in wiki delete cookies command but it didnt help)
thanks i advance

**Comment by fhoeben** [comment]
I don't know, this depends on how the site implemented this feature. 

Did you try clearing local storage also?
Does the behavior persist if you visit another site between the two test runs?

**Comment by suval** [comment]
Q:Did you try clearing local storage also?
yes, but it does not resolve problem

Q:Does the behavior persist if you visit another site between the two test runs?
yes,

I use CLICK command to make the checkbox checked, then i OK to accept the form so it goes to next page. After clicking accept it makes the checbox checked, if i dont click accept it does nothing, i can click the checkbox several times and it does not save it between tests. I tried clear local storage command before accept form and after but still have the problem


Is there any possibility to make selenium not to save local storage defaulty?

**Comment by fhoeben** [comment]
I'm not aware of any mechanism beyond cookies and local storage to save data in a browser.

Which browser are you using? Do you see the same behavior with all browser?

I have seen in the past that some browsers (Internet Explorer and Safari), do not delete all cookies when requested (HTTP-only cookies) only a full stop and restart of the browser did that. 
But you describe multiple runs of the same test, so I assumed the browser was closed in between the runs.

I really don't know what to make of this. Is there any chance I can visit the site myself to see what is happening?

**Comment by suval** [comment]
Nvm, it was developed to keep user settings between sessions as some1 told me. Thank you for your time.
