### ISSUE TITLE
Enter quotation marks in any field

### ISSUE THREAD

**Issue by maikelgithub** [fhoeben/hsac-fitnesse-fixtures#210]
Hi,

I have a problem while filling in quotation marks in my scripts in FitNesse. 

This is my sample script:
|script                                 |
|open |https://www.google.nl            |
|enter|"FitNesse"     |as   |id=lst-ib  |
|press enter                            |
|show |take screenshot|Quotation Example|

However, the text passed on to the browser is only FitNesse where I am expecting "FitNesse". Please check the screenshot below for the result.

![image](https://user-images.githubusercontent.com/29131018/40409394-14ed0be4-5e6b-11e8-915f-e75b2225e22f.png)

I also noticed that this is not an issue on Mac OS, but only on Windows.

Is there any limitation on Windows, that this isn't possible? Or is this a bug in FitNesse?

Thank you in advance for your response.

**Comment by joroelev** [comment]
Just enclose the string you want to enter in !- -! FitNesse will then tread it as literal text. Also see: http://www.fitnesse.org/FitNesse.FullReferenceGuide.UserGuide.FitNesseWiki.MarkupLanguageReference.MarkupLiteralText

**Comment by tcnh** [comment]
This is a windows chromedriver issue. See my comment in https://bugs.chromium.org/p/chromedriver/issues/detail?id=1789 (that issue is closed, because it was merged with 932, but still exists)

This can be fixed by having the us english locale installed on the windows machine. You don't need it active. Just installed fixes the issue.

**Comment by maikelgithub** [comment]
thank you @tcnh (Tom), this workaround generates the expected output.

**Comment by joroelev** [comment]
@tcnh . I was already wondering why the !--! approach was working for me and not for @maikelgithub. Turned out the the right language was already installed. Thanx for the link!
