### ISSUE TITLE
setPropertyValue("webdriver.chrome.driver", driverPath);

### ISSUE THREAD

**Issue by boredland** [fhoeben/hsac-fitnesse-fixtures#212]
Hi there!
I tried setting the driverPath using the method "setPropertyValue":
`|setProperty     |webdriver.chrome.driver|Value       |fitnesse-fixture/drivers/chromedriver-linux-64bit|`
That has no effect, I guess, due to the ProjectDriverFactoryFactory.create(..) overwriting it. Would it be necessary to add some check for this or is there a way to set a custom path for the webdriver?

**Comment by fhoeben** [comment]
Setting the property does work, only that property value is not used when you start a selenium driver using '|start driver for|chrome|` since that expects to start a driver embedded in the project. You can start a driver using a custom location using:
```
|selenium driver setup|
|set property |webdriver.chrome.driver|value |fitnesse-fixture/drivers/chromedriver-linux-64bit|
|start driver|!-org.openqa.selenium.chrome.ChromeDriver-!|
```
