### ISSUE TITLE
is visible doesn't find texts after a <br>

### ISSUE THREAD

**Issue by pvreeuwijk** [fhoeben/hsac-fitnesse-fixtures#216]
Our application uses a div to show a list. There is very little formatting, the lines are just seperated by a html <br> within the div.
example:
<div class="GuidanceText_FullText">3 maal per dag 1 tablet<br>Kuur afmaken<br>Innemen met wat voedsel</div>

This content is being tested by:
|ensure|is visible|3 maal per dag 1 tablet                  |
|ensure    |is visible         |Kuur afmaken                    |
|ensure    |is visible         |Innemen met wat voedsel |

The problem is: Only the 1st line is seen. The 2nd and 3th lines are failing.

**Comment by fhoeben** [comment]
Very strange. Can you post the exact HTML, to reproduce the problem (possibly even in a .wiki format, like HsacAcceptanceTests for BrowserTest use)?

**Comment by pvreeuwijk** [comment]
Good suggestion to create a HsacAcceptanceTests, I found the problem lies somewere else in the complex page. Creating a mock xml server for pin pointing these issues is very useful, thanks
