### ISSUE TITLE
feature request: tag information in test results

### ISSUE THREAD

**Issue by inico** [fhoeben/hsac-fitnesse-fixtures#218]
Hello,

I was wondering if it is possible to enable the passing of the "tag" of a fitnesse page & suite when executing these in the XML output files when you runs a suite. This way it allows for the test reporting of multiple suites/tags to either isoalate orr aggregate on these tags whcih can help to build dashboards (like in ELK or splunk).

Kind regards,
Inico Veringa

**Comment by fhoeben** [comment]
I use a 'standard' surefire xml report format (I believe). Is there an element in such a document to embed tag/group information? Then we could add it.
I believe it is done in the [allure listener](https://github.com/fhoeben/allure-fitnesse-listener), but that uses a specialised test runner if I recall correctly.

**Comment by tcnh** [comment]
No custom runner is needed. As @fhoeben mentions, the allure listener grabs the tags. This can easily be implemented in any custom junit listener (or added to the default listener in a PR):

Have a look at https://github.com/fhoeben/allure-fitnesse-listener/blob/master/src/main/java/nl/hsac/fitnesse/junit/allure/JUnitAllureFrameworkListener.java too see the implementation there (grab the wikipage object using FitnessePageAnnotation and then get the tag by getting "Suites" from the page properties)
