### ISSUE TITLE
Question : Setting Delay in Test Suite FitNesse Slim Test

### ISSUE THREAD

**Issue by ybermejo** [fhoeben/hsac-fitnesse-fixtures#221]
Hi, 
I'm new in using FitNesse for automation testing and am using slim. I have a test suite and need to set a delay in between test steps. Need help folks how this thing to be done. Any help will appreciate.

sample Flow:
call Service 1
delay 4000ms
call Service 2

**Comment by tcnh** [comment]
99/100 Times fixed wait times are a bad idea.. if you wait 4000ms today, I bet your service takes 4005 to complete tomorrow ;-)

Is there an expected outcome you could wait/poll for using the repeat until ... methods?

**Comment by ybermejo** [comment]
Hi @tcnh 
Sorry but I don't get you. I need to set up a 4 second delay before calling the Service 2. I'm not sure what's the logic behind the service I'm calling and testing, all I know is it requires that delay. Is it feasible?

**Comment by Romancha** [comment]
You can use "wait" method.

|wait|4|seconds|

**Comment by tcnh** [comment]
> I need to set up a 4 second delay before calling the Service 2. I'm not sure what's the logic behind the service I'm calling and testing, all I know is it requires that delay. Is it feasible?

You could extend the fixture you're using with a wait method. The method @romancha mentions is in BrowserTest. 

Still, personally I would investigate what you're waiting for (i.e. what changes after these 4 seconds) and wait for that to happen. It will make your tests more robust.

**Comment by ybermejo** [comment]
Thanks @Romancha, is it right to put the method in the next service to cal (e.g Service 2) or after the previous service? And how will I verify that the method works?

Hi @tcnh , will consider that and do some investigation why delay is needed. Thanks.
