### ISSUE TITLE
FitNesse: Extract value from Soap Envelope Response

### ISSUE THREAD

**Issue by ybermejo** [fhoeben/hsac-fitnesse-fixtures#223]
Hi All,

Need help on how to extract value from soap envelope response. Right now I'm trying to use xPath expression in XmlHttpTest (https://github.com/fhoeben/hsac-fitnesse-fixtures/wiki/2.-Slim-Fixtures#xmlhttptest ). 
I need to get the value **MembershipId** tag.
![image](https://user-images.githubusercontent.com/40356873/43001907-98a34360-8c59-11e8-9648-8b3570e6ee07.png)

Here's my code but I don't know what correct path to place in the yellow section.
![image](https://user-images.githubusercontent.com/40356873/43002050-04dc33d4-8c5a-11e8-979e-3d080f99f858.png)

Hoping for any response. Thanks :)

**Comment by fhoeben** [comment]
I take it you figured out how to get the value yourself?

**Comment by ybermejo** [comment]
Hi @fhoeben,
Yeah already figured out. I just missed the /text() and removed the $responseBody in the last row. Thanks anyway :)
