### ISSUE TITLE
Question: Unable to run a test in Fitnesse

### ISSUE THREAD

**Issue by ybermejo** [fhoeben/hsac-fitnesse-fixtures#228]
Hi All,
Is anyone experienced or know how to solve this issue? I'm not sure if its because of my machine. Need your help guys.
![image](https://user-images.githubusercontent.com/40356873/43910777-508c5bde-9c30-11e8-84f5-d3ec0f5d0a29.png)
![image](https://user-images.githubusercontent.com/40356873/43910963-cb116e26-9c30-11e8-9b8a-0be705b9e04e.png)

**Comment by fhoeben** [comment]
Like the message says, this is a message from the Java virtual machine (nothing FitNesse specific about it) that states that your machine is out of memory (both real and virtual) and therefore the JVM can not allocate the memory it needs.

You can either stop/close some processes that are running, or reboot your machine, and see whether that helps. If it keeps occurring you probably need to troubleshoot what is eating your memory (and ensure it stops doing that) or add memory to your machine.

This error has nothing to do with this project, so I'm closing the issue.
