### ISSUE TITLE
Assertion for check for raw response for webservice is possible ?

### ISSUE THREAD

**Issue by VinayGitDemo** [fhoeben/hsac-fitnesse-fixtures#235]
Hi,
I want to assert the complete raw response which is coming as the output of my web service.
I used this one.

|check |Get raw response |my expected xml string |output xml string|

But if run Test am receiving below error :

![image](https://user-images.githubusercontent.com/38095296/47346652-42124980-d6cb-11e8-8407-bd66c36f8307.png)

**Comment by tcnh** [comment]
There is no get raw response method.
Have you tried:

`|check|response|expected response|` ?

**Comment by VinayGitDemo** [comment]
Hi ,
Thanks for response !!
Tried same way but got below error.

![image](https://user-images.githubusercontent.com/38095296/47351944-9ff85e80-d6d6-11e8-8bd3-0ba1949be578.png)

**Comment by VinayGitDemo** [comment]
Hi ,

Also tried as you suggested, but received below error. Here, if past same I guess, XML format should also match.



![image](https://user-images.githubusercontent.com/38095296/47353243-61b06e80-d6d9-11e8-906a-aebb620322d6.png)

![image](https://user-images.githubusercontent.com/38095296/47353272-77be2f00-d6d9-11e8-8d1e-314adb788711.png)

**Comment by tcnh** [comment]
Do you really need to check the full response to be exactly your expectation?
There's a few issues here: 
 1 your expected xml is not escaped in the wiki, resulting in html code being sent.
 2 you're checking against a formatted response, so I expect using a plain text validation will be hard, try using a preformatted wiki block.

But much better: have a look at using xpaths for validation. This allows you to write readable checks for specific data in your responses,.
