### ISSUE TITLE
Can't build the project. The Maven 3.6.0 is incompatible with org.apache.portals.jetspeed-2 plugin.

### ISSUE THREAD

**Issue by Solwo** [fhoeben/hsac-fitnesse-fixtures#238]
**How to reproduce:**
1. Clone https://github.com/fhoeben/sample-fitnesse-project
2. mvn clean compile exec:exec

the same error in the fhoeben/hsac-fitnesse-fixtures project.

**Message:**
[ERROR] Failed to execute goal org.apache.portals.jetspeed-2:jetspeed-unpack-maven-plugin:2.3.1:unpack (copy-hsac-baseline) on project sample-fitnesse-project-using-hsac-fixtures: Unable to parse configuration of mojo org.apache.portals.jetspeed-2:jetspeed-unpack-maven-plugin:2.3.1:unpack for parameter pluginArtifacts: Cannot assign configuration entry 'pluginArtifacts' with value '${plugin.artifacts}' of type java.util.Collections.UnmodifiableRandomAccessList to property of type java.util.ArrayList -> [Help 1]

**Environment:**
https://github.com/fhoeben/sample-fitnesse-project/tree/c7a5e1367d45bf5466db89d09e6980a5ae74af26

Apache Maven 3.6.0 (97c98ec64a1fdfee7767ce5ffb20918da4f719f3; 2018-10-24T21:41:47+03:00)
Maven home: C:\Tools\Maven6\bin\..
Java version: 1.8.0_191, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk1.8.0_191\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows server 2016", version: "10.0", arch: "amd64", family: "windows"

Last supported Maven is v. 3.5.4,  compiled without problems.

**Related:**
https://issues.apache.org/jira/browse/MNG-6504
https://issues.apache.org/jira/browse/JS2-1366

**Comment by tcnh** [comment]
Came across this issue as well with maven 3.6.0.
To work around it: replace the jetspeed plugin entry in your pom.xml with: 
```
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <version>3.1.1</version>
                <executions>
                    <execution>
                        <id>copy-hsac-baseline</id>
                        <phase>generate-resources</phase>
                        <goals>
                            <goal>unpack</goal>
                        </goals>
                        <configuration>
                            <artifactItems>
                                <artifactItem>
                                    <groupId>nl.hsac</groupId>
                                    <artifactId>hsac-fitnesse-fixtures</artifactId>
                                    <version>${hsac.fixtures.version}</version>
                                    <type>zip</type>
                                    <classifier>standalone</classifier>
                                    <overWrite>false</overWrite>
                                    <outputDirectory>${project.basedir}/wiki</outputDirectory>
                                    <excludes>fixtures/nl/**,fixtures/templates/**</excludes>
                                </artifactItem>
                            </artifactItems>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
```

You now use the standard maven dependency plugin to unpack the zip and no longer need jetspeed.
@fhoeben I don't think I'll find time to create a PR before thursday. :(

**Comment by fhoeben** [comment]
I see the dependency plugin still uses a marker file to determine whether to overwrite on unpack. That is unfortunate.

**Comment by tcnh** [comment]
That's unfortunate. I assumed the overwriteIfNewer parameter would work per file, but that seems not to be the case

**Comment by fhoeben** [comment]
Merged into sample project
