### ISSUE TITLE
check number of times doe snot count over (i)frames

### ISSUE THREAD

**Issue by jecepede** [fhoeben/hsac-fitnesse-fixtures#243]
Aloha !

The following code : 

```
| script                                                         |
| check | number of times | searchForSomething | is visible  | 2 |
```

Does not seem to work when a page has (i)frames. The 'searchForSomething' is not counted correctly. The search 'forgets' it has (i)frames and skips them in the count resulting in a failed test.

A work-around can be by swithing to the specific (i)frame before doing the a search. Note, if you have nested (i)frames, you will need to switch a number of times to reach the correct destination-(i)frame. In my case I did :

```
| switch to parent frame                                         |
| switch to frame |name=main                                     |
| switch to frame |id=nested-frame                               |
| check | number of times | searchForSomething | is visible  | 2 |
```

Cheeeeeeeeeers,

Jecepede

**Comment by jecepede** [comment]
Oops sorry, 

Perhaps I I had to mention this.
I did fiddled with the concept but it did not make any differene. Eg :

```
|switch to parent frame                |
|set implicit find in frames to | true |
```

Even then it still counts incorrectly.
Also, if I understood the code in the right way, this setting is true by default.


Cheeeeeeeeeeeers

Jecepede

**Comment by fhoeben** [comment]
My point was that BrowserTest should not sum over all iframes if the boolean was set to false in the test. (You are right it is true by default)
