### ISSUE TITLE
Abort suite of suites on timeout, or any failure

### ISSUE THREAD

**Issue by violinner** [fhoeben/hsac-fitnesse-fixtures#245]
In the automated CI build, I would like to immediately fail out of all the FitNesse suites for a build on first failure, or if a timeout has been exceeded.

For the first case, is there any way for a fixture to tell if any test command has failed up to a certain point?

For the second case, I'm guessing that if BrowserTest is extended and in the constructor checks the current time against a deadline in an nl.hsac.fitnesse.fixture.Environment.getSymbol() entry, it can raise a StopSuite Exception.  This will quickly exhaust the entire hierarchy of Suites.

Do you have any advice on these?

**Comment by fhoeben** [comment]
I have not thought about this extensively but maybe the TimerFixture can already (or be easily extended) to stop the suite if a timer exceeds a certain value. This could then be called in a 'SetUp' page so it is checked before each test is started.

Aborting a run on first failure seems like something that requires a change to the test runner. Maybe you can create your own subclass of HsacFitNesseRunner? Maybe you could make a PR to make it configurable, based on a system property.

**Comment by tcnh** [comment]
I faced a similar request (stop on first exception, in that case a timeout). Solved that by extending browsertest and overriding exception handling, catching timeout exceptions, handling them and throwing a stoptestexception.

**Comment by violinner** [comment]
in Setup, TimerFixture can retrieve the elapsed time on a timer started in SuiteSetup.

StopTestFixture does not have a method "stopTestIfExceeds(actual, expected), i.e.,:
| stop test if | $x | exceeds | 32768 |

Adding this locally to an extension of StopTestFixture, and can now halt the Suite of Suites on an unexpectedly long test.

**Comment by violinner** [comment]
Does HsacFitNesseRunner only run through JUnit?
I need to listen for failures encountered in the page walker when FitNesse is run with a command, i.e.:
"-c MyIntegrationSuite".

**Comment by fhoeben** [comment]
HsacFitNesseRunner is for running via jUnit. 
For other scenario's you probably need to create you own test system listener.

**Comment by fhoeben** [comment]
See also https://github.com/unclebob/fitnesse/issues/1171

**Comment by tcnh** [comment]
@fhoeben I'm getting a similar question in another project. It seems that more peaople are interested in stopping a (browser) test in case of an exception. (I'm guessing this mainly concerns browserTest, because those tends tend to become very time consuming when continuously running into timeouts.)

Until now, if someone wanted this, I suggested extending browser test using the following approach:
```
public class CustomBrowserTest extends BrowserTest<WebElement> {
    private boolean abortOnException;

    public void abortOnException(boolean abort) {
        abortOnException = abort;
    }

    @Override
    protected Throwable handleException(Method method, Object[] arguments, Throwable t) {
        Throwable result = super.handleException(method, arguments, t);
        if(abortOnException) {
            String msg = result.getMessage();
            if (msg.startsWith("message:<<") && msg.endsWith(">>")) {
                msg = msg.substring(10, msg.length() - 2);
            }
            result = new StopTestException(false, msg);
        }
        return result;
    }
}
```
Do you think it's a good idea to implement this into BrowserTest (or even SlimFixture) directly? If so, I can do a PR on that. 
However, it feels a bit like symptoms management where one should actually create tests that are reliable enough to not need this behaviour (or explicitly stop when going off the rails by using 'wait for x' or 'stop test if y is (not) z' in strategic locations)

**Comment by fhoeben** [comment]
@tcnh it indeed looks a bit like symptoms management. But since what I believe @violinner is looking for is a way to abort an entire suite (not just the current test like in your sample code, this would be a simple change to the code) I don't believe there  currently is a way to achieve the result desired.
And to abort a suite on first failure is something that I don't believe any fixture could ever achieve.

I really think a generic handler inside fitnesse would be a better fix for the problem desired.

**Comment by violinner** [comment]
This was good enough, and works with a range of versions of FitNesse:

A test listener plug-in creates a file "fit-stop-test" on encountering an error.

A StartUp .wiki page contains a test table invoking an extended StopTest fixture.

On encountering the file "fit-stop-test", StopTest fixture throws a StopSuiteException.

StartUp is inherited for all tests in all the suites, so it causes FitNesse to abort all the Suites after the test listener plug-in "hears about" an error or exception.

**Comment by fhoeben** [comment]
What I've seen happening with BrowserTest is that the browser process (e.g. chrome) dies and the suite keeps on running but is not able to do anything and this makes the run EXTREMELY slow.

It would be very good to detect that situation and abort the suite when that happens. I don't know how to detect that yet as the selenium WebDriver instance (and chromedriver process) are still there.

But this should be a different issue.

**Comment by violinner** [comment]
This is related, as the work-around is similar:

A FitNesse plug-in can watch for test failures, and also watch after every test for the existence of the firefox process (fork tasklist.exe and read the list from process.getInputStream()).

Lacking better communication between plug-in and fixtures, a tell-tale file can be dropped into the workspace on errors, such as "firefox is not running."

In the BrowserTest suite, a test, i.e., an extension of StopTestFixture) in SetUp.wiki can test for the existence of the tell-tale file and throw a SuiteException if it is there.  This will end every suite after the plug-in discovers that FireFox is not running.

**Comment by violinner** [comment]
I will look into it.  The same solution applies as with the
"abort-on-first-error" solution:

-register a custom listener when starting the test suite.
- the listener is called back on every test step.
-if the test step calls a browser test method but a browser is not running,
write to a file with a conventional name.
- the test suite has a SetUp page at the root.
-SetUp invokes a custom fixture that throws a SuiteException if the
conventional file ids found.
-all tests and Suites quickly fail.
