### ISSUE TITLE
documentation: 'set repeat interval to interval' needs to be called as 'set repeat interval to milliseconds'

### ISSUE THREAD

**Issue by pvreeuwijk** [fhoeben/hsac-fitnesse-fixtures#246]
In the documentation is the method 'set repeat interval to interval'
This can not be called as the method is implemented as setRepeatIntervalToMilliseconds(int milliseconds)

proposed solution

update documentation

or

change the method to setRepeatIntervalToMilliseconds(int milliseconds)
maybe have  setRepeatIntervalToMilliseconds(int milliseconds) call the function for backward compability.

**Comment by fhoeben** [comment]
Good catch. I believe just changing the documentation is the easiest fix (and backward compatible).

**Comment by fhoeben** [comment]
Fixed. it was already ok in the bundled wiki as far as I can tell, so I just updated the wiki here on GitHub
