### ISSUE TITLE
extracting am images alt label

### ISSUE THREAD

**Issue by pvreeuwijk** [fhoeben/hsac-fitnesse-fixtures#251]
In browser test I can identify the presence of an image based on its alt tag using something like:
|ensure | is visible | xpath=//img[@alt='c285cdc16eb8']

but retieving it's value by using @ alt doesn't seem to work:
|$qrlink<-[null] | value of | xpath=//img/@alt|

is there any support for this?

**Comment by fhoeben** [comment]
Yes:
`|$qrlink=|value of attribute |alt| on |xpath=//img|`

A 'place' is always an element
