### ISSUE TITLE
nl.hsac.fitnesse.fixture.slim.StopTestException: Cannot use Selenium before configuring how to start a driver (for instance using SeleniumDriverSetup)

### ISSUE THREAD

**Issue by DiazJJ** [fhoeben/hsac-fitnesse-fixtures#252]
I did download the hsac-fitnesse-fixtures and follow the steps in the installation and after that I did try some exmple of BrowserTest https://github.com/fhoeben/hsac-fitnesse-fixtures/wiki/3.-BrowserTest-Examples
but when I run it always get an exception ----> nl.hsac.fitnesse.fixture.slim.StopTestException: Cannot use Selenium before configuring how to start a driver (for instance using SeleniumDriverSetup) ----> anyone can help ?? Thank so much

**Comment by fhoeben** [comment]
You need to create a SuiteSetUp page configuring selenium. Something like:
```
|script          |selenium driver setup                    |
|start driver for|chrome       |
```

Did you download/unzip the 'standalone' version, or use the [sample project](https://github.com/fhoeben/sample-fitnesse-project)? 

When you use either of those and start the wiki you get some working examples in http://localhost:9090/HsacExamples.SlimTests.BrowserTests
(Port number can be different, of course, depending on how you started)

**Comment by DiazJJ** [comment]
yes sir I did download/unzip the standalone version and when I test the Slimtest BrowserTests Examples it always get the exception ----> nl.hsac.fitnesse.fixture.slim.StopTestException: Cannot use Selenium before configuring how to start a driver (for instance using SeleniumDriverSetup)

**Comment by DiazJJ** [comment]
<a href="https://cl.ly/aede2c6290cb" target="_blank"><img src="https://d2ddoduugvun08.cloudfront.net/items/0b2X1x2R3V473V3V1Q1R/%5Baf7540ccb43ee22f6e665db52b320e78%5D_Image%25202019-02-27%2520at%25201.34.42%2520PM.png" style="display: block;height: auto;width: 100%;"/></a>

**Comment by fhoeben** [comment]
You added the page at the level where no browser is started, that is done in the suite set up at the HsacExamples.SlimTests.BrowserTests level, your page is HsacExamples.SoapTest.TestBrowser. Try opening http://localhost:2222/HsacExamples.SlimTests.BrowserTests.ScriptTest and see whether that works.

On another note: the sample test you copied no longer works (as www.funda.nl has added robot detection preventing automated interaction).

**Comment by DiazJJ** [comment]
IT WORKED SIR! THANK YOU SO MUCH SIR!
