### ISSUE TITLE
iframe does not have id, what can I use to get the iframe ?

### ISSUE THREAD

**Issue by DiazJJ** [fhoeben/hsac-fitnesse-fixtures#257]

**Comment by fhoeben** [comment]
Can you provide the html. Any other technical selector is usable. For instance `xpath=//iframe`

**Comment by DiazJJ** [comment]
itried to use xpath but it didnt work
here is the element

**Comment by fhoeben** [comment]
You should be able to find it with an XPath. Have you tried some whether you can find the right selector in the developer tools of your browser.

If the xpath I suggested does not work I suspect there are multiple iframes on the page. You could try something like `xpath=(//iframe)[2]` to get the 2nd iframe (xpath indexes are 1 based, not 0 based)

**Comment by DiazJJ** [comment]
It is now solved sir, I just put wait command before the xpath command, Thank you
