### ISSUE TITLE
Possible to use stopTestIf without triggering error/exception/fail?

### ISSUE THREAD

**Issue by McLFaberge** [fhoeben/hsac-fitnesse-fixtures#258]
My current situation:
I'm trying to run a test in separate steps. Step2 only needs to start if Step1 fails. The second test elaborates on Step1, but takes a lot longer.

StopTestIf seems a great tool, but I can't seem to stop throwing an exception. Is there a workaround for this?

Edit: I wouldn't mind my test failing when StopTestIf were skipped.

**Comment by fhoeben** [comment]
StopTestIf is targeted to stop tests, that's why it throws an exception (the exception stops the test).

Are your steps on a single page? Or are they separate pages in a suite?

I don't quite understand what you mean by  'when StopTestIf were skipped'. Do you mean the test can fail if the test is NOT stopped?

**Comment by McLFaberge** [comment]
Thank you for your reply!

My tests are currently on a single page. I haven't worked out yet how to run tests from different pages (still learning). I'm still figuring out how to integrate some logic into my FitNesse tests (IF-THEN-ELSE type logic)

> I don't quite understand what you mean by 'when StopTestIf were skipped'. Do you mean the test can fail if the test is NOT stopped?

That's exactly right. But this bit was meant for if someone would have come up with a workaround that happened to throw a fail/exception for a test continuing.

**Comment by fhoeben** [comment]
In general FitNesse (and specifically Slim script tables) do not support if-then-else logic. The general idea behind this is (in my understanding) that a test should cover a single known case, a single execution, path through the system being tested. Therefore if-the-else is not desirable: there should be a specific test case for the 'if branch' and another for the 'else branch' if both should work. The situation being tested should be controlled and all relevant paths must always be covered.

Running multiple tests is quite easy: you first create a 'parent page' (a suite) and then add children to (below) this page. You can then run all child pages from the 'parent page' by clicking the 'Suite' button at the top of the page (on the same location where the 'Test' button is located on each individual child page. The child pages can still be run in isolation, by clicking Test on them, but by clicking Suite on the parent page all child test pages are run (one after the other).
