### ISSUE TITLE
version 4: "Bad table! The argument is not an output of the scenario." on scenario decision tables

### ISSUE THREAD

**Issue by Eddie1802** [fhoeben/hsac-fitnesse-fixtures#261]
I'm trying to upgrade from version 3 to 4 but I get a Bad table error on every scenario based decision table. 
![image](https://user-images.githubusercontent.com/2613395/57225495-d1020600-700c-11e9-87de-9c3081bc30c3.png)

The same can be seen here:
https://fhoeben.github.io/hsac-fitnesse-fixtures-test-results/examples-results/HsacExamples.SlimTests.BrowserTests.ScenarioTest.html
![image](https://user-images.githubusercontent.com/2613395/57225440-a6b04880-700c-11e9-9172-746461b3967f.png)

I see that the [table template version](https://fhoeben.github.io/hsac-fitnesse-fixtures-test-results/examples-results/HsacExamples.SlimTests.BrowserTests.TableTemplateTest) of this example test doesn't fail. But I'd rather not replace all my scenario's with table templates because we use a lot of scenario based decision tables.

This stopped me from upgrading to version 4 but since chrome 74 is not supported by the webdriver shipped with version 3 the need to upgrade is now here.

**Comment by fhoeben** [comment]
Should be fairly easy fix (sorry I didn't do the example). See https://github.com/unclebob/fitnesse/pull/1178

So the output parameter of the scenario should get a `?` directly after them in the scenario top row. (i.e.  `partyNo?` instead of `partyNo` in the definition of `add party via web service`)
