### ISSUE TITLE
Enter does not clear the current value of the field

### ISSUE THREAD

**Issue by saskiav** [fhoeben/hsac-fitnesse-fixtures#263]
Below a small output part of a test. I am trying to change the value of the field Achternaam, but I can't get it cleared.
```
|script | browser test|
|ensure | is visible | Achternaam|
|check | value of | id=aanvrager1.achternaam | Vriez|
|enter | Iets anders | as | id=aanvrager1.achternaam|
|check | value of | id=aanvrager1.achternaam | [VriezIets anders] expected [Iets anders]|
```
Can anyone explain why the enter command is not clearing the value of the field first?
I really have no clue.

**Comment by tcnh** [comment]
I'm guessing some javascript that is executed on focus of the input field is causing trouble

you could try clicking  `id=aanvrager1.achternaam` before you enter the new value. If that works,it's probably some async javascript you should wait for first.

**Comment by saskiav** [comment]
I tried the click on the field but that didn't have any effect.
What you said about the async js however could be the cause. They are using
a lot of javascript.
Is there any workaround for it??


Op vr 10 mei 2019 16:19 schreef Tom Heintzberger <notifications@github.com>:

**Comment by fhoeben** [comment]
Try placing the following scenario above your script (or in your ScenarioLibrary page):

```
|scenario|enter _ as _ |value, field|
|click|@{field}|
|select all|
|press|back_space|
|type|@{value}|

```

It empties the field by selecting its contents and sending a backspace keypress (instead of trying to use Selenium magic which sometimes fails with JavaScript) and then typing the value desired.

**Comment by saskiav** [comment]
Thanks!
Will try it out after the weekend. I will let you know if I'll get it work.

Op vr 10 mei 2019 17:39 schreef Fried Hoeben <notifications@github.com>:

**Comment by saskiav** [comment]
Yes! It works!
I've put a scenario in my Library, so we can use it from anywhere.
Thanks for helping me out!
