### ISSUE TITLE
repeateMaxCount should not be the max int

### ISSUE THREAD

**Issue by maartenjanvangool** [fhoeben/hsac-fitnesse-fixtures#267]
I made a test that checks on an endpoint whether or not something another service is doing is finished. In order to do this, I use the repeat until functionality in jsonhttp test. 

After 10 minutes of running my test, I kill the test, not knowing why it was taking so long (and not getting any feedback). After reviewing, I find that the repeatMaxCount = Integer.MAX_VALUE by default. I would say that this is a bad default; a test should not by default run endlessly, but always end at some point (maybe after a minute or two). Perhaps this default should be changed?

**Comment by fhoeben** [comment]
The default was chosen to do exactly what the method name states: repeat until some condition is met. The assumption is that one knows the condition will be true eventually and we are waiting for that.

Giving are more limited default might seem like a good idea but is fairly arbitrary: why should we wait for at most 2 minutes, and not 30 seconds or 10 minutes? What is ridiculously long for me might be normal for some else's test. 

The current setup intends to nudge the user to make the maximum explicit in the test script.

I would sooner favour making the fact that one SHOULD set a maximum more explicit in the documentation. What do you think about that?

**Comment by maartenjanvangool** [comment]
The fact that a limited default is arbitrary is by itself not an argument not to set one in my opinion. 

I agree a maximum should be set by the user, and that should be added to the documentation. But I do still think a test should not by default run endlessly (or at least all night) just because I forgot to set it and my service went down. 

I'll at least make a pull request to improve the documentation :-).

**Comment by fhoeben** [comment]
Thanks for the PR.

**Comment by fhoeben** [comment]
I do see your point that the current default max repeat is too high.
Lowering it does 'break' backwards compatibility, but a more sensible value seems acceptable.

What value would you suggest? I'm thinking along the lines of 36000, which would be an hour if each check takes 100ms.

**Comment by maartenjanvangool** [comment]
I understand the point of backward compatibility. An hour would be a lot better than what it is now, but I would assume dialing it down to like 15 minutes would still not break many tests. One should not have tests with a 15 minute delay in it anyway.

**Comment by fhoeben** [comment]
Should be addressed in 4.5.3
