### ISSUE TITLE
Bug: map of maps fixture, start with equal values result in overwrite

### ISSUE THREAD

**Issue by teunisv** [fhoeben/hsac-fitnesse-fixtures#270]
```
|table:map of maps fixture|false    |
|bug                      |1   |1   |
|code                     |NL  |EN  |
|dog                      |Hond|Dog |
|cat                      |Kat |Cat |
|                         |$nl=|$en=|

|script|string fixture                                  |
|check |value of|$nl|{bug=1, code=NL, dog=Hond, cat=Kat}|
|check |value of|$en|{bug=1, code=EN, dog=Dog, cat=Cat} |
```
i expect this to be green/oke; but values of $nl are same as $en
only happens if first one has the same values

**Comment by fhoeben** [comment]
I understand that this might seem surprising, but this is indeed how it works.
The fixture creates a single map, containing other maps. In that single map each nested map has a key. That key is the value in the first row.
By giving the same values in the first row, the third column effectively overwrites the second.
To prevent this: ensure the values is the first (or actually second) row are unique per column.

This could probably be avoided by generating a unique key for each map, but that would render the whole (single) map of map less usable, as the key for each map is no longer the (user chosen) value in the first row but a generated one.

Is it really that hard, or undesirable, to ensure the first row's values a unique values?

**Comment by teunisv** [comment]
No just really unexpected; (the first define got same values after a change, and suddenly rest too)

A hint in HsacExamples.SlimTests.UtilityFixtures.GeneratedSymbolicLinkSuite.SuiteGenerator
would maby be usefull for other user that run into same ~~bug~~/feature

**Comment by fhoeben** [comment]
Good point. Could do a little write up and make a PR? Thanks

**Comment by fhoeben** [comment]
There is a 'workaround' for this behaviour: if you don't put any content in the first column of the 2nd row (i.e. where 'bug' currently is in your example) the first row the rest of the row will NOT be placed in the resulting maps, but *only* be used as identifier of that column's map.

I understand it is not a real workaround, but might make the behaviour easier to understand, and make it clearer that no row containing key/values should be added above that row.

So to update your example:
```
|table:map of maps fixture|false   |
|     |nl-value           |en-value|
|bug  |1                  |1       |
|code |NL                 |EN      |
|dog  |Hond               |Dog     |
|cat  |Kat                |Cat     |
|     |$nl=               |$en=    |
```

**Comment by teunisv** [comment]
perefct example. for me its 'fixed'
