### ISSUE TITLE
firefox v 60 on UNIX crashes on exit after downloading files

### ISSUE THREAD

**Issue by violinner** [fhoeben/hsac-fitnesse-fixtures#272]
On UNIX RedHat EL7.5, in a docker container, Firefox version 60.1 crashes on exit when it has encountered a test that downloads a file from a dynamic web application.  This will leave a core file and throw an exception on "|stop driver|" (which is a disappointment on some really long automated tests).

I can mask the crash by wrapping SeleniumDriverSetup().stopDriver() in a try-catch block, but the test suite is not able to start Firefox again after stopping it, for instance, to log in as a different user.

Are there any suggestions to getting rid of this crash on exit problem?   Perhaps by substituting getWindowHandles() & closing all the windows, not calling webDriver.quit() in SeleniumHelper?

**Comment by fhoeben** [comment]
Do you have a small test to reproduce this? Does the problem also occur with other (newer) versions of Firefox, I believe 68 is the latest?

I expect this to be a bug in geckodriver. Please also report it at https://github.com/mozilla/geckodriver. Have you found other error reports describing the same problem?

**Comment by violinner** [comment]
Increasing /dev/swp space seems to fix the problem:  shared memory is exhausted.
