### ISSUE TITLE
selectFor() fails unexpectedly when an <option> contains multiple text nodes

### ISSUE THREAD

**Issue by JessefSpecialisterren** [fhoeben/hsac-fitnesse-fixtures#273]
Today I ran into an edge case where |select|_value_|for|_input_| gave a timeout even though the \<select> in question had an \<option> containing the exact right text. After some debugging, it turned out the \<option> contained three text nodes, and the text to be matched was in the second one. The xpaths that OptionBy generates only examine the first text node of any \<option>, which explains why this particular option wasn't found.

This could be fixed by using the strategy outlined in [https://stackoverflow.com/a/3655588](https://stackoverflow.com/a/3655588). I verified this by testing the generated xpath manually, then modifying it according to that strategy and testing again. `//option[contains(normalize-space(translate(text(), ' ', ' ')), 'Option text')]` did not find anything, but `//option[text()[contains(normalize-space(translate(., ' ', ' ')), 'Option text')]]` found the \<option> as expected. Note that this strategy would still not cover cases where the value to be matched is split out over multiple text nodes, though I have yet to see that happening in an \<option> in the wild.

As for how an \<option> with this property came into being in the first place: the application I am testing uses Ember.js to generate its UI. I suspect that this edge case requires some JavaScript trickery to appear.

**Comment by fhoeben** [comment]
Thanks for pointing this out.
Your analysis makes sense, I believe most xPaths in the project already use this strategy to check text.

I did not realise it was not used for `option`, but then again I did not realise the `option` was allowed to contain anything but a single text element.

**Comment by fhoeben** [comment]
Can you provide a HTML page to reproduce the problem? I just updated one of the acceptance tests, expecting to reproduce it. But it came back green...

I created test
```
!define HTML { {{{
<!DOCTYPE html>
<html>
<body>
<label for="s3">Complex options to choose</label>
<select id="s3">
    <option value="1">a mail to <span>example1@example.com</span> is the <span>first</span> option</option>
    <option value="2" selected>example2@example.com</option>
    <option value="3">example3@example.com</option>
    <option value="4">example4@example.com <span>is another</span> to choose</option>
</select>
</body>
</html>}}} }

|script      |mock xml server setup|
|add response|${HTML}              |
|$url=       |get mock server url  |

|script                |browser test                                                                                             |
|open                  |$url                                                                                                     |
|seconds before timeout|1                                                                                                        |
|select                |example4@example.com    |for                      |Complex options to choose                             |
|check                 |value of                |Complex options to choose|!-example4@example.com-! is another to choose         |
|select                |first                   |for                      |Complex options to choose                             |
|check                 |value of                |Complex options to choose|a mail to !-example1@example.com-! is the first option|
|select                |to choose               |for                      |Complex options to choose                             |
|check                 |value of                |Complex options to choose|!-example4@example.com-! is another to choose         |


|script|mock xml server setup|
|stop                        |


```

**Comment by fhoeben** [comment]
Even using the option text split across multiple nodes worked for me:
```
|select                |a mail to !-example1@example.com-! is the first option|for                      |Complex options to choose                             |
|check                 |value of                                              |Complex options to choose|a mail to !-example1@example.com-! is the first option|
```

**Comment by fhoeben** [comment]
I tested using chrome, which browser did you use?

**Comment by fhoeben** [comment]
According to https://developer.mozilla.org/en-US/docs/Web/HTML/Element/option an option is not technically allowed to contain anything but text (which may include escaped characters).

> Permitted content | Text, possibly with escaped characters (like `&eacute;`).

**Comment by JessefSpecialisterren** [comment]
A quick examination of your test case proved that, at least in Firefox, all the \<option>s still only contain a single text node:

![image](https://user-images.githubusercontent.com/36038882/61286122-82b67380-a7c2-11e9-9999-36ebf4444915.png)

I'll play around with JavaScript for a bit to see if I can reproduce the issue that way.

**Comment by JessefSpecialisterren** [comment]
Here's a version that reproduces the issue both in Firefox and in Chrome:

```!define HTML { {{{
<!DOCTYPE html>
<html>
<body>
<label for="s3">Multiple text nodes in an option</label>
<select id="s3">
    <option value="1"></option>
</select>
<script type="text/javascript">
    var whitespace = document.createTextNode(' ');
    var optionText = document.createTextNode('Option text');
    var option = document.querySelector('#s3 option');
    option.appendChild(whitespace);
    option.appendChild(optionText);
</script>
</body>
</html>}}} }

|script      |mock xml server setup|
|add response|${HTML}              |
|$url=       |get mock server url  |

|script                |browser test                                    |
|open                  |$url                                            |
|seconds before timeout|1                                               |
|select                |Option text|for|Multiple text nodes in an option|


|script|mock xml server setup|
|stop                        |```

**Comment by fhoeben** [comment]
JavaScript magic indeed.
Thanks for the test. I have a vacation coming up, but I'll see whether this can be addressed in a release before that.
