### ISSUE TITLE
BrowserTest: Input values (username & password) in Authentication Popup

### ISSUE THREAD

**Issue by mvfsp14** [fhoeben/hsac-fitnesse-fixtures#277]
Do we have a BrowserTest command to handle inputting values (username and password) in an authentication pop up like the image below? 

![image](https://user-images.githubusercontent.com/54445608/63746142-a64afe80-c8d6-11e9-89b6-21400bde5e09.png)

On our project, one of our web portals implemented this authentication popup. We cannot use this command: 
`|open|<username>:<password>@<URL>| `

Due to URL are changing everytime a user access it and it contains [SAML](https://en.wikipedia.org/wiki/Security_Assertion_Markup_Language)

Here's a sample: 
`https:<username>:<password>@<URL>/SAMLRequest=<UNIQUE CODE/ID>`

We cannot also use "|enter|value|as|input|" as authentication popup don't have locators/element (xpath / id).

**Comment by fhoeben** [comment]
I haven't faced this login approach in my tests before (I always had html pages to do the login as that can be styled and offer links for forgotten passwords and such).

I don't know whether you can enter passwords in an authentication pop-up using Selenium. That probably requires some special code (a PR would be welcome).

Maybe the `open` command might be usable, if you get the URL with unique code first. Maybe by using something like:
```
|script|browser test|
|open|<normal url>|
|$url=|location|
|push fixture|
|start|string fixture|
|$updatedUrl=|replace all|!-https://(.+)-!|in|$url|with|!-https://<username>:<password>@$1-!|
|pop fixture|
|open|$updatedUrl|
...
```

Or maybe xml or json http test can be used to complete the login and then capture a cookie, or whatever is created, and transfer this to the browser.

**Comment by danielkroon** [comment]
@mvfsp14 so did you found a solution to overcome this scenario? I'm facing sort of the same issue.

**Comment by sudo-md** [comment]
@fhoeben I like your solution, with the changing URL's it should work with the active session. 

@mvfsp14 have you tried to use the full URL every time?

**Comment by mvfsp14** [comment]
Hi @fhoeben - apologies for late feedback but your approach/solution worked smoothly. Thank you. 

We can now close this ticket.
