### ISSUE TITLE
JSON HTTP Test: the test is failed if response status code == 4xx/5xx, despite none asserts are made in test

### ISSUE THREAD

**Issue by n-verbitsky** [fhoeben/hsac-fitnesse-fixtures#278]
The Fitnesse test is failed if the response code equals to 4xx or 5xx. Like this:

![image](https://user-images.githubusercontent.com/46368838/64179011-16272f00-ce6b-11e9-91fe-f67c6bc9feb2.png)

This may be inconvenient if we're writing negative tests where we are actually expecting 4xx or 5xx status codes. Like this:

![image](https://user-images.githubusercontent.com/46368838/64179128-4c64ae80-ce6b-11e9-90c6-f726194e3ad0.png)

**Comment by MelvinKlh** [comment]
I think you can use `reject` before the `get from`, as also mentioned in https://github.com/fhoeben/hsac-fitnesse-fixtures/issues/19

**Comment by n-verbitsky** [comment]
@MelvinKlh, that works, thanks a lot!
Closing issues, as seemingly my question is duplicate of [#19 ](https://github.com/fhoeben/hsac-fitnesse-fixtures/issues/19)
