### ISSUE TITLE
Fails to connect to android driver at GRID from versions above 4.5.5 

### ISSUE THREAD

**Issue by Taxanas** [fhoeben/hsac-fitnesse-fixtures#284]
Hello, Fried Hoeben,

I'm huge fan of your work, which makes lots of lives much easier (including mine :))

There's an issue with connectivity between hsac-fitnesse-fixtures and GRID with versions above 4.5.5, starting from this commit:

> https://github.com/fhoeben/hsac-fitnesse-fixtures/commit/8386eaed763950104b9387ea93a77a0f2aa6ae43

Im using hsac-fitnesse-appium method connectToAndroidDriverAtWithCapabilities:

In the end it requests for:

> {
  "desiredCapabilities": {
    "unhandledPromptBehavior": "ignore",
    "platformName": "Android",
    "unexpectedAlertBehaviour": "ignore"
  },
  "capabilities": {
    "alwaysMatch": {
      "platformName": "android",
      "unexpectedAlertBehaviour": "ignore",
      "unhandledPromptBehavior": "ignore"
    },
    "firstMatch": [
      {
      }

As i understand, "unexpectedAlertBehaviour" and "unhandledPromptBehavior" are not standard w3c caps and are not recognized by GRID (by versions above 2.53.3) and by appium.

4.5.5 version was requesting for:
> {
  "desiredCapabilities": {
    "platformName": "Android"
  },
  "capabilities": {
    "alwaysMatch": {
      "platformName": "android"
    },
    "firstMatch": [
      {
      }
    ]
  }
}

Any help or suggestion of workaround would be appreciated.

**Comment by fhoeben** [comment]
I changed the unexepected  alert behavior because chrome's defaults changed.
I use this all the time with Selenium grid (3.141.59), without problem for chrome desktop.

I could image the setting is a problem for Appium, but for a normal grid I expect it to work. Are you experiencing trouble there also?

I have to admit I haven't looked at Appium for a while. Any chance you can create a PR to fix this for Appium (there is an acceptance test for desktop chrome handling of alerts, that should remain green ;-))?

**Comment by Taxanas** [comment]
Thanks for fast response,

You are right, the problem with GRID only appears when using connectToAndroidDriverAtWithCapabilities method. 
While using connectToDriverAtWithCapabilities retrieves session without issues for same capabilities provided.
connectToDriverAtWithCapabilities json:
> {
  "desiredCapabilities": {
    "app": "*.apk",
    "appActivity": "*Activity",
    "appPackage": "*debug",
    "unhandledPromptBehavior": "ignore",
    "platformName": "Android",
    "deviceName": "ENU7N16109005056",
    "resetKeyboard": true,
    "unexpectedAlertBehaviour": "ignore"
  },
  "capabilities": {
    "firstMatch": [
      {
        "platformName": "android",
        "unhandledPromptBehavior": "ignore"
      }
    ]
  }
}
connectToAndroidDriverAtWithCapabilities:
> {
  "desiredCapabilities": {
    "app": "C:\\mobile\\OnTrack-kotlin\\app\\build\\outputs\\apk\\prep\\app-prep.apk",
    "appActivity": "apk.drivers.LoginActivity",
    "appPackage": "apk.drivers.debug",
    "unhandledPromptBehavior": "ignore",
    "platformName": "Android",
    "deviceName": "ENU7N16109005056",
    "resetKeyboard": true,
    "unexpectedAlertBehaviour": "ignore"
  },
  "capabilities": {
    "alwaysMatch": {
      "appium:app": "*.apk",
      "appium:appActivity": "*Activity",
      "appium:appPackage": "*debug",
      "appium:deviceName": "ENU7N16109005056",
      "platformName": "android",
      "appium:resetKeyboard": true,
      "unexpectedAlertBehaviour": "ignore",
      "unhandledPromptBehavior": "ignore"
    },
    "firstMatch": [
      {
      }
    ]
  }
}
Tried debugging how these jsons are build, but due to my juniority, it seems I would need a month of investigation to get familiar with it before making a quality PR :)

Maybe you could give an advice where to focus on, to have json from connectToDriverAtWithCapabilities but still be able to use juicy mobile utils from your appium project?

Thanks again,

**Comment by fhoeben** [comment]
You are quick to supply a PR after first claiming to be too junior ;-)

Given the method you refer to I assume you are using 'hsac-fitnesse-appium' or integrating Android in some other way?

That project was still using a quite old version of Selenium/Appium. Would it make a difference if the dependencies were updated there? I just pushed a change there to upgrade to latest dependencies see https://oss.sonatype.org/content/repositories/snapshots/nl/hsac/hsac-fitnesse-appium/0.0.12-SNAPSHOT/
My appium test environment no longer seems to work. Are you in a position to verify whether 0.0.12 still works? If so I'll release it.

**Comment by fhoeben** [comment]
I did some googling and https://stackoverflow.com/questions/47410707/invalid-capabilities-in-alwaysmatch-unhandledpromptbehavior-is-type-boolean-ins#answer-48113333 suggests that W3C should support values "accept", "dismiss" (although I see all values in https://www.w3.org/TR/webdriver/#dfn-known-prompt-handling-approaches-table).

Did you try explicitly setting the value to either of those in the capabilities you supply (which should prevent the default value of 'ignore' from being set in DriverFactory)?
