### ISSUE TITLE
Additional Utils for fixtures

### ISSUE THREAD

**Issue by Taxanas** [fhoeben/hsac-fitnesse-fixtures#287]
Hello, Fried Hoeben,

Im thinking about adding new converters to utils StringFixture or as separate. Examples:
Decimal-> Hex; Hex-> Decimal; bytes->Hex; Hex->bytes;

Additionally, adding some TCP, UDP, (MQTT?) clients.

What do you think about such fixtures? Would you see any value or it is not so general usage and would only create difficulties in maintenance?

Or maybe you already know someone working on such fixtures for fitnesse?

Thank you,

**Comment by fhoeben** [comment]
Hi Taxanas,
Thanks for suggesting such features. I can image such (utility fixtures) being quite helpful in some cases.
I'm not quite sure how generally useful they would be. I find most users are running tests at the end-user and http service level and not at the lower technical levels. I personally never had a need for them so it will be hard for me to judge their quality.

So maybe you can create such fixtures in a separate project the you yourself, and others, can install on top of the fixtures in this project?
If there are only a couple of classes and no additional dependencies we could incorporate them into this project. But like I said: I don't feel very confident maintaining them.
