### ISSUE TITLE
FitNesse failure navigator doesn't work anymore

### ISSUE THREAD

**Issue by Gertray13** [fhoeben/hsac-fitnesse-fixtures#290]
Since the latest upgrade to version 4.8.0 I am unable to get the failure navigator to work. It shows the failures correctly, but running suites with a lot of tests doesn't autoscroll to the next / previous issue anymore:

![image](https://user-images.githubusercontent.com/58523899/70160452-ce5ab280-16ba-11ea-80a3-6c988d26ae33.png)

I think it's related to the latest inclusion of the `toolchain-fitnesse-plugin`, but I'm not 100% sure. Let me know if it's required to create an issue on that project.

**Comment by tcnh** [comment]
I suspect this is a bootstrap-plus issue. I'll have a look tomorrow!

**Comment by tcnh** [comment]
This was indeed a javascript issue with bootstrap-plus.
It is fixed in bootstrap-plus 2.0.3 and incorporated in toolchain-plugin version 1.18

See: https://github.com/praegus/toolchain-fitnesse-plugin/releases/tag/toolchain-fitnesse-plugin-1.18 and https://github.com/praegus/fitnesse-bootstrap-plus-theme/releases/tag/fitnesse-bootstrap-plus-theme-2.0.3

**Comment by Gertray13** [comment]
Thanks a lot, it is indeed fixed with the new version!

**Comment by tcnh** [comment]
This issue reappeared in bootstrap-plus. It has our attention but may take a couple of days to fix in a more robust way.

**Comment by tcnh** [comment]
This should no longer occur when aupgrading to https://github.com/praegus/toolchain-fitnesse-plugin/releases/tag/toolchain-fitnesse-plugin-2.0.0 (containing https://github.com/praegus/fitnesse-bootstrap-plus-theme/releases/tag/fitnesse-bootstrap-plus-theme-2.0.5 that has the failure navigator somewhat redone)

**Comment by Gertray13** [comment]
@tcnh, thank you for your update!
