### ISSUE TITLE
PollingTests support for scenarios/tables of http calls

### ISSUE THREAD

**Issue by Taxanas** [fhoeben/hsac-fitnesse-fixtures#291]
Hello, Fried Hoeben,

I was wondering whether there are any future plans to make repeated scenarios/tables of http calls until condition is met, not just for repeating last http call. In many cases that would help to reduce wiki code and make it clean and shiny :)

Thank you,
Sincerely, Julius

**Comment by fhoeben** [comment]
No plans yet.
In general I aim for tests where I know how often/when to do something. So both an 'if' and 'for' option for scenarios, which have been asked before, I never pursued.

Ik you need something the best I can come up right now is to define the repeating step as a new method in a custom fixture (subclass).

But if you see a way to add a generic repeat/until for scenarios, either in this project or in FitNesse itself, please make a PR.

**Comment by Taxanas** [comment]
Closing this request, as Praegus toolchain fixtures are quite helpful in this case :)
