### ISSUE TITLE
test report has broken links to screenshots of failures

### ISSUE THREAD

**Issue by pvreeuwijk** [fhoeben/hsac-fitnesse-fixtures#294]
As per version 4.9.1 our test reports do not show failures correctly. the screenshots are not shown anymore.
Inspecting the html source show invalid code: "<div>  ....   <div"

The quotes need to be removed and the closing div needs an > 

"&lt;div&gt;&lt;div&gt;Timed-out waiting (after 10s).&lt;/div&gt;&lt;div&gt;&lt;a href="files/pagesources/org.openqa.selenium.TimeoutException_62.html" target="_blank"&gt;Page content&lt;/a&gt;:&lt;a href="files/screenshots/timeouts/BrowserTest/timeout_62.png" target="_blank"&gt;&lt;img src="files/screenshots/timeouts/BrowserTest/timeout_62.png" title="D:\jenkins\.jenkins\workspace\tly_integration_test_master-GL3LN7WPXVLOXGAZQQ27C4ZSFOC62BVT6LIEBNZJVCPNJCNH2ZGQ\target\fitnesse-results\files\screenshots\timeouts\BrowserTest\timeout_62.png" height="200"/&gt;&lt;/a&gt;&lt;/div&gt;&lt;/div"

**Comment by fhoeben** [comment]
What was the last version you did see this work (I can't imagine the change from 4.9.0 to 4.9.1 causing this)?

**Comment by fhoeben** [comment]
Did you also upgrade to FitNesse 20191229 (from 20191217)? 
4.9.1 was released with 20191217, and seems to do the screenshots correctly for me. When I upgrade to 20191217 the problem appears.

So, for now, my assumption is this is a FitNesse issue introduced in the latest release there.

**Comment by pvreeuwijk** [comment]
We changed from 4.8.2 to 4.9.1.
Fitnesse version was upgraded from 10190628  to 20191229

Thanks for analysing the issue, we'll monitor #1252 on fitnesse

**Comment by fhoeben** [comment]
No problem, hope to address it quickly. (As you gathered there is an easy workaround for now: downgrade FitNesse)

**Comment by fhoeben** [comment]
FitNesse 20200108 does give proper reports
