### ISSUE TITLE
Additional methods for httptest

### ISSUE THREAD

**Issue by Taxanas** [fhoeben/hsac-fitnesse-fixtures#297]
Hello,

I think it would be very useful to expand method: `repeat until response is` to `repeat until response is (not)` 
Or add separate methods like `repeat until response is not`, `repeat until response contains`

Example usage would be calling endpoints, which return `[]`, until they have a value to return.

Have your thought about it? :)

**Comment by fhoeben** [comment]
I have considered it, but have not needed it. Should be a simple change.
Can you make a PR?

**Comment by Taxanas** [comment]
Sure, im already testing it :)
