### ISSUE TITLE
Is there a fixture available to compare dates?

### ISSUE THREAD

**Issue by h-battjes** [fhoeben/hsac-fitnesse-fixtures#304]
I'd like to compare dates, is there a way to do this?
for example: check 10-02-2020 < 11-02-2020

**Comment by fhoeben** [comment]
DateFormatFixture can convert a string date in a specific format to a long, which you can then compare using standard Slim value compare

**Comment by h-battjes** [comment]
Ah thanks, I already assumed there was to way to do it
