### ISSUE TITLE
Checken welke na een hover zichtbaar worden.

### ISSUE THREAD

**Issue by RobVanGalen** [fhoeben/hsac-fitnesse-fixtures#31]
Het zou handig zijn als het mogelijk is teksten te controleren na middels een hover actie zichtbaar worden.

HTML voorbeeld:
```
<span class="ra_bh_hovertooltip " title=" <strong>Kosten verrekenen met financiering</strong><br> <div id="row_kostenmeefinancieren_tooltipDiv">Als de kosten worden meegefinancierd, wordt het advies niet los geïncasseerd.</div> ">
<span id="row_kostenmeefinancieren_tooltip" class="infotext">
<strong>Kosten verrekenen met financiering</strong>
<br>
<div id="row_kostenmeefinancieren_tooltipDiv">Als de kosten worden meegefinancierd, wordt het advies niet los geïncasseerd.</div>
</span>
</span>
```

**Comment by fhoeben** [comment]
Je HTML voorbeeld is niet echt leesbaar. Kan je het proberen tussen 3x ` (oftewel 3 backticks ervoor en erna) voor en na. Dan kan ik echt de HTML zien...

**Comment by fhoeben** [comment]
Ik heb het HTML voorbeeld wat leesbaarder gemaakt, maar ik denk dat er ook JavaScript of CSS bijhoort, om het zichtbaar (en onzichtbaar) worden te regelen. Heb je die ook voor me?
