### ISSUE TITLE
File fixture can't access file created outside files section

### ISSUE THREAD

**Issue by jtenkate** [fhoeben/hsac-fitnesse-fixtures#311]
Problem: when creating a file in a directory **outside** the wiki/FitnesseRoot/files folder, creating the file succeeds (as can be seen on file level) but further test actions using the created file fail.
**within files section**
```
|script |file fixture |
|dir1= |get directory                        |
|$file=|append     |FIRST LINE |to |testfile |
|$x=   |filename of|$file                |
```
**outside files section**
```
|script |file fixture |
|set directory |C:\                          |
|$file=|append     |FIRST LINE |to |testfile |
|$x=   |filename of|$file                |
```
Result of second part of the test:
```
|$x= Unable to find: C:\<a href="file:\C:\testfile" target="_blank">testfile<\a> | filename of | $file->[testfile]|
```

**Comment by tcnh** [comment]
This happens because append returns a link to the file, not the file path itself and getFullName doesn't handle html links.
 
FileFixture can access the file, if you provide the full path to the keyword. i.e:
`|$x=|filename of|C:\\testfile|` 

If you have the filename in a separate symbol, you could just use that:
```
|script       |file fixture            |
|$filename=   |value of   |testfile    |
|set directory|D:\                     |
|append       |FIRST LINE |to|$filename|
|$x=          |filename of|$filename   |
```

**Comment by jtenkate** [comment]
Thanks, that works for me. The file fixture examples could use an update for this imho.

Reason to go outside the files section is that the SUT uses files from a specific place (not being the wiki  files section)
