### ISSUE TITLE
Unable to switch away from closed tab if one open tab remains

### ISSUE THREAD

**Issue by JessefSpecialisterren** [fhoeben/hsac-fitnesse-fixtures#318]
When there are two open tabs, and the current tab is closed using JavaScript, calling `|switch to next tab|` will time out and leave you on the closed tab. I made an acceptance test that reproduces this issue:

```
This test ensures we can switch back to the first tab when a previously opened second tab is closed but still our current tab.

!define HTML { {{{
<html>
<body>
First tab
</body>
</html>}}} }

!define HTML2 { {{{
<html>
<body>
<a href="javascript:window.close()">Close</a>
</body>
</html>}}} }

|script      |mock xml server setup|
|add response|${HTML}              |
|add response|${HTML2}             |
|$url=       |get mock server url  |

|script|browser test         |
|open  |$url                 |
|open  |$url      |in new tab|
|click |Close                |
|wait  |1         |seconds   |
|switch to next tab          |
|ensure|is visible|First tab |

|script|mock xml server setup|
|stop                        |
```

I would expect HSAC to switch to the only open tab in this case. Same goes for `|switch to previous tab|`.

I made a workaround for this (it was causing unnecessary failures in one of our projects):

```Java
@Override
public boolean switchToNextTab() {
    List<String> tabs = getTabHandles();
    if (tabs.size() == 1 && getCurrentTabIndex(tabs) < 0) {
        // There is only one open tab, but it is not the current one. Switch to the only open tab
        goToTab(tabs, 0);
        return true;
    } else {
        return super.switchToNextTab();
    }
}

@Override
public boolean switchToPreviousTab() {
    List<String> tabs = getTabHandles();
    if (tabs.size() == 1 && getCurrentTabIndex(tabs) < 0) {
        // There is only one open tab, but it is not the current one. Switch to the only open tab
        goToTab(tabs, 0);
        return true;
    } else {
        return super.switchToPreviousTab();
    }
}
```

I'm sure a more generalized solution is possible, but it may prove interesting to preserve current behavior when the current tab is closed and there are two or more open tabs. Not preserving current behavior might break a test or two.

**Comment by tcnh** [comment]
Did you try calling `ensure only one tab`?

**Comment by JessefSpecialisterren** [comment]
> Did you try calling `ensure only one tab`?

Yes we did! However, in the project where we ran into this issue, the tab is closed by JavaScript when an AJAX request completes, which means that the timing is variable and unpredictable. Calling `ensure only one tab` would therefore sometimes close the tab before the request completed, making the test fail unnecessarily.

With the given workaround, `switch to next tab` always gives the correct result. I would also argue that one would expect `switch to next tab` to cause a switch to the remaining open tab if the current tab is closed. I mean, it does so when there are two open tabs left. This bug only surfaces when there is one open tab left.

**Comment by tcnh** [comment]
Ah, I see what you mean. 
I solved a similar issue in one of our projects using an extra method  `switchToTab(int index)` combined with `getCurrentTabIndex` without introducing extra logic in the switchToNext/Previous methods that may not be backwards compatible. (I don't like 'hidden' logic in tests :])And it reads nice and verbose..

The example test would then read:
```
|script          |browser test         |
|open            |$url                 |
|$applicationTab=|get current tab index|
|open            |$url      |in new tab|
|click           |Close                |
|wait            |1         |seconds   |
|switch to tab   |$applicationTab      |
|ensure          |is visible|First tab |
```

**Comment by JessefSpecialisterren** [comment]
@tcnh Fair enough, but that still requires an extra method. I would argue that it should be possible to reliably automate a test like this without having to extend BrowserTest. So whether it is by adding a new method or adapting an existing method, I would still like to see this fixed somehow 🙂

**Comment by tcnh** [comment]
@fhoeben what is your take on this? A PR is very litttle work for both approaches anyway

**Comment by fhoeben** [comment]
The fact that the behaviour is different whether there remains 1 tab open or multiple seems a big smell to me. 

So I'm in favour of having tab switching 'just work' irrespective of whether the current tab is closed. I believe that is what @JessefSpecialisterren  is suggesting.
