### ISSUE TITLE
Http stream testing

### ISSUE THREAD

**Issue by Taxanas** [fhoeben/hsac-fitnesse-fixtures#322]
Hello, @fhoeben 

I was wondering if there are any plans for http stream api testing fixtures creation in future?

Thank you,

**Comment by fhoeben** [comment]
Do you mean something like web sockets or Kafka?

No plans at the moment, but PRs are always welcomed...

**Comment by Taxanas** [comment]
> Do you mean something like web sockets or Kafka?
Actually i was thinking about event stream (SSE)

**Comment by Taxanas** [comment]
Created stream listener, which collects data and returns as json, but i see its lots of work to make it configurable from various angles, as it depends on internal implementations of streams.
Closing ticket
