### ISSUE TITLE
Finding out the exact request that HttpTest sends to the server

### ISSUE THREAD

**Issue by JessefSpecialisterren** [fhoeben/hsac-fitnesse-fixtures#326]
Today I tried debugging a request to a REST API that was giving an unexpected response when issued with HSAC's HttpTest. Being unable to reproduce the issue with other tools, I tried finding out the exact request that HSAC was sending to the server, specifically which headers were included. However, no matter what I try, I can't seem to get the exact request.

* HttpTest itself only seems to know the headers I have explicitly set, not the ones that are automatically added by Apache HttpClient.
* I tried running the test with FixtureDebugTest and stepping through the code, but Apache HttpClient's code is an incredible maze, and after an hour I still didn't have my answer.
* I tried enabling logging for Apache HttpClient using the instructions at http://hc.apache.org/httpcomponents-client-4.5.x/logging.html . Nothing appeared to happen, I got no extra console output whatsoever.
* The host enforces HTTPS, so it is not trivial to obtain the exact request through network sniffing.

By this time, I thought this might be worth a bug report. Am I missing something here? Access to full request headers/bodies would be incredibly useful for debugging.

**Comment by fhoeben** [comment]
I believe I found a way to provide the headers and will add a method `request headers` to the next release. (In the mean time you could try compiling from master branch, or the .jar or the generated docker images from the [pipeline run](https://gitlab.com/fhoeben/hsac-fitnesse-fixtures/-/pipelines/156394529) to troubleshoot the problem you are facing)

**Comment by JessefSpecialisterren** [comment]
Awesome! I gave the .jar from the pipeline run a whirl, and it seems to work fine! I even captured a test call to a different (HTTP) API with Wireshark and verified that the result of `request headers` matched the actual request. That was a very quick and effective response, I am grateful indeed!
