### ISSUE TITLE
Allow non-xml response bodies with xml http test?

### ISSUE THREAD

**Issue by JessefSpecialisterren** [fhoeben/hsac-fitnesse-fixtures#329]
Lately, the team I'm currently working in has been writing tests for an API that mostly gives xml responses, but some endpoints give plain text responses. The xml responses are naturally most easily processed with `xml http test`, but that fixture returns false on `get from` and related methods when there is a non-xml response body. That is a sensible default, but creates a cumbersome situation on mixed-response-type APIs.

For example, if we want to automate a flow that involves both xml and non-xml responses, we either have to `|show|` or `|reject|` certain calls to prevent unnecessary test failures, or switch fixtures. But switching fixtures loses all state, so we'd have to manually reinstate values, headers, cookies (which AFAIK is not possible without extending the relevant *HttpTest classes), content type and so on. Alternatively, we could use `http test` for the entire flow and do our checks using `xml fixture`, but we'd give up some of the convenient extra methods of `xml http test`.

We currently intend to solve this using the following subclass:
```Java
public class HybridXmlHttpTest extends XmlHttpTest {
    protected boolean acceptNonXmlResponses = false;

    public void acceptNonXmlResponsesInSubsequentRequests() {
        acceptNonXmlResponses = true;
    }

    public void rejectNonXmlResponsesInSubsequentRequests() {
        acceptNonXmlResponses = false;
    }

    @Override
    public boolean responseIsValid() {
        try {
            getResponse().validResponse();
        } catch (FitFailureException | NonValidResponseReceivedException e) {
            if (e instanceof FitFailureException
                    && e.getMessage().startsWith("Unable to check for SOAP fault")
                    && acceptNonXmlResponses
            ) {
                return true;
            }
            if (getThrowExceptionOnHttpRequestFailure()) {
                throw new SlimFixtureException(false, e.getMessage());
            } else {
                return false;
            }
        }
        return true;
    }
}
```
This allows us to explicitly switch between failing and not failing on non-xml response bodies. However, this will likely break if the implementation details of `(Xml)HttpTest` change. Our question is therefore: would you consider including a solution like this into HSAC?

**Comment by fhoeben** [comment]
Although I believe I understand your situation and approach I don't immediately see this as a generic solution I want to include in the fixtures.

To me it seems more logical to have test cases/suites that check the XML responses and others that check the plain text ones. 
Setting up headers, cookies, etc could be generic which would then move to a scenario library where it can be reused for both types of API responses.

Reusing state in fixtures often suggests a smell where test cases are too large. But if you really want to do that, and switch fixtures you can do it. You would employ `push fixture`, `start <fixture class>` and `pop fixture` which allows a fixtures instance (and its state) to be put aside and later recovered. I believe one can also store the current fixture instance in a slim symbol and restore that later, although I don't recall the syntax immediately.

**Comment by JessefSpecialisterren** [comment]
Fair points. The flow I was thinking about is more of an end-to-end test, where we would test using the API as one of the real users might. They would most likely use a single http client instance and perform a list of calls sequentially, maintaining state between calls.

> You would employ `push fixture`, `start <fixture class>` and `pop fixture`

I had thought of that, but AFAIK that would not help when switching between `xml http test` and `http test` and back. We'd still have to manually transfer state between those instances.

I would also like to point out that `json http test` has no qualms about accepting non-json response bodies, which is part of the reason why we were surprised by this complication.

**Comment by fhoeben** [comment]
Your point about `json http test` is quite valid. But then again I believe you would technically have no problem to use `xml http test` either, you would just have to `reject` the call (as you already indicated) where you expect a non-xml response and check response status in the wiki, which could of course be hidden in a `call non-xml-endpoint` scenario. Or does XmlHttpTest does not allow access to the non-XML response?

The end user using a http client is quite the advanced user ;-) For them having to reuse state is also not so nice, in tools like `curl` or SOAP-UI one typically prepares requests individually, right?

Anyway someone doing a sequence of calls and reusing state is probably best mimicked by using HttpTest and checking XML using XmlFixture, imho.

**Comment by JessefSpecialisterren** [comment]
I can see I'm not going to sway your opinion on this 🙂. Well, that is understandable; it's easy for us to ask you to add a feature, but you'll be the one maintaining it through time. No trouble accessing the non-XML response, by the way.

I'll take this back to the team and we'll see which solution fits best in our current situation. Thank you for you consideration!
