### ISSUE TITLE
Argument not used.. on purpose?

### ISSUE THREAD

**Issue by roydekleijn** [fhoeben/hsac-fitnesse-fixtures#332]
https://github.com/fhoeben/hsac-fitnesse-fixtures/blob/ce304570bb0cb55dd05a29b2ae048c800c3e9ff7/src/main/java/nl/hsac/fitnesse/fixture/slim/web/BrowserTest.java#L337

**Comment by fhoeben** [comment]
Indeed on purpose. It allows subclasses to change the behaviour based on whether the alert was accepted or dismissed. This class does not offer different behaviour.
