### ISSUE TITLE
Add support for chromium-based edgedriver

### ISSUE THREAD

**Issue by timovd** [fhoeben/hsac-fitnesse-fixtures#334]
When changing the version of selenium.edgedriver to a version that's based on chromium, the zipped file contains a folder with other stuff and it will not be able to install the driver. Add a fileMatchInside to only get the msedgedriver.exe from the zip.

e.g.
```
<url>https://msedgedriver.azureedge.net/${selenium.edgedriver.version}/edgedriver_mac64.zip</url>
<fileMatchInside>msedgedriver.exe</fileMatchInside>
```

optionally edge for Mac can be added as well;
```<driver>
<name>edgedriver</name>
<platform>mac</platform>
<bit>64</bit>
<version>${selenium.edgedriver.version}</version>
<url>https://msedgedriver.azureedge.net/${selenium.edgedriver.version}/edgedriver_mac64.zip</url>
<fileMatchInside>msedgedriver.exe</fileMatchInside>
</driver>```

**Comment by fhoeben** [comment]
Looks like you got it all figured out. Could you make a PR of this (skip mac Edge for now)?
