### ISSUE TITLE
Control Click fixture

### ISSUE THREAD

**Issue by KickinAlfa** [fhoeben/hsac-fitnesse-fixtures#338]
Hi,

Today we were doing an upgrade for our old chrome driver version to a newer one.
We discovered that when using the browser test fixtures the "control click" is no longer working.

Is this something that sounds familiar?

**Comment by tcnh** [comment]
Works here.. 
Can you provide a small reproduction script of what doesn't work? And the browser and driver version you're using?

**Comment by KickinAlfa** [comment]
It sounds really silly:

`|script       |browser test                                      |
|click        |id=1|
|control click|id=2                |

Basicly the first id gets deselected when clicking on the 2nd.
We are using chrome Versie 84.0.4147.89, the old driver we used was 2.35.528161)
We then upgraded to chromedriver 83.0.4103.39.

We are using a selenium node

**Comment by tcnh** [comment]
Tried with a multi select as well:
![image](https://user-images.githubusercontent.com/2232710/87781314-c2c69100-c830-11ea-8815-52e2a4d85b66.png)
If you use chrome 84, please also use chromedriver 84. Using a driver that is not in sync with your browser's version may produce unexpected results.
