### ISSUE TITLE
JsonHttpTest repeatUntil. . . only does exact matches

### ISSUE THREAD

**Issue by violinner** [fhoeben/hsac-fitnesse-fixtures#339]
It would be convenient to allow regex matches in repeatUntilJsonPathIs(2), i.e.:

   | repeat until json path | $.responses[0].hits.hits[0]._source.message | is | =~/.*Process has started.*/ |

- I have been unable to force this to use "...source[?(@.message contains 'Process has started')]"
- Using regex is probably clearer on the report.

**Comment by fhoeben** [comment]
Nice idea. I'm looking at supporting this...
