### ISSUE TITLE
Bug: RerunLastFailures on Parallel executions

### ISSUE THREAD

**Issue by teunisv** [fhoeben/hsac-fitnesse-fixtures#344]
Creates the file only for 1 of the Parallel executions, not all

**Comment by fhoeben** [comment]
It is intentionally created for all, as each run's failures should be able to re-run (especially when each run is run on its own on a different host or in a separate docker container). You can make it work on a single machine/container by specifying a different name for the output file (using `reRunSuiteLocation` system property).

Combining all failures from all runs in a single rerun is also possible by creating a 'suite' (aka directory) containing the generated rerun .wiki files, but in that case the files must have different names also.
