### ISSUE TITLE
xpath with no match in BrowserTest, but correct match in Developer Tools (Turns out: both match)

### ISSUE THREAD

**Issue by pvbemmelen62** [fhoeben/hsac-fitnesse-fixtures#357]
Problem: I have an xpath expression that doesn't match any element when evaluated by BrowserTest, yet in Developers Tools the xpath expression does match exactly the right element. (both with firefox browser, en chrome browser).

The Application Under Test, is a question form, with questions that depending on the question either allow to select a value for answer, or enter some text as answer. In essence the question form is like this:

    <div class="question">Are you doing okay today?</div>
    <select><option>Yes</option><option>No</option></select>
    <div class="vspace"></div>

    <div class="question">Will you work tomorrow?</div>
    <select><option>Yes</option><option>No</option></select>
    <div class="vspace"></div>

    <div class="question">Are you getting better at your work?</div>
    <input name="betterAtWork"/>
    <div class="vspace"></div>

    <div class="question">Did you fill out your weekform?</div>
    <select><option>Yes</option><option>No</option></select>
    <div class="vspace"></div>

I wrote a test script that has two scenario's:
    at question _ click _
    at question _ enter _
; they both search for the element that has the specified question text (first arg of scenario),
and then respectively, click on the first following element that contains the text of arg 2 of the scenario,
or enter the text (arg 2) in the first following input element.

It's possible in writing a test script like this, with many questions, that erroneously, you might write
    |at question|Are you doing okay today?          |enter|No          |
where it should be
    |at question|Are you doing okay today?          |click|No          |
If that happens, the script should NOT enter the value in the first input further down the form,
because that would not be the question intended; instead the execution of the instruction should fail.

**The xpath expression used in the scenario's, searches backward in document order from the element that is about
to get the click or enter, for the most recent question text, and verifies that that is the intended question text.**

    |scenario|at question _ click _                                                                    |question, value                                                                    |
    |click   |//*[contains(text(), '@{question}') and @class='question']//following::*[contains(text(),'@{value}') and preceding::*[@class='question'][1][contains(text(), '@{question}')]]|

    |scenario|at question _ enter _|question, value                                                                                                                                           |
    |enter   |@{value}             |as|xpath=//*[contains(text(), '@{question}') and @class='question']//following::input[preceding::*[@class='question'][1][contains(text(), '@{question}')]]|

    |script                                                                                                                                               |
    |open        |http://localhost:9090/PaulsFitnesse.TestCases.QuestionForm.xpathStuff.MyExternalPages.HtmlPages.question-form|
 
    |script                                                            |
    |at question|Are you doing okay today?          |click|No          |
    |at question|Will you work tomorrow?            |enter|Probably not|
    |at question|Are you getting better at your work|click|Yes         |
    |at question|Did you fill out your weekform?    |click|No          |

Problem: the xpath expression doesn't match any element when evaluated by BrowserTest, for any of the questions.
Yet in Developers Tools the xpath expression does match exactly the right element.

For example:
`//*[contains(text(), 'Are you doing okay today?') and @class='question']//following::*[contains(text(),'No') and preceding::*[@class='question'][1][contains(text(), 'Are you doing okay today?')]]`

Does anyone know why this is?
And what can be done about it?

**Comment by fhoeben** [comment]
Are you using `click` on the selects on purpose? I would expect you would use either `select as` or `select for` such elements (as you don't want to just click but you want to click on the select and then select the desired option).

The xPath you have is quite complex, I'm not immediately sure how to translate your click to a select. But I expect something like: 

|scenario|at question _ select _ | question, option |
|select|@{option}|as|xpath=//div[@class='question' and text()='@{question}']/following-sibling::*[1] |

|script                                                                                                                                               |
|open        |http://localhost:9090/PaulsFitnesse.TestCases.QuestionForm.xpathStuff.MyExternalPages.HtmlPages.question-form|
|at question|Are you doing okay today?          |select|No          |

Does the 'Will you work tomorrow?' work, or also not?

**Comment by pvbemmelen62** [comment]
I spotted a bug in my example script code:

    |scenario|at question _ click _                                                                    |question, value                                                                    |
    |click   |//*[contains(text(), '@{question}') and @class='question']//following::*[contains(text(),'@{value}') and preceding::*[@class='question'][1][contains(text(), '@{question}')]]|

**I forgot the "xpath=" part.**
Thus, the code should be:

    |scenario|at question _ click _                                                                    |question, value                                                                          |
    |click   |xpath=//*[contains(text(), '@{question}') and @class='question']//following::*[contains(text(),'@{value}') and preceding::*[@class='question'][1][contains(text(), '@{question}')]]|

And that bug also exists in the test script for the actual application that I'm testing.
Once I correct that bug, my test script for the actual application runs succesfully too!

In your comment, you point out that I use a click where a select would be more appropriate.
The actual application for most questions contains html code a bit like

      <div class="question">Are you doing okay today?</div>
      <input id="AreYouDoingOkayToday_0" type="radio" name="AreYouDoingOkayToday" value="AreYouDoingOkayToday.YES">
        <label for="AreYouDoingOkayToday_0">Ja</label><br>
      <input id="AreYouDoingOkayToday_1" type="radio" name="AreYouDoingOkayToday" value="AreYouDoingOkayToday.NO">
        <label for="AreYouDoingOkayToday_1">No</label><br>

So mostly a click is appropriate.

There are a few "select" questions too, and there the scenario that does "click" seems to do the right thing.
**Are there situations where a click would not "do the right thing" ?**

And I saw that you used only one '/' in    ..../following-sibling....
where I used two slashes in  ...//following...
I may have to check whether my code should use only one slash; it may have the same effect, but maybe one is more logical.

Thanks for your comment, Fried.

**Comment by pvbemmelen62** [comment]
I spotted a bug in my example script code:

    |scenario|at question _ click _                                                                    |question, value                                                                    |
    |click   |//*[contains(text(), '@{question}') and @class='question']//following::*[contains(text(),'@{value}') and preceding::*[@class='question'][1][contains(text(), '@{question}')]]|

**I forgot the "xpath=" part.**
Thus, the code should be:

    |scenario|at question _ click _                                                                    |question, value                                                                          |
    |click   |xpath=//*[contains(text(), '@{question}') and @class='question']//following::*[contains(text(),'@{value}') and preceding::*[@class='question'][1][contains(text(), '@{question}')]]|

And that bug also exists in the test script for the actual application that I'm testing.
Once I correct that bug, my test script for the actual application runs succesfully too!

In your comment, you point out that I use a click where a select would be more appropriate.
The actual application for most questions contains html code a bit like

      <div class="question">Are you doing okay today?</div>
      <input id="AreYouDoingOkayToday_0" type="radio" name="AreYouDoingOkayToday" value="AreYouDoingOkayToday.YES">
        <label for="AreYouDoingOkayToday_0">Ja</label><br>
      <input id="AreYouDoingOkayToday_1" type="radio" name="AreYouDoingOkayToday" value="AreYouDoingOkayToday.NO">
        <label for="AreYouDoingOkayToday_1">No</label><br>

So mostly a click is appropriate.

There are a few "select" questions too, and there the scenario that does "click" seems to do the right thing.
**Are there situations where a click would not "do the right thing" ?**

And I saw that you used only one '/' in    ..../following-sibling....
where I used two slashes in  ...//following...
I may have to check whether my code should use only one slash; it may have the same effect, but maybe one is more logical.

Thanks for your comment, Fried.

**Comment by fhoeben** [comment]
Click will probably do the right thing since the xpath you use targets the option that must be selected. I never intended it to be used that way, but I suppose it works. I try to keep away from xpath in my tests as much as possible (that's what's the heuristics are for).
HTML-wise I would having 'normal' labels to have the questions for selects and text input fields seems much more appropriate, and then you could have used the 'enter as' and 'select as' without the need for any xpath. Radio-buttons are always a bit trickier, but there a container for the question and its input/options seems to be a more logical choice, which would allow the usage of '|click|Ja|in|xpath=...|' which I would find nicer.
But I don't know whether you have any influence over the HTML...

Anyway if this pattern occurs often in your system under test it might be nice to make a custom subclass of BrowserTest, which encapsulates these xpaths in a custom heuristic allowing the wiki page to be nice and readable.

**Comment by pvbemmelen62** [comment]
I have no influence over the HTML ; it's complex also because it supports a number of different languages, most right-to-left (Arabic, and such).

Anyway, the application under test is not the application that I work on normally; for the latter we have made a subclass of BrowserTest, exactly as you suggest.

Thanks for your support.
