### ISSUE TITLE
flaky test found for the project

### ISSUE THREAD

**Issue by JoshSu** [fhoeben/hsac-fitnesse-fixtures#358]
I found some flaky tests in this project. 

This google docs contains detailed logic for how to fix the flaky test.

https://docs.google.com/document/d/1yfU0ca3xds04q1Q4XVBVuDsmbpbz3t3q8C68EBifx0Q/edit?usp=sharing

**Comment by JoshSu** [comment]
Can you please give me the permission for sending out pull request? Thanks

**Comment by fhoeben** [comment]
Thanks for taking the time to look at this project's tests and see whether you can improve them.  How did you determine which tests are 'flaky'?

Everyone can create pull requests from their own fork.

So you first have to fork the project (create a new branch), make the changes you want to, push those (to your own repo) and then when you come to this project you get the option to create a PR.
