### ISSUE TITLE
Test run is hanging due to 'Timed out receiving message from renderer: 10.000' from chromedriver

### ISSUE THREAD

**Issue by pvreeuwijk** [fhoeben/hsac-fitnesse-fixtures#363]
We upgraded to the latest hsac version, but still our run is blocked by a message from chromedriver: '[SEVERE]: Timed out receiving message from renderer'. 
I expected the script to stop executing after a certain maximal time period as a guard to this.

information
- headless run
- latest hsac version
- chrome 87.0.4280.88

logging information:
2020-12-08 03:14:17.000 test Started '-------' (106 / 445)
dec. 08, 2020 3:14:17 A.M. org.openqa.selenium.remote.DesiredCapabilities chrome
INFO: Using `new ChromeOptions()` is preferred to `DesiredCapabilities.chrome()`
Starting ChromeDriver 87.0.4280.88 (89e2380a3e36c3464b5dd1302349b1382549290d-refs/branch-heads/4280@{#1761}) on port 32320
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
dec. 08, 2020 3:14:19 A.M. org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
[1607393726.346][SEVERE]: Timed out receiving message from renderer: 10.000
[1607393726.347][SEVERE]: Timed out receiving message from renderer: 10.000

=> from here there's a spinner in Jenkins, and the run has to be terminated manuaaly from this point.

**Comment by fhoeben** [comment]
The `Timed out receiving message from renderer` is not something I can fix, that's a chromedriver/chrome issue (I have the impression I've seen it in the past when there was insufficient memory).

Quite a bit of work has been done in the past to ensure quicker termination of test runs when the environment fails. But in general there is no maximum amount of time a run may take (as this of course depends on the number of tests that need to be run). Maybe Jenkins offers such a feature, a maximum on the amount of time a build may take before it is automatically terminated?

I've never been able to determine how to detect this `Timed out receiving message from renderer` situation on the Java/Selenium code side. Do you have any suggestions (either on how to detect the issue, or prevent it)?

**Comment by tcnh** [comment]
Ususally this is not an error but a report of chromedriver looping  a wait. The SEVERE tag is quite misleading. It's strange that you test halts.. Do you see this on all webpages? Or could there be something blocking your sut from loading?
In the past, I've circumvented these log messages by setting the  pageLoadStrategy capability to eager or none.
Note that using 'none' may cause timing issues, as selenium will not even wait for the browser to parse the page (generally not the best idea when testing). Eager will parse, but not necessarily wait for all resources to be loaded.

**Comment by fhoeben** [comment]
Any news or can we close this request?

**Comment by pvreeuwijk** [comment]
-
