### ISSUE TITLE
Version 4.23.0 conatins Toolchain-plugin 2.0.10 which is nt compatible with FitNesse 20201213

### ISSUE THREAD

**Issue by tcnh** [fhoeben/hsac-fitnesse-fixtures#365]
Latest toolchain plugin (2.0.11) fixes this.
See https://github.com/fhoeben/hsac-fitnesse-fixtures/pull/364

**Comment by fhoeben** [comment]
4.23.1 will address this. It will be available in Maven Central shortly...
