### ISSUE TITLE
NullPointerException on macOs Catalina with security update 2020-001

### ISSUE THREAD

**Issue by reators** [fhoeben/hsac-fitnesse-fixtures#367]
After updating my MacBook running Catalina 10.15.7 with security update 2020-001 many UI-related tests crash at the end now:

Console log:
```
Test system terminated with exception [fitnesse.testsystems.TestExecutionException: java.lang.NullPointerException: Cannot invoke "javax.script.ScriptEngine.eval(String)" because "this.engine" is null]
```
The FitNesse UI shows something similar:
```
Could not complete testing: java.lang.NullPointerException: Cannot invoke "javax.script.ScriptEngine.eval(String)" because "this.engine" is null 
```
SW-Versions:
hsac-fixture: 4.23.1
fitnesse: 20201213

The error occured also with hsac 4.22.0 and fitnesse 20200501

**Comment by fhoeben** [comment]
Can you share which Java JVM you are using? I suspect you are running a version which does not include a JavaScript engine...

**Comment by tcnh** [comment]
99% sure this is Java 15. It has Nashorn removed.
Integrating https://github.com/openjdk/nashorn for Java 15 compatibility is on my backlog, but for now I'd recommend to stick with Java 11 as it's the latest LTS.

**Comment by reators** [comment]
Thanks for your answers.
@tcnh you were right: I use Java 15 ("OpenJDK 15.0.1" to be precise. I didn't install this explicitly. Could it be introduced by the security update?)

I have two other java versions installed on my machine:
```
    14.0.1, x86_64:	"OpenJDK 14.0.1"
    1.8.0_252, x86_64:	"AdoptOpenJDK 8"
```
I tried both and both of them don't show the reported error: UI tests run as smoothly as before 👍🏻 
So I think I'll stick with Java14 in the meantime until nashorn engine is integrated into FitNesse.

@fhoeben: Your question pointed into the right direction, right?

**Comment by fhoeben** [comment]
@reators I expected this indeed, but was not as confident as @tcnh, so I just asked a more open question ;-)

If you are running locally go with whatever version you have available, as long as it has a JavaScript engine included.
If you also run your tests on a CI server you might want to sync your local version with its version, just to be sure.

If you run your tests (in CI) using a docker (virtual machine) image I would recommend using Java 8 as it is the smallest JVM, keeping the image to be loaded as small as possible.

@tcnh if you plan to integrate a JavaScript engine it is probably best not to use Nashorn (which I believe is no longer supported by Oracle) but go with [Graal's JavaScript](https://www.graalvm.org/reference-manual/js/RunOnJDK/) instead (it can be used outside the Graal JVM). See also https://stackoverflow.com/questions/56788151/migrate-nashorn-to-graalvm
