### ISSUE TITLE
jdk11 : ScriptLanguageFixture.java:   package jdk.nashorn.internal.runtime does not exist

### ISSUE THREAD

**Issue by pvbemmelen62** [fhoeben/hsac-fitnesse-fixtures#370]
I want to debug the BrowserTest fixture, and I'm starting FixtureDebugTest for debugging; I'm using jdk-11.0.8 (openjdk);
I get a fatal error:

`G:\paul\git\hsac-fitnesse-fixtures\src\main\java\nl\hsac\fitnesse\fixture\slim\ScriptLanguageFixture.java:3:36
java: package jdk.nashorn.internal.runtime does not exist`

The problem is line 3 in ScriptLanguageFixture.java :
 
`import jdk.nashorn.internal.runtime.ECMAException;`

**How can I solve this error?**

The FixtureDebugTest.java file contents is probably irrelevant, but for "completeness" (it's under src/test) :

---------------------------------------------
package nl.hsac.fitnesse.sample_project;

import fitnesse.junit.FitNesseRunner;
import nl.hsac.fitnesse.junit.HsacFitNesseRunner;
import org.junit.runner.RunWith;

/**
 * Test class to allow fixture code to be debugged, or run by build server.
 */
@RunWith(HsacFitNesseRunner.class)
@FitNesseRunner.Suite("FitNesse.PaulsPlayground.OpenMyWebsiteTest")
public class FixtureDebugTest {
}
---------------------------------------------
When I run the test script  OpenMyWebsiteTest  via the Fitnesse wiki server, clicking Test,
the test runs fine. Because then it doesn't do any compiling, I guess.

**Comment by pvbemmelen62** [comment]
The FixtureDebugTest is in under the src/test  dir.

**Comment by fhoeben** [comment]
Given the error I expect that you are using another Java version when you run `FixtureDebugTest`, and not Java 11 like you believe. Nashorn is the JavaScript engine that was present in Java versions up to 15, but was [removed from Java 15](https://openjdk.java.net/jeps/372).

That package is present in a Java 11 JVM. 

I believe @tcnh is planning to create a PR for FitNesse (and probably `ScriptLanguageFixture`) to use an external JavaScript engine, I'm in favour of GraalVM's, so it can be used with Java versions 15 and higher. But for now stick to Java versions 8 or 11...

**Comment by pvbemmelen62** [comment]
To be sure I reinstalled the following jdk :

http://jdk.java.net/archive/
  11 GA (build 11+28)
  Windows         64-bit  zip (sha256) 179 MB

which links to
  https://download.java.net/java/ga/jdk11/openjdk-11_windows-x64_bin.zip

I installed it in
  C:/Program Files/Java/jdk-11.28
and updated my JAVA_HOME and PATH.

I deleted the old jdk that I had.

And restarted my computer, to make sure the environment settings are being picked up.

In IntelliJ  , where I do  FixtureDebugTest > Debug,  I changed the project structure settings to use the jdk-11.28 .

**The problem remains.**

I also renamed the 
  C:/Program Files/Java/jdk-11.28
to
  C:/Program Files/Java/jdk-11.28-hide
to check that that's really the jdk that's being used.
I then get errors messages that IntelliJ can't find jdk-11.28 .
That confirms that IntelliJ is really using jdk-11.28 .

In the cygwin command shell where I run the mvn command below, I checked that the correct javac is found:
$ which javac
/cygdrive/c/Program Files/Java/jdk-11.28/bin/javac
Paul@livingroom-pc /cygdrive/g/paul

When I run command
    mvn clean compile dependency:copy-dependencies exec:exec
I see warnings related to nashorn :

[INFO] --- maven-javadoc-plugin:3.1.1:javadoc (default) @ hsac-fitnesse-fixtures ---
[INFO]
Loading source files for package nl.hsac.fitnesse.fixture.fit...
Loading source files for package nl.hsac.fitnesse.fixture.leanapps...
Loading source files for package nl.hsac.fitnesse.fixture.slim...
Loading source files for package nl.hsac.fitnesse.fixture.slim.web...
Constructing Javadoc information...
1 warning
[WARNING] Javadoc Warnings
[WARNING] javadoc: warning - The old Doclet and Taglet APIs in the packages
[WARNING] com.sun.javadoc, com.sun.tools.doclets and their implementations
[WARNING] are planned to be removed in a future JDK release. These
[WARNING] components have been superseded by the new APIs in jdk.javadoc.doclet.
[WARNING] Users are strongly recommended to migrate to the new APIs.
[WARNING] G:\paul\git\hsac-fitnesse-fixtures\src\main\java\nl\hsac\fitnesse\fixture\slim\ScriptLanguageFixture.java:3: error: package jdk.nashorn.internal.runti
me is not visible
[WARNING] import jdk.nashorn.internal.runtime.ECMAException;
[WARNING] ^
[WARNING] (package jdk.nashorn.internal.runtime is declared in module jdk.scripting.nashorn, which does not export it to the unnamed module)
[INFO]
[INFO] --- maven-compiler-plugin:3.6.1:compile (default-compile) @ hsac-fitnesse-fixtures ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 191 source files to G:\paul\git\hsac-fitnesse-fixtures\wiki\fixtures
[WARNING] bootstrap class path not set in conjunction with -source 8
[WARNING] /G:/paul/git/hsac-fitnesse-fixtures/src/main/java/nl/hsac/fitnesse/fixture/util/MapHelper.java:[3,33] jdk.nashorn.api.scripting.ScriptObjectMirror in
jdk.nashorn.api.scripting has been deprecated and marked for removal
[WARNING] /G:/paul/git/hsac-fitnesse-fixtures/src/main/java/nl/hsac/fitnesse/fixture/Environment.java:[138,25] newInstance() in java.lang.Class has been depreca
ted
[WARNING] /G:/paul/git/hsac-fitnesse-fixtures/src/main/java/nl/hsac/fitnesse/fixture/util/MapHelper.java:[219,54] jdk.nashorn.api.scripting.ScriptObjectMirror i
n jdk.nashorn.api.scripting has been deprecated and marked for removal
[WARNING] /G:/paul/git/hsac-fitnesse-fixtures/src/main/java/nl/hsac/fitnesse/fixture/util/MapHelper.java:[220,13] jdk.nashorn.api.scripting.ScriptObjectMirror i
n jdk.nashorn.api.scripting has been deprecated and marked for removal
[WARNING] /G:/paul/git/hsac-fitnesse-fixtures/src/main/java/nl/hsac/fitnesse/fixture/util/MapHelper.java:[220,42] jdk.nashorn.api.scripting.ScriptObjectMirror i
n jdk.nashorn.api.scripting has been deprecated and marked for removal

**I'd like it to work with openjdk , rather than installing the java 8 from Oracle.
Do you have any suggestions that I could try ?**

**Comment by pvbemmelen62** [comment]
Below some further information that seems to suggest that jdk.nashorn.internal.runtime  is not available in jdk11.

I looked at
    src.zip\jdk.scripting.nashorn\module-info.java
in src.zip from the jdk11 that I have installed.

It contains a lot of javadoc, and the lines
-----------------------------------------------------------------------------------
@Deprecated(since="11", forRemoval=true)
module jdk.scripting.nashorn {
    requires java.logging;
    requires jdk.dynalink;

    requires transitive java.scripting;

    exports jdk.nashorn.api.scripting;
    exports jdk.nashorn.api.tree;

    exports jdk.nashorn.internal.runtime to
        jdk.scripting.nashorn.shell;
    exports jdk.nashorn.internal.objects to
        jdk.scripting.nashorn.shell;
    exports jdk.nashorn.tools to
        jdk.scripting.nashorn.shell;

    provides javax.script.ScriptEngineFactory with
        jdk.nashorn.api.scripting.NashornScriptEngineFactory;

    provides jdk.dynalink.linker.GuardingDynamicLinkerExporter with
        jdk.nashorn.api.linker.NashornLinkerExporter;
}
-----------------------------------------------------------------------------------
On webpage
    https://www.oracle.com/corporate/features/understanding-java-9-modules.html
it says

**exports and exports…to.** An exports module directive specifies one of the module’s packages whose public types (and their nested public and protected types) should be accessible to code in all other modules. An exports…to directive enables you to specify in a comma-separated list precisely which module’s or modules’ code can access the exported package—this is known as a qualified export. 
-----------------------------------------------------------------------------------
That seems to suggest that any class from jdk.nashorn.internal.runtime   is only available to jdk.scripting.nashorn.shell
and not to hsac classes.
So that would explain why
    import jdk.nashorn.internal.runtime.ECMAException;
in file ScriptLanguageFixture.java  gives error
    java: package jdk.nashorn.internal.runtime does not exist
and
    java: cannot find symbol
      symbol:   class ECMAException

Yet I know, that at my work, I was able to do FixtureDebugTest > Debug , and there I also have openjdk11 to the best of my knowledge.

**Can anyone share his/her thoughts on this?**

**Comment by fhoeben** [comment]
Some thoughts of mine:
- Java 8 is alive, just not by Oracle. For instance by  [Amazon](https://docs.aws.amazon.com/corretto/latest/corretto-8-ug/downloads-list.html), [AdoptOpenJDK](https://adoptopenjdk.net/?variant=openjdk8&jvmVariant=hotspot) or [Azul](https://www.azul.com/downloads/zulu-community/?version=java-8-lts&os=windows&package=jdk)

- Could it be that in the project you are having this problem you cloned the source repository of hsac-fitnesse-fixtures and added your own classes to play around with? That means you are compiling (not just running) these fixtures before you run you test. That could cause these problems. At your work you probably created a setup where you had these fixtures as a dependency, which should just work fine on Java 11. Try adding your tests (and fixtures) to a clone of https://github.com/fhoeben/sample-fitnesse-project and see whether that works better. That gives you the recommended setup where you only compile your own code (if any) before a run...

**Comment by tcnh** [comment]
I think it fails on the fixture-doc doclet that translates javadoc to json apidocs. Skip javadoc and see if that helps. Doclets are a sun construct that may not be present in openjdk.

**Comment by pvbemmelen62** [comment]
Problem solved!

I followed fhoeben's advice:

Yesterday I did
  git clone https://github.com/fhoeben/hsac-fitnesse-fixtures.git

15 minutes ago I did
    git clone https://github.com/fhoeben/sample-fitnesse-project.git

Now it works perfectly:  I can debug using FixtureDebugTest , and step into methods from fixture BrowserTest !

Thanks fhoeben and tcnh for your suggestions.
