### ISSUE TITLE
POST API responds with PDF contents

### ISSUE THREAD

**Issue by roydekleijn** [fhoeben/hsac-fitnesse-fixtures#377]
Hello,

One of my clients created an POST API that responds with an PDF document. 

I try to create the file with FileFixture.

| $response= | response |
| create | test.pdf | containing | $response |

Something is stored in test.pdf, but it looks like it's a 'cleaned' value. If we open the PDF, we see a blank document. 

Did. you notice such behaviour before? or what is the right wat to store the PDF (retrieved by an POST api call)?

Roy

**Comment by fhoeben** [comment]
I believe HttpTest currently always expects its responses to be text based (except when using `get file from`), and the `response` method will HTML escape that response. So send a HTTP POST and receive a binary response and then store that some new code is required. A PR is welcome...
