### ISSUE TITLE
Always on top + click issue

### ISSUE THREAD

**Issue by teunisnl** [fhoeben/hsac-fitnesse-fixtures#38]
tested in 2.5.2

As example:
`|script|browser test                                                                                      |
|open  |!-http://www.koffiediscounter.nl/product/1826157/nespresso-delonghi-lattissima-touch-en550s.html-!|
|click |xpath=.//*[@id='combination-products-container']/div/div[1]/div[2]/div[2]/a                       |`

I try to click on 2nd "Plaats in winkelmand" but the hover-content is preventing the click
(page timeout also shows this)
a scroll to + page_up can by pass this, but running into same error on input form where an element is selected, so page_up will directed toward the element instead of the page

**Comment by fhoeben** [comment]
You mean the 'cookie consent' popup is blocking? What I tend to do with these kind of boxes is just click once to accept it. When you use 'click if available' there is no error when the box is not displayed, but then you probably also want to configure a shorter 'seconds before timeout' to prevent having to wait 10 seconds if the box is not there. Scrolling can indeed also help if you don't want to click away the box.

I don't quite get what you mean by 'scroll to + page_up', or it being directed toward the element. That sounds like your using 'press' or something, but 'scroll to' is another command so ...?

**Comment by teunisnl** [comment]
The button im trying to press is under the red border item (Plaats in Winkelwagen for pakket 1)
![timeout](https://cloud.githubusercontent.com/assets/9052650/12759675/b14d7610-c9e2-11e5-87e7-c909910b9fc3.png)

the issue is item(in red border) overlays the item im trying to access
this next code bypasses the issue, but doesnt work if preceded by a |enter| which is case for an other site
`|script|browser test |
|open |!-http://www.koffiediscounter.nl/product/1826157/nespresso-delonghi-lattissima-touch-en550s.html-!| 
|scroll to|xpath=.//*[@id='combination-products-container']/div/div[1]/div[2]/div[2]/a |
|press|page_up|
|click |xpath=.//*[@id='combination-products-container']/div/div[1]/div[2]/div[2]/a |`

**Comment by fhoeben** [comment]
The problem with the floating element is real. So yes you will indeed have to scroll, or you have to find ways to work with the site's navigation to deal with this issue. So for instance for your example:

    |script   |browser test                                                                                  |
    |open     |http://www.koffiediscounter.nl/product/1826157/nespresso-delonghi-lattissima-touch-en550s.html|
    |scroll to|Uitgebreide omschrijving                                                                      |
    |click    |Plaats in winkelmand                                                                          |


or

    |script|browser test                                                                                  |
    |open  |http://www.koffiediscounter.nl/product/1826157/nespresso-delonghi-lattissima-touch-en550s.html|
    |click |Voordeelbundels                                                                               |
    |click |Plaats in winkelmand                                                                          |
    |check |value of                 |css=.total                |Totaal incl. BTW € 292,55                |

Of course, if this is really the site you're testing and you are part of the development effort I would recommend that you have some accessibility features added to the 'Plaats in winkelmand' links, so they also become usable by people accessing the site using a screen reader (which is very hard if there are multiple buttons/links on same page with same text but that do different things). So for instance you could have an aria-label='Plaats Pakket 1 in winkelmand' added to the link, and use `|click |Plaats Pakket 1 in winkelmand|' in your test.

I don't know what to tell you about the fact the floating element blocks a button. That's the way it is. Do you have a suggestion how the fixtures could address this?

**Comment by teunisnl** [comment]
Until i am sure i am allowed to share site it involves a different example same issue, but now the only link with the specified name
```
|script|browser test                                 |
|open  |!-http://tweakers.net/-!                     |
|note  |by pass cookie wall                          |
|click |Ja                                           |
|note  |next will time-out, link behind  menu bar    |
|click |Het bekijken waard                           |
|note  |this one does work weird enough|             |
|enter |p@p.com                        |as|name=email|
|note  |next will time-out, link behind  menu bar    |
|click |Nieuws van vandaag                           |
```
I guess its impossible to see if an other element is blocking the view ?
(bit weird that enter has no issue with the menu bar though)

The option to scroll to an element before the element that we wanna click on is a option, but
a solution inside the fixture it self would be more ideal. (working with site that has menu bar on every page so it gives alot of extra code just to bypass the fact its blocking the element i am trying to access)

To suggest a solution is gonna be tough, could suggest ability to scroll the the page, but due fact different width might require no scrolling so its not guaranteed to work.

**Comment by fhoeben** [comment]
I see no generic solution other than the scrolling made explicit in the wiki.

For a specific page you might be able to make a subclass that ensures it always scrolls to some pixels above (or below depending on how the floating element works) below the element you are trying to use.
