### ISSUE TITLE
Table Template to loop over values in an array

### ISSUE THREAD

**Issue by violinner** [fhoeben/hsac-fitnesse-fixtures#387]
Is it possible to use Table Template or scenario constructs to loop an action over values in an array?

I would like to click all the buttons with stem-matched ids on a web page using Browser Test.

Getting the ids in an array is easy, but I'm stumped on using them, as there will be different numbers of them on different days.

I'm guessing that one option is to overload
  |click | place |
to click everything in an array if an array is passed.

**Comment by fhoeben** [comment]
There is no way to perform a click on all items matching a 'place/selector'.

It is an explicit design choice in FitNesse not to support `if/then/else` or `loops` so no scenario (or table template) provides this functionality. The idea behind is that you want to perform checks in a controlled environment: the test should be explicit in how many elements are present and whether something exists.

Having said this: I believe it is quite easy to add a custom Java method to perform a click on each of a set, if you use your own BrowerTest subclass...
