### ISSUE TITLE
Screenshot of mouse-over

### ISSUE THREAD

**Issue by teunisnl** [fhoeben/hsac-fitnesse-fixtures#39]
I wanna make a screenshot while the mouseover action is happening (for instance to confirm the button color changed)

atm a hover-to and take screenshot will not achief this

**Comment by fhoeben** [comment]
And that does not work if you do something like?

`|hover over|button|

|show|take screenshot|hovering|`

**Comment by teunisnl** [comment]
i tried that it on it shows on browser its hovering over, but on screenshot
the button in question has the default layout

**Comment by fhoeben** [comment]
Strange. I believe that worked when I tried something like that. So also no joy when using 'storyboard' instead of 'script'?

Do you have a sample page I could see this behavior occur? Maybe I could find a solution, but maybe its some sort of Selenium limitation.
Which browser are you using?

**Comment by teunisnl** [comment]
hmm no issues when i try this on different machine, so ill have retest this again. ill update it on Thursday

**Comment by teunisnl** [comment]
When using storyboard it does show the hover over during the screenshot, but not during script.

Adding a 1 second wait before screens works, so in my eyes this can be considered fixed
