### ISSUE TITLE
How to collect a value from another Map and use into other Map?

### ISSUE THREAD

**Issue by marciojusto** [fhoeben/hsac-fitnesse-fixtures#394]
Sorry in advance to use this channel to ask this...

I have the map:

`|script   |map fixture                            |
|set value|!randomUuid        |for|username       |
|set value|${PASSWORD}        |for|password       |
|set value|!randomInt         |for|phoneNumber    |
|set value|${APPLICATION_NAME}|for|applicationName|
|set value|!randomUuid        |for|login          |
|$userMap=|copy map                               |`

and I'm trying to get the login and use it in another Map

`|script          |map fixture                            |
|set value       |true               |for|rememberMe     |
|set value       |${PASSWORD}        |for|password       |
|set value       |${APPLICATION_NAME}|for|applicationName|
|set value       |$userMap.login     |for|login          |
|$userMapCreated=|copy map                               |`

But, I only receive an HTML code with the entire first map

**Comment by fhoeben** [comment]
I believe there are two ways: one is to use map fixture and supply a map to read from in its header row, the other is to use a JavaScript expression inside the wiki page.
The latter is easier in code now, but I fear that feature might be dropped when migrating FitNesse to a higher Java version (higher Java versions no longer have an in-built JavaScript engine).


To use MapFixture:
```
|script     |map fixture        |$userMap                              |
|$login=    |value              |login                                 |
```

Then you have `$login` to use wherever.


Using JavaScript (see http://fitnesse.org/FitNesse.FullReferenceGuide.UserGuide.WritingAcceptanceTests.SliM.ExpressionsInTables):

```
|script |map fixture | 
|set value |true |for|rememberMe |
|set value |${PASSWORD} |for|password |
|set value |${APPLICATION_NAME}|for|applicationName| 
|set value |$`userMap.login` |for|login |
|$userMapCreated=|copy map |
```

**Comment by marciojusto** [comment]
Thanks a lot! It's worked!
