### ISSUE TITLE
enter followed by click (textbox)

### ISSUE THREAD

**Issue by teunisnl** [fhoeben/hsac-fitnesse-fixtures#40]
```
|storyboard|browser test                                                              |
|open      |!-https://www.telfort.nl/Algemeen/Contact/contactformulier/glasvezel.htm-!|
|click     |Ja, ik ga akkoord                                                         |
|click     |Verzenden                                                                 |
|enter     |abcefg       |as       |id=wmformfragment_personal_data_description       |
|click     |Man                                                                       |
````
In this specfic case you get no error, but the screenshot clearly show that Man radio button is never clicked
(either clicking man 2x or clicking before enter by passes the issue)

**Comment by fhoeben** [comment]
Strange indeed. I don't know why this is may be. I see I can also bypass the issue by adding a '|press|tab|' after entering a value, to exit the text area.

Maybe there is some Javascript attached to leaving the text area the messes up the clicking of 'Man'?

The script below has a check to ensure the 'Man' option is actually selected. 
(Was there a reason you used on id to identify the 'Uw vraag' input, or that you escaped the URL to open?)

    |script|browser test                                                          |
    |open  |https://www.telfort.nl/Algemeen/Contact/contactformulier/glasvezel.htm|
    |click |Ja, ik ga akkoord                                                     |
    |click |Verzenden                                                             |
    |enter |abcefg                   |as                 |Uw vraag                |
    |press |tab                                                                   |
    |click |Man                                                                   |
    |check |value of                 |Man                |true                    |

**Comment by teunisnl** [comment]
the escped url/id use, old habbits (and for checks you do need the escapes)

and for press tab thatsould solve the issues, ty for hints
