### ISSUE TITLE
Json problem

### ISSUE THREAD

**Issue by julien-guilet** [fhoeben/hsac-fitnesse-fixtures#407]
Hello, 

I have a problem with the manipulation of JSON data.
I search in all fixture of JSON manipulation, but i didn't found a solution for put a JSON object on key.
JsonFixture always put quotation marks on start and end of expression.
Example :
![jsonProblem](https://user-images.githubusercontent.com/68598612/159652089-46a36418-0cc4-4272-b079-b6c82b0c0a96.PNG)

**Comment by tcnh** [comment]
The issue here is that you send a String (the string is not deserialized to json). You can achieve what you want with a workaround using map fixture:
![image](https://user-images.githubusercontent.com/2232710/159712291-17b2a299-b1a5-41d3-971d-57709f7c6861.png)
