### ISSUE TITLE
Headless Chrome Execution

### ISSUE THREAD

**Issue by Mohim-Singla** [fhoeben/hsac-fitnesse-fixtures#417]
In reference to issue #348 
Hey @mvfsp14 and @fhoeben I also intend to run some tests with chrome browser in headless mode. But the issue is the browser hangs upon loading the webpage and returning the following error: [SEVERE] Timed out receiving message from renderer.
Upon finding a solution to this error I realized that it might get resolved by setting the PageLoadStrategy to NONE or EAGER. I'm new to fitnesse and I'm unable to pass this argument to the chrome profile, Could you please help me with the correct syntax/fitnesse table as to how can I set the value of PageLoadStrategy to NONE.

Here is my code:
|script |map fixture |
|set value |headless |for|args[0] |
|set value |disable-gpu |for|args[1] |
|set value |--start-maximized |for|args[2] |
|set value |--no-sandbox |for|args[3] |
|set value |--disable-dev-shm-usage |for|args[4] |
|set value |--dns-prefetch-disable |for|args[5] |
|set value |--silentOutput=true |for|args[6] |
|set value | !-PageLoadStrategy.NONE-! |for| !-setPageLoadStrategy-! |
|$HeadlessProfile=|copy map |

|script |selenium driver setup |
|start driver for|chrome|with profile|$HeadlessProfile|

Here is the error code:
[12:25 PM] Mohim Singla

EXCEPTION:ABORT_SLIM_TEST:nl.hsac.fitnesse.fixture.slim.StopTestException: Could not start a new session. Response code 400. Message: invalid argument: entry 0 of 'firstMatch' is invalid from invalid argument: cannot parse capability: goog:chromeOptions from invalid argument: unrecognized chrome option: capabilities

**Comment by tcnh** [comment]
PageLoadStrategy is not a chrome specific option, but a top-level capability. I'm afraid the only way to set those is using a running remote (can be localhost) driver and connection to it. You can then define your capabilities as json, where both the pageLoadStrategy and the chromeOptions capabilities are part of.

That said, I have not seen this error in a really long time. Which versions of hsac-fitnesse-fixtures and chrome are you running and on what OS?

**Comment by Mohim-Singla** [comment]
Thanks for the response.
I'm using the following versions:
hsac-fitnesse-fixture: 5.2.9
Chrome Version: 102.0.5005.61
OS: Linux amd64 version:4.15.0-161-generic

I'm getting this error message for one particular application. I did try to run the tests on other applications and it's working fine.

**Comment by fhoeben** [comment]
@Mohim-Singla do you also get the error when you run the test with 'regular' chrome instead of headless?

I recall this error mostly when the chrome process I launched (or tried to launch) died for some reason (e.g. insufficient memory)

**Comment by Mohim-Singla** [comment]
Actually I'm running Fitnesse on some other machine and we do not have any graphical interface on that machine. So the only option available is to run the browser in headless mode.
Also if I don't try to pass pageLoadStrategy option to the driver's profile and run some test suite on some other application it works fine. But for the application we intend to run the test suite it gets hang on the "open _URL_" command. The webpage that loads can be seen in the screenshot that Fitnesse takes but it gets timed out and gives this error in the execution logs: [SEVERE] Timed out receiving message from renderer. 
I have increased the timeout time even to 600 seconds, but no luck!

**Comment by fhoeben** [comment]
@Mohim-Singla it still sounds like something fishy is happening on the page. What happens running locally (both headless and normally) using the same site?

If you go to the site manually with the chrome developer tools open, anything special in the (JavaScript) 'Console' or in the 'Network' tabs (like an error or a network request that fails or takes a really long time).


One option that might influence your results, that you could try, is adding the following row _above_ the "open URL" row.
```
|set continue if ready state interactive|true                                      |
```

**Comment by fhoeben** [comment]
@Mohim-Singla I believe one of those errors might indeed be causing the problems. Actually the use of synchronous XMLHttpRequest on the main thread seems most likely to me (I didn't even know that that was possible) and if it is I fear that no page load strategy will fix it.
If that is indeed that case I expect you to run into the same problem running the same test from your local machine with a regular (non headless) chrome. Do you have the problem then?

Mismatching versions of chrome and chromedriver can also cause many problems. That's one of the reasons I prefer running tests using the docker images. That way I'm sure I'm using a matching chrome and chromedriver and I don't have to mess with installing chrome on a CI server, and it doesn't need to be run in headless mode either.

But you described that you could test other applications using the same chrome and FitNesse-hsac setup, so the chrome and chromedriver combination does seem to work.

**Comment by Mohim-Singla** [comment]
Thank you @fhoeben for your help.
I won't be able to run Fitnesse on my local system due to restrictions by my company. I'll surely try to run the test cases using docker image and if the issue still persists, I think it would be better to debug the error from the application's side. Thanks a lot for your help.

**Comment by Mohim-Singla** [comment]
Hi again @fhoeben, I did tried to run the test locally on my windows machine (windows 10 and both in the headless and non-headless mode) and the test suite is running perfectly fine, but It's not working in the Linux environment whose configurations I mentioned earlier. Any idea as to what would be the problem?

**Comment by fhoeben** [comment]
@Mohim-Singla sorry I have no idea what could be done to prevent this.

One thing I can think of to try is seeing what happens running the test in a docker container. If that fails locally maybe it can assist in tracking down a cause/fix. If that works it could be something to try on the CI server (if it works locally it should work there also).
