### ISSUE TITLE
Redirects are automatic followed

### ISSUE THREAD

**Issue by AukeRoze** [fhoeben/hsac-fitnesse-fixtures#42]
When we do a get that follows a redirect  we cannot do different checks because
the redirect is automatic followed.
We want an option in fitnesse that we can stop following an redirect

**Comment by fhoeben** [comment]
Sounds like a fine option for HttpTest (and its subclasses).

**Comment by fhoeben** [comment]
Fix, based on your pull request, included in 2.5.3. Thanks @AukeRoze.
