### ISSUE TITLE
How to start chrome with json capabilities

### ISSUE THREAD

**Issue by aquddos123** [fhoeben/hsac-fitnesse-fixtures#441]
If I were to use script table in wiki page and start chrome with json capabilities how can I do that?
I see this option available only with jUnit test suites when running with override selenium settings. But I want to exercise this in interactive fitnesse mode when using fitnesse standalone. 

**This is what is available:**
![image](https://user-images.githubusercontent.com/4468089/208182805-4cd850f2-37dd-41df-a9aa-1af89d145e8b.png)

**But this is what I am looking for:**
![image](https://user-images.githubusercontent.com/4468089/208182896-d304891a-d6b9-4e35-b64d-e2091929fdc9.png)

**Comment by fhoeben** [comment]
At the moment I don't believe this is possible. But I don't quite understand *why* this would be desirable. What the jUnit logic does is parse the JSON string to a `Map` and then pass that Map to the `startDriverWithProfile` method. So this is exactly the same as what is in your 'This is what is available' screenshots.

**Comment by aquddos123** [comment]
Yes, I agree jUnit configuration provides this option but unfortunately, we can't use jUnit configs. We need to rely on FitNesse standard method of execution which is using standalone JAR. That is why we want to keep all selenium browser configurations in the fitnesse wiki. 
I asked because the json capabilities option is available in the wiki's when using grid but not with standalone browsers.

![image](https://user-images.githubusercontent.com/4468089/208524063-1eacd13f-147f-46d5-8ef6-3ffc6a1855ae.png)

**Comment by fhoeben** [comment]
No my point was that the JSON option offers no advantage over specifying a map via the wiki. Why do you want to use JSON instead of just defining the map via `MapFixture`?

Anyway, you can use `JsonFixture` to parse the JSON string and then pass it to `SeleniumDriverSetup`. 

Something like:
```
|script|json fixture                            |
|load  |!-{"args":["headless", "disable-gpu"]}-!|
|$a=   |json path|$                             |

|script          |selenium driver setup |
|start driver for|chrome|with profile|$a|
```

In this example I load the JSON from the wiki, but you could also load it from a file, which might be better if you want to use the same config in a CI run as it allows you to have the same content in the browser as via the command line.

**Comment by aquddos123** [comment]
Thanks @fhoeben. 
The map fixture is working fine. We were just trying to simplify it by passing the entire script from command line or using a file as you described. I think json fixture solution serves  our purpose. 
Thanks!
