### ISSUE TITLE
[Question] Test not run logic

### ISSUE THREAD

**Issue by aquddos123** [fhoeben/hsac-fitnesse-fixtures#442]
I want to understand the logic how we skip tests with message "Test not run" when a timeout occur. And is there any way to override or reset this skip test logic?
  
I have several suites (SuiteA, SuiteB, SuiteC) with their own SuiteSetUp and SuiteTearDown. Each SuiteSetUp is starting its own fresh selenium driver and SuiteTeardown is closing and quitting driver. 
When running all suites together, if anything times out in **SuiteA**, not only tests in SuiteA are skipped but tests in all following suites (SuietB, SuiteC) are also skipped.  Whereas, I am expecting only test within SuiteA should be skipped and since other suites are starting their own selenium driver, they should be running normally.

**This is how my suite structure looks like:**

![image](https://user-images.githubusercontent.com/4468089/208269851-f71ef0dd-b9a9-41b9-b646-87d8f765fd33.png)

**This is the cause of timeout in SuiteA:**

![image](https://user-images.githubusercontent.com/4468089/208270715-8680b6eb-4506-4388-9ca4-4bcc261cde70.png)

**This is how SuiteSetUp fails to start new selenium driver in SuiteB when there is something times out in SuiteA:**

![image](https://user-images.githubusercontent.com/4468089/208269898-c8bc6014-e61a-4dc3-a9a7-82e12b37dabb.png)

I am using FitNesse in an interactive mode using fitnesse-standalone.

**Comment by fhoeben** [comment]
The handling currently indeed is for the entire suite being executed, not for sub-suites. This has nothing to do with hsac-fixtures selenium setup. It is FitNesse's standard 'stop suite exception' handling.

I would recommend doing 3 separate runs for each of the suites, one after the other. This should give you the behaviour regarding exception handling you need.

**Comment by aquddos123** [comment]
Thanks!
