### ISSUE TITLE
Store after a get value of specified attribute inside a element

### ISSUE THREAD

**Issue by Thiouwz** [fhoeben/hsac-fitnesse-fixtures#45]
Hello,
I'm trying to check if a "like" action will increment the number show on my web page.
To do that, I was thinking to store number value before the action, and compare it to the value after the action.

I know I can get my value this way : value of | xpath=//*[@id="nb-vote"]
Is there a way to store it temporaly?

**Comment by fhoeben** [comment]
Standard Slim scenario table feature to create a '[symbol] (http://fitnesse.org/FitNesse.UserGuide.WritingAcceptanceTests.SliM.SymbolsInTables)' should do the trick. Afterwards you can compare using '[value comparison](http://fitnesse.org/FitNesse.UserGuide.WritingAcceptanceTests.SliM.ValueComparisons)' :

```
|$before=|value of | xpath=//*[@id="nb-vote"]|
|click|Like|
|check|value of | xpath=//*[@id="nb-vote"]|> $before|

```

**Comment by Thiouwz** [comment]
Works like a charm, thank you :D
