### ISSUE TITLE
Req: deleteAllCookies for all domains

### ISSUE THREAD

**Issue by teunisnl** [fhoeben/hsac-fitnesse-fixtures#46]
I'm having issue with a website cookiewall, they set a cookie on a 2nd domain, and even if i throw away cookies of main site, the cookie on the different domain will make sure i never get see cookiewall again. making it very hard to suite test the website.

Currently by passing this by restarting the driver in setup/teardown, but for future tests a deleteAllCookies that really clears all cookies would be nice

**Comment by fhoeben** [comment]
This is a limitation of selenium, as far as I know. Try opening a page on the 2nd domain and doing a deleteAllCookies there. That should clear those also.

If you want to start your tests 'clean' I recommend doing a delete on both domains in the SetUp page (and not on TearDown).
