### ISSUE TITLE
Request: extend fixture to support appium?

### ISSUE THREAD

**Issue by tcnh** [fhoeben/hsac-fitnesse-fixtures#47]
Not an issue, more like a feature request.

Would it be possible to extend the driver setup and helpers to make use of AndroidDriver (appium) and support MobileElements (subclass of WebElement, but with bonus-operations), so that we could create a native app test fixture that supports swiping, multi-touch and mobile element locating?

I tried extending it, but alas my experience is insufficient. (I get an AndroidDriver, but then fail, because the rest of the fixtures are expecting WebElements and not MobileElements). Using only standard webDriver commands, automating native apps already works quite nicely using your fixtures.

**Comment by fhoeben** [comment]
What would be be needed to make use of AndroidDriver? I would expect it already to be possible, but maybe a bit cumbersome.

Can you maybe share your attempt (via a fork) and explain where you run into problems?

**Comment by tcnh** [comment]
Got it running, still needs a bit of polishing. I'll create a demo page + a small native app fixture to show the extra functionality and share in a fork.

**Comment by tcnh** [comment]
New approach in https://github.com/tcnh/hsac-fitnesse-fixtures/tree/androidFixture
Not ready to be a PR yet, but I think this is a better way to integrate Appium than the initial approach. We now have two new fixtures (one for iOS and one for android), both implementing the same interface to allow for cross platform scripting.

Element locating uses a very basic level of heuristic to determine what element to use (for Android. iOS fixture uses the first one that matches the lookup). Locating requires minimal technical knowledge of the application, as it tries to find elements by visible text, decriptions, hints or id-partials. Will try and find a way of adding acceptance tests that work with sauce in the next days and also create documentation.

Would appreciate any feedback or suggestions

**Comment by fhoeben** [comment]
Looks cool feature-wise. But it is quite a bit of code. I have to find some time to look through it properly!

**Comment by fhoeben** [comment]
I've started work (based on your ideas) in a new project. Any help/suggestions are welcome: https://github.com/fhoeben/hsac-fitnesse-appium
