### ISSUE TITLE
Remove remote-allow-origins all argument after Selenium fix

### ISSUE THREAD

**Issue by timovd** [fhoeben/hsac-fitnesse-fixtures#481]
The changes in #477 starting the chromebrowser with _remote-allow-origins=*_ arguments need te be removed after Selenium has a fix for this.
This is just a workaround described in https://github.com/SeleniumHQ/selenium/commit/807bb7d97560aab7181e968944ed976cd5bccf73

**Comment by fhoeben** [comment]
Selenium 4.9.0 is out, see #489. We need to fix some stuff (hopefully just the imports. And hopefully the changes this issue refers to can be reverted.
@timovd can you take a look at Selenium 4.9 support and addressing this issue?

**Comment by fhoeben** [comment]
Latest release should include the fixes from Selenium. @timovd can you validate and revert the `remote-allow-origins` arguments to chromedriver if indeed possible?

**Comment by timovd** [comment]
Did a few tests and it seems like "remote-allow-origins *" can be removed now. Will create a PR after some more tests.
