### ISSUE TITLE
Why does getEnvironment().getFitNesseRootDir() return target/fitnesse-results  when running via FixtureDebugTest ?

### ISSUE THREAD

**Issue by pvbemmelen62** [fhoeben/hsac-fitnesse-fixtures#482]
When I run a testscript via FixtureDebugTest , I see that

this.getEnvironment().getFitNesseDir() : wiki
this.getEnvironment().getFitNesseRootDir() : target/fitnesse-results
this.getEnvironment().getFitNesseFilesSectionDir() : C:gittoolchaintargetfitnesse-resultsfiles

The top of the project is C:\git\toolchain  on a Windows machine.

Why is
    this.getEnvironment().getFitNesseRootDir() : target/fitnesse-results
?
I would expect it to be    wiki\FitNesseRoot  .

**Comment by fhoeben** [comment]
This is done since the tests run via this class are expected to be part of a jUnit run that will generates all its results in the `target/fitnesse-results` directory, all links inside the (html) test output are expected to point to files in that directory so that just having this directory in the CI server (or docker) results gives the full HTML directory without broken links (for screenshots and files up- and downloaded).

Having said that there may be a better/different way to achieve this. This was one of the first parts of this project I implemented (it was quite some time ago and I don't quite recall).
On the other had I don't recall ever having to go back to it or change stuff. 

Are you just wondering or was this causing problems for you?

**Comment by fhoeben** [comment]
But this also means you are actually doing two test runs (one to generate `ListFilesGenerated` and then a second that will include that page), correct?

This is similar to what I do in the acceptance tests, in [GeneratedSymbolicLinkSuite](https://github.com/fhoeben/hsac-fitnesse-fixtures/tree/master/wiki/FitNesseRoot/HsacExamples/SlimTests/UtilityFixtures/GeneratedSymbolicLinkSuite)
 * first I run [SuiteGenerator](https://github.com/fhoeben/hsac-fitnesse-fixtures/blob/master/wiki/FitNesseRoot/HsacExamples/SlimTests/UtilityFixtures/GeneratedSymbolicLinkSuite/SuiteGenerator.wiki), it will create `EnLocaleTests.wiki` and `EnLocaleTests.wiki`
 * the in the 2nd run I run these

To place the file I use a path relative to `getEnvironment().getFitNesseDir()`, see https://github.com/fhoeben/hsac-fitnesse-fixtures/blob/6cd6fb917a2d39a3a9adb9388119c170265d2755/src/main/java/nl/hsac/fitnesse/fixture/slim/FileFixture.java#L37.

Would something similar work for you?

**Comment by fhoeben** [comment]
But this also means you are actually doing two test runs (one to generate `ListFilesGenerated` and then a second that will include that page), correct?

This is similar to what I do in the acceptance tests, in [GeneratedSymbolicLinkSuite](https://github.com/fhoeben/hsac-fitnesse-fixtures/tree/master/wiki/FitNesseRoot/HsacExamples/SlimTests/UtilityFixtures/GeneratedSymbolicLinkSuite)
 * first I run [SuiteGenerator](https://github.com/fhoeben/hsac-fitnesse-fixtures/blob/master/wiki/FitNesseRoot/HsacExamples/SlimTests/UtilityFixtures/GeneratedSymbolicLinkSuite/SuiteGenerator.wiki), it will create `EnLocaleTests.wiki` and `EnLocaleTests.wiki`
 * the in the 2nd run I run these

To place the file I use a path relative to `getEnvironment().getFitNesseDir()`, see https://github.com/fhoeben/hsac-fitnesse-fixtures/blob/6cd6fb917a2d39a3a9adb9388119c170265d2755/src/main/java/nl/hsac/fitnesse/fixture/slim/FileFixture.java#L37.

Would something similar work for you?

**Comment by pvbemmelen62** [comment]
Above method resulted in paths starting with
C:\git\toolchain\wiki\.
where the '.' is superfluous, so I've added code to make it canonical, taken from
 http://www.java2s.com/example/java-utility-method/canonical-path-create/getcanonicalpath-string-path-06b89.html
I'll close the call; thanks for your support, Fried.
