### ISSUE TITLE
Support setting HTTP headers on GET verb

### ISSUE THREAD

**Issue by benjammin17** [fhoeben/hsac-fitnesse-fixtures#5]
We are writing tests using:

|set value	| <myValue> |for header|Application-Id|

But apparently it doesnt work with a GET. POST seems to work fine (have not tried delete yet).
Could this be implemented in a future build?

**Comment by fhoeben** [comment]
I also added support for headers on DELETE

**Comment by benjammin17** [comment]
Thanks this helps a lot
