### ISSUE TITLE
Where do I go for help on "No SLF4J providers were found" ?

### ISSUE THREAD

**Issue by pvbemmelen62** [fhoeben/hsac-fitnesse-fixtures#500]
Recently I noticed the message
<pre>
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
</pre>
when starting the Fitnesse wiki server.

I guess this is not related to the hsac fixtures; I'd normally create an issue on fitnesse.org , but fitnesse.org is not reachable, which may be related to https://github.com/unclebob/fitnesse/issues/1387 .

**Question: where do I go for help on this problem.**

In case I came to the right place, here some info related to the problem:
Program jinfo provided a lot of info on the wiki process, with o.a. the following lines:
<pre>
java.class.path=fitnesse-standalone.jar;C\:\\git\\toolchain\\wiki\\plugins\\hsac-fitnesse-plugin-1.32.10.jar;C\:\\git\\toolchain\\wiki\\plugins\\toolchain-fitnesse-plugin-2.0.16-jar-with-dependencies.jar^M
</pre>
<pre>
java_class_path (initial): fitnesse-standalone.jar
</pre>
And I've added the dependency for groudId "org.slf4j" and artifactId "slf4j-simple"  and version "2.0.7" to the pom, but that jar doesn't show up in the classpath of the wiki server, so I still "No SLF4J providers were found".

**Comment by fhoeben** [comment]
(fitnesse.org seems up to me)

The error is indeed something for https://github.com/unclebob/fitnesse, see https://github.com/unclebob/fitnesse/issues/1329
But I believe it is not something to worry about. It has to do with fitnesse being both a library and executable. If the dependency would be added to the wiki executable (where I expect you see the error) than fixture developers would not be able to use their own slf4j logging provider in their fixtures (where the dependency you added to the `pom.xml` ended up, I actually believe this project already ensures a provider is available in the test process so it should not be necessary)

**Comment by pvbemmelen62** [comment]
You are right: when running a test, the Execution Log > Standard Error    shows:
<pre>
Standard Error:
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
ERROR StatusLogger Log4j2 could not find a logging implementation. Please add log4j-core to the classpath. Using SimpleLogger to log to the console...
</pre>
so a SimpleLogger is used for the test process.

I'm worried that logging message from the wiki server process won't be printed.
