### ISSUE TITLE
Why does "enter as" not use topmost matching input when out of view ?

### ISSUE THREAD

**Issue by pvbemmelen62** [fhoeben/hsac-fitnesse-fixtures#511]
I have the following command in my Fitnesse script:

`|enter                 |Informatievoorziening           |as             |afdeling                   |`

Up until now I assumed that a command that affects some element on the webpage, uses the element spec in the command, and searches the page from top to bottom for a matching element.

I now observe that when there are two elements that match, both having aria-label="afdeling" , and the topmost element is scrolled out of view and the bottom element is visible, that then the bottom element is used by the command.

**Is that correct behaviour ?**

I have a Fitnesse script to show the behaviour described:
[debug-enter-as-heuristic.wiki.txt](https://github.com/fhoeben/hsac-fitnesse-fixtures/files/11646248/debug-enter-as-heuristic.wiki.txt)

**Comment by pvbemmelen62** [comment]
Slightly clearer script, because it uses "scroll to" command:
[debug-enter-as-heuristic.wiki.txt](https://github.com/fhoeben/hsac-fitnesse-fixtures/files/11650248/debug-enter-as-heuristic.wiki.txt)

**Comment by fhoeben** [comment]
@pvbemmelen62 

In general I believe that if two values have the same label they should have the same function or the context must be really clear, and then setting that explicit context makes things more clear.

I never assumed any order. And I have to say I actually like the fact that the visible element is preferred to one that requires scrolling. It is more like what a regular end-user would do (when you tell me to fill a field I fill the one I see, I don't go scrolling around the page whether there are other fields named the same).

So I think my answer to your question is: "yes it is" and we should keep the behaviour as-is. Your test script will probably be easier to understand and more maintainable if you are able to set an explicit context to indicate which 'afdeling' input you mean. (And the application would probably be better if the labels were different in the first place).

Imagine the input you intend to fill is removed from the form (or the positions changed), without explicit context the test script will just fill the other input and continue to the next line. In my opinion this is not desirable, you should get an error indicating the input is not available so it is clear the test script needs to be updated to handle the removed/renamed input.

If a context is not possible, and the names must remain the same, I guess an explicit scroll can get it to work, but I think your test will be fragile....

**Comment by fhoeben** [comment]
@pvbemmelen62 in code I have an order between different heuristics. But for a single 'selector' (like aria-label=...) I just use the order Selenium provides. I don't know which order (if any) order they guarantee

**Comment by pvbemmelen62** [comment]
I'll close the call here.
And I'll have a look at Selenium , or WebDriver .
Maybe https://www.w3.org/TR/webdriver/#element-retrieval  where it states
`Element retrieval searches are performed using pre-order traversal of the document’s nodes that match the provided selector’s expression. `
is applicable. But does that allow any preference for elements visible from the viewport?
Anyway, that spec is rather complex. For instance:
`The querySelectorAll(selectors) method steps are to return the static result of running scope-match string selectors against this.`
