### ISSUE TITLE
Alert problem - org.openqa.selenium.UnhandledAlertException: Unexpected modal dialog 

### ISSUE THREAD

**Issue by violinner** [fhoeben/hsac-fitnesse-fixtures#52]
Driving a desktop Windows Firefox browser, when an "OK / Cancel" alert box is popped up,
the alert flashes, disappears, and the browser test script immediately fails with an exception:

org.openqa.selenium.UnhandledAlertException:
Unexpected modal dialog (text is: are you sure, etc., etc.
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
...
at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
...
at nl.hsac.fitnesse.fixture.util.SeleniumHelper.executeScript(SeleniumHelper.java:483)

I am using-
"Driver info: org.openqa.selenium.firefox.FirefoxDriver",
selenium-api-2.47.1.jar (selenium-remote-2.47.1.jar, selenium-support- 2.47.1.jar)
selenium-firefox-driver-2.47.1.jar

Is there a need to use another version, or call some set-up to make the alert box stay up?

Thanks!

**Comment by fhoeben** [comment]
Is this only on firefox, or also on chrome?
I have not encountered this problem before. But I only recall testing with chrome, and maybe safari, for pop-ups.

**Comment by violinner** [comment]
I must test on Firefox on Windows.
I modified HsacExamples.SlimTests.BrowserTests.SuiteSetUp to use only Firefox.
I have downloaded HSAC version 2.5.4, and modified the existing Script Test (Source 1, below)
to talk to a locally hosted servlet (Source 2, below).
The button click works and pops up a window.confirm alert, producing an Unexpected... exception in Selenium.

>>>>>>>>>>> Source 1:
|script           |browser test |
|open             |http://localhost:8080/violinServlet/ |
|click            |Try it |
|wait seconds     |1 |
|show             |take screenshot   |Foto_1  |

>>>>>>>>>>> violinServlet is running locally on tomcat :8080:

>>>>>>>>>>> Source 2, index.jsp:
<!DOCTYPE html>
<html><body><p>Click the button to demonstrate the prompt box.</p>
<button onclick="myFunction()">Try it</button>
<p id="demo"></p>
<script>
function myFunction() {
    var truefalse = window.confirm("are you ready?");
     document.getElementById("demo").innerHTML = "Hello, you are ready :" + truefalse;
}
</script></body></html>

Incidentally, when SuiteSetup is modified to uncomment only internet explorer, an error results.  What are the prerequisites to driving internet explorer?

**Comment by fhoeben** [comment]
To run tests with IE you need to configure your windows' internet options in a specific way. See https://github.com/SeleniumHQ/selenium/wiki/InternetExplorerDriver#required-configuration. When using the hsac-fitnesse-fixtures with Internet Explorer locally the first step, adding the driver to your PATH, is not needed.

I assume you get the error on the `|show |take screenshot |Foto_1 |` line? This is a known limitation of Selenium. When an alert is shown, after clicking `Try it`, Selenium can do nothing but interact with the alert. So not even taking a screenshot is possible.

Having said that I re-ran test `HsacAcceptanceTests.SlimTests.BrowserTest.AlertHandlingTest`, which is very similar to your testcase. This test succeeds with Chrome, but not with Firefox or Safari. I will investigate further.

**Comment by violinner** [comment]
Yes, I get the error on the  |show |take screenshot |Foto_1 |  line.
The error contains "Page content:" and a screenshot of the results after the confirm box has been closed.
That is, "Hello, you are ready: false"

Thank you for investigating alerts in FireFox.
I found a hint on the Web that I should set the following, but is it possible to do this locally?
>    |with capabilities     |!{unexpectedAlertBehaviour:ignore}|

**Comment by fhoeben** [comment]
For Firefox there is indeed a bug in BrowserTest. The 'implicit wait for Angular' messes up the alert handling. As a workaround I suggest you add the following row to your test, after the 'open' row:
`|set implicit wait for angular to|false           |`

For Safari the cause is clear. Its selenium driver does not support (like PhantomJs): 
> A modal dialog was opened. The SafariDriver does not support interacting with modal dialogs. To avoid hanging your test, the alert has been dismissed. For more information, see http://code.google.com/p/selenium/issues/detail?id=3862

**Comment by fhoeben** [comment]
I will see whether I can fix Firefox to handle alerts as intended, even with implicit wait for angular enabled. BUT I was already thinking of making implicit wait for angular be set to false by default as I find it is rarely needed (even when testing AngluarJs sites) and can slow down tests quite a lot.

**Comment by fhoeben** [comment]
I believe the latest code (after my last commit) addresses you problem.

On my machine this fixes the sample test/page you gave. Does this also work in your real test?

**Comment by violinner** [comment]
I have downloaded source from Master, updated NgBrowserTest.java which was changed, built the package and re-tested.  Neither change makes a difference-

1) using the new hsac-fitnesse-fixtures-2.5.5-SNAPSHOT.jar
or
2) setting "|set implicit wait for angular to|false |"
after "|open|http//localhost:8080/...|"

Do you have any advice?  Should I be building the branch instead?
Thanks!

**Comment by fhoeben** [comment]
You have the right code, but I forgot one import change to you have to make to the wiki.
The message is actually correct, Selenium requires you to handle the alert before continuing. So you have to add either `|dismiss alert|` or `|confirm alert|` above `|show |take screenshot |Foto_1 |` row.

Have you tried 'HsacAcceptanceTests.SlimTests.BrowserTest.AlertHandlingTest' after changing its SuiteSetUp to start firefox instead of phantomjs?

**Comment by violinner** [comment]
This works perfectly.  Do you have any plans for a release incorporating this fix?
Thank you.

**Comment by fhoeben** [comment]
Latest release has fix: https://github.com/fhoeben/hsac-fitnesse-fixtures/releases/tag/2.5.5

**Comment by bhabanipattanayak** [comment]
You can ass this if you want to do some action for all the alerts
DesiredCapabilities browser = DesiredCapabilities.firefox(); 
browser.setCapability(CapabilityType.UNEXPECTED_ALERT_BEHAVIOUR, UnexpectedAlertBehaviour.IGNORE);
You can use UnexpectedAlertBehaviour.ACCEPT or UnexpectedAlertBehaviour.DISMISS
Same can be done for other drivers.
