### ISSUE TITLE
Skip executing SetUp.wiki

### ISSUE THREAD

**Issue by timovd** [fhoeben/hsac-fitnesse-fixtures#527]
In the main folder "1" I created SetUp.wiki.
SetUp.wiki is executed each time when a script is executed, for example Test.wiki in folder 1\1.1 and Test2.wiki in folder 1\1.2.
In folder 1\1.3 I don't want to execute SetUp.wiki from folder 1.
I tried adding
_!define ALL_UNCLE_SUITE_SETUPS {false}_
_!define ALL_UNCLE_SETUPS {false}_ (not sure if this does anything)
but this didn't help. Is there a way to skip SetUp.wiki in a specific folder or test?

**Comment by fhoeben** [comment]
I don't believe there is. The only way to prevent this is to have an extra level in the hierarchy, move the setup to one of the children and place all tests that should have the setup below that child.

Eg

1. 1
  1.a.
      1.a.1. SetUp
      1.a.2. Test1
      1.a.3. Test2
  1.b. Test3
