### ISSUE TITLE
Could not invoke constructor for MapFixture[0] or The instance scriptTableActor.setValueFor. does not exist

### ISSUE THREAD

**Issue by Mrle1992** [fhoeben/hsac-fitnesse-fixtures#528]
I have a problem, when I run a test in the fitness program, it gives me this Could not invoke constructor for MapFixture[0] for some function and The instance scriptTableActor.setValueFor for another. does not exist. It also gives me this error ookie "latestContext" does not have a proper "SameSite" attribute value. Soon, cookies without the "SameSite" attribute or with an invalid value will be treated as "Lax". This means that the cookie will no longer be sent in third-party contexts. If your application depends on this cookie being available in such contexts, please add the "SameSite=None" attribute to it. To know more about the "SameSite" attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite ExampleSuite.Environment.Acceptance.TestScripts.DesktopDevice.ScopeInsight:27:39
![Untitled999](https://github.com/fhoeben/hsac-fitnesse-fixtures/assets/142903765/ca2aab52-6c33-476d-8999-193787f46dec)

**Comment by fhoeben** [comment]
I don't believe the cookie is a problem, it is not intended to be sent to third parties.

The constructor error message probably means that FitNesse cannot find the Java code. How did you:

- Install FitNesse?
- Start the wiki?
- Which Java version are you using?

**Comment by Mrle1992** [comment]
I'm sorry, I realized later that I didn't write the question properly. In any case, here is exactly what the problem is, this is a

![Untitled888](https://github.com/fhoeben/hsac-fitnesse-fixtures/assets/142903765/985e1c03-cfdb-4eda-a944-4bebf4999303)
 WARNING: Cookie "latestContext" does not have a proper "SameSite" attribute value. Soon, cookies without the "SameSite" attribute or with an invalid value will be treated as "Lax". This means that the cookie will no longer be sent in third-party contexts. If your application depends on this cookie being available in such contexts, please add the "SameSite=None" attribute to it. To know more about the "SameSite" attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite ExampleSuite.Environment.Acceptance.TestScripts.DesktopDevice.ScopeInsight:27:39 a this is an

 ERROR: The Components object is deprecated. It will soon be removed. ExampleSuite.Environment.Acceptance.TestScripts.DesktopDevice.ScopeInsight

java version "1.8.0_202"
Apache Maven 3.9.2
Fitnesse Version 20211027022506

**Comment by fhoeben** [comment]
What was the exact command you used to start the wiki? It looks like FitNesse is unable to find the (compiled) Java classes for the fixtures.

Did you use `mvn clean compile dependency:copy-dependencies exec:exec`?

If you used this command maybe you can also share the output you get when you press the green "Execution log" button at the top of the test results page that might provide some more details on what is going on...


Did you use https://github.com/fhoeben/sample-fitnesse-project to start your project? This is what I generally recommend.

**Comment by Mrle1992** [comment]
Thanks for your help, I managed to solve the problem with this code you gave me to start the project mvn clean compile dependency:copy-dependencies exec:exec

In the description it was written that I use this code mvn clean compile exec:exec, it is possible that it did not want to work because of that
