### ISSUE TITLE
Version 2.5.5 with Firefox driver does not find input fields on form

### ISSUE THREAD

**Issue by violinner** [fhoeben/hsac-fitnesse-fixtures#54]
In version 2.5.5, the following command stopped working in FireFox:
|enter |${value}|as|fieldname|

"type" and "tab" commands still work, which is a work-around for filling out a form where all elements are tab-able.  

Using Selenium version 2.48.2,

**Comment by fhoeben** [comment]
It stopped working. Does nothing happen, or is an error shown?
Is the 'fieldname' the text of a label, or a technical selector, or the text of of a table heading, or ...?

**Comment by violinner** [comment]
Nothing happens, and there is no error.  The next step times out waiting for a change.
The field is:
<input class="text" type="text" name="fieldname" tabindex="1" size="20" autocomplete="off">
I notice that the text tag is not terminated.  I am fixing that to see if it makes a difference.

**Comment by fhoeben** [comment]
I don't see the field in your comment? Maybe you need to add some pre-formatting to the post.

Can you try with 2.6.0-SNAPSHOT (I would potentially expect more problems there, but it is using a newer Selenium).

I did a quick check with a page, HsacExamples.SlimTests.BrowserT.ests.ScriptTest, its 'enter as' still works in firefox for 2.6.0-SNAPSHOT

**Comment by violinner** [comment]
T
What is the URL to 2.6.0-SNAPSHOT ?

**Comment by violinner** [comment]
I built 2.6.0-SNAPSHOT, and still have no luck with "enter as" on my page.
Fixing the page, and trying HsacExamples.SlimTests.BrowserTests.ScriptTest...

**Comment by fhoeben** [comment]
Did the page work with a previous version? Selecting an input based on its name attribute has not worked since 2.4.0. Can you try:
`|enter|${value}|as|name=fieldname|`

Input tags don't need to be terminated in HTML5, since they're not allowed to have content. Silly, but that should make no difference.

**Comment by violinner** [comment]
(I hope you meant that name selection has worked since 2.4.0.)
jumping for joy-
It worked when I changed my test to:
 |enter|${value}|as|name=fieldname| 

This is great - thanks.

**Comment by fhoeben** [comment]
Before 2.4.0 you did not have to use the `name=` prefix to select by name.

The reason this is now required is that I want to define my tests using texts/words as visible to the end-user, and the name is not visible. 
Any chance your input has an associated label, or is in a table row where another cell is a `th`, or...
How would an end-user refer to this input field? How do people using a screenreader know what to put in this input? The fixture attempts to allow you to refer to the input in your tests using these concepts.

**Comment by violinner** [comment]
My input is indeed associated with a label, and the script finds the field through the visible label.
I found the behavior changed when upgrading from an old version of HSAC.
Thanks.
