### ISSUE TITLE
missing Git tag for 5.2.43 and 5.2.45

### ISSUE THREAD

**Issue by hboutemy** [fhoeben/hsac-fitnesse-fixtures#540]
found while trying to rebuild https://github.com/jvm-repo-rebuild/reproducible-central/blob/master/content/nl/hsac/hsac-fitnesse-fixtures/README.md

**Comment by fhoeben** [comment]
Added tag for 5.2.45

Seems to be some annoying intermittent issue in automatic release generation where release to maven central succeeds but maven process reports an error, which prevent a tag to be made and a release published on GitHub

(I'm not bothered enough to also fix 5.2.43)

**Comment by hboutemy** [comment]
yes, let's forget about 5.2.43
FYI, the Git tag for 5.2.45 does not really correspond to the reference release: https://github.com/jvm-repo-rebuild/reproducible-central/blob/master/content/nl/hsac/hsac-fitnesse-fixtures/hsac-fitnesse-fixtures-5.2.45.diffoscope

we'll see for next release, I'll be interested if you can share the output of the failure if it happens for next release
