### ISSUE TITLE
How can I see immediately that timeout occurs ?

### ISSUE THREAD

**Issue by pvbemmelen62** [fhoeben/hsac-fitnesse-fixtures#548]
I have a script that has a scenario consisting of many lines, and occasionally some line halfway through the scenario,
has a timeout .
I won't see that the timeout occurs until the script table is fully processed, en the run log shows the results for that table.

If I make the scenario run in "debug script" mode, I get a pause popup before each instruction; but still I can't really tell if the instruction immediately before the pause popup, has timed out.

I want to see immediately that a timeout occurred, so that in "debug script" mode I can inspect the webpage, and see why I get the timeout.

**Comment by fhoeben** [comment]
What kind of timeout are you referring to? In general when unable to perform an action an attempt is made to capture both the HTML and a screenshot of the current page to allow debugging after the script has completed (this to allow 'debugging' based on CI runs where no user/console is present to inspect web pages at the time the error occurs).

To get this information (and abort the script) if some expected element is not present on the page 'wait for visible ...' can be used.

If you are running the script on your local machine and watching the browser window, wouldn't setting a large value for 'seconds before timeout ...' allow you to check the webpage manually?

**Comment by fhoeben** [comment]
Another approach can be to run the test with a Java debugger attached (using `FitNesseDebugTest`) and setting a breakpoint at the timeout handling code.

**Comment by pvbemmelen62** [comment]
I'd like to debug not after the script has completed, but immediately as the command fails with a timeout.
So I'll take the approach you suggest in your second comment above:  setting a breakpoint using the debugger.
I'll have to figure out what class/line of code that is.

**Comment by fhoeben** [comment]
Maybe I can help you identify the code location.
What is the exact 'timeout' you get, do you have example wiki and execution log output?

**Comment by pvbemmelen62** [comment]
I'm talking about a timeout in a click command.
My guess is, that the code where to put the breakpoint, would not depend on the exact element spec in the click command.
Below is a simple script that generates a timeout in the click command.

<pre>

|script          |selenium driver setup|
|start driver for|!-MicrosoftEdge-!    |

|script                               |browser test|
|scroll elements to center of viewport|true        |
|set browser size to maximum                       |
|seconds before timeout               |5           |

|script                        |
|open |https://www.example.com/|
|click|absent                  |

</pre>

**Comment by fhoeben** [comment]
Easiest place to get all timeout exceptions is at `src/main/java/nl/hsac/fitnesse/fixture/slim/web/BrowserTest.java:2795` (method `getTimeoutMessage()`). That is completely generic timeout handling so it will not immediately be clear which row of the script you are on. But you will have access to the page and all state.

If you need to find out which line of the script you are on you can ### then probably go up a few frames in the stack using your debugger to `nl/hsac/fitnesse/fixture/slim/SlimFixture.java:45` where you can see what call is actually being done by checking `method` and `arguments`. See the screenshot below taken from your example script, where I see that BrowserTest's click method is being invoked with the argument 'absent':
<img width="978" alt="Screenshot 2023-11-07 at 11 57 08" src="https://github.com/fhoeben/hsac-fitnesse-fixtures/assets/5467859/f325f27c-a7f6-484a-a57d-27d5ac4708b3">

**Comment by pvbemmelen62** [comment]
Thank you: that's exactly what I need!  I'll close the call.
