### ISSUE TITLE
How  to  import script fixture？

### ISSUE THREAD

**Issue by cmaster007** [fhoeben/hsac-fitnesse-fixtures#549]
why？  How  to  import script fixture？
![1698390170199](https://github.com/fhoeben/hsac-fitnesse-fixtures/assets/35914039/e20dbd74-3833-434c-8323-5723500917b8)

**Comment by fhoeben** [comment]
Any chance your suite is not configured to use Slim (so is using the Fit test system)?

**Comment by cmaster007** [comment]
![image](https://github.com/fhoeben/hsac-fitnesse-fixtures/assets/35914039/b33925eb-d1d8-4cb4-a37e-34fb2e0d6724)

**Comment by fhoeben** [comment]
Setting the test system should be done at the suite level, so on the parent page of this test

**Comment by cmaster007** [comment]
Setting the test system should be done at the suite level,  is error
![1698654552706](https://github.com/fhoeben/hsac-fitnesse-fixtures/assets/35914039/5db5486c-1844-4ad4-b6d2-6d56f39051a4)
Setting the test system should be done at the test level,  is ok
![1698654672935](https://github.com/fhoeben/hsac-fitnesse-fixtures/assets/35914039/cad30490-90dc-466d-b09e-c8ddcc9772a5)
but the map fixture import error

**Comment by fhoeben** [comment]
SuiteSetup is not the parent page, `OneUi.DrmAccess` is

**Comment by cmaster007** [comment]
how to  fix it？
![1698717399244](https://github.com/fhoeben/hsac-fitnesse-fixtures/assets/35914039/046e4fd7-636b-4dbd-a755-cabb9143cd65)
what  is need import？

**Comment by fhoeben** [comment]
You probably need a `!path` in your suite page `OneUi.DrmAccess`.

Have you tried basing your project on [my template project](https://github.com/fhoeben/sample-fitnesse-project), that has all this covered? 

After renaming `MyTestSuite` to something of your liking you'd be good to go.

In that suite page I have the following content:

```
---
Suite
Help: Generated suite, intended to be renamed and otherwise modified and to
---

Boilerplate test suite, generated to give your own test suite a flying start. Customize it to your heart's desire.
It is probably a good idea to add a link (i.e. [[MyTestSuite][.MyTestSuite]]) to this page on the .FrontPage.

!contents -R2 -g -p -f -h


!*> Basic setup for tests with Slim
Workaround for https://github.com/unclebob/fitnesse/issues/989
!define slim.port {0}

!define TEST_SYSTEM {slim}
!define ALL_UNCLE_SUITE_SETUPS {true}

The classpath location:
!path fixtures
!path fixtures/*.jar

*!
```

**Comment by cmaster007** [comment]
en, ok,all right but how diffrent OneUi.DrmAccess and MyTestSuite.FrontEndTests.BaiduTest  .MyTestSuite not define !path fixtures/*.jar  OneUi.DrmAccess   define is ugly ，why  not include  a suitesetup  page？

![1698816418183](https://github.com/fhoeben/hsac-fitnesse-fixtures/assets/35914039/4933d2b0-94fc-4245-a18b-762785e519fe)
It is running  ok
![1698816511265](https://github.com/fhoeben/hsac-fitnesse-fixtures/assets/35914039/0e647aa4-eccd-4f84-9f61-dde84aa37d75)
MyTestSuite.FrontEndTests.BaiduTest is  running  ok， how different？

**Comment by fhoeben** [comment]
I'm not sure I understand your last comment.
MyTestSuite does define the `!path`, see https://github.com/fhoeben/sample-fitnesse-project/blob/master/wiki/FitNesseRoot/MyTestSuite.wiki?plain=1

Maybe you overlook it in the wiki, since it is in a collapsible section (i.e. `!*> Basic setup for tests with Slim ...`)?

Putting the `!path` in a test page or specific sub-suite is possible, but not in a suite set up, as far as I'm aware. Please see http://fitnesse.org/FitNesse.FullReferenceGuide.UserGuide.WritingAcceptanceTests.ClassPath for more details.
> Whenever Fit processes test tables on a given page, it build its own internal class path by finding the !path directives on the current page, and on every ancestor page. In other words, it looks **up** the page hierarchy of SubWikis.

**Comment by cmaster007** [comment]
ok,The problem has been solved，thank you very much
