### ISSUE TITLE
Setting global timeout 

### ISSUE THREAD

**Issue by violinner** [fhoeben/hsac-fitnesse-fixtures#55]
Is there a table that can set up a global timeout for an entire suite?
I see documentation of "seleniumDefaultTimeout", but I'm unclear on where to set it.

What is the format of a table defining a longer timeout, to avoid the error in a browser test table:
"Timed-out waiting (after 10s)."

I have 75 test pages, and would like to change this in one place, to iterate until the best value is found for the network and server latency.

I have tried:

|script|selenium driver setup|
|set property|slim.timeout|value|45|
|set property|seleniumDefaultTimeout|value|45|
|note - numbers with and without "seconds", but none has an effect on the default 10s timeout|

**Comment by fhoeben** [comment]
Sorry, there is no way to set the default timeout via the wiki. The `seleniumDefaultTimeout` can be specified as a system property (e.g. `-DseleniumDefaultTimeout=20`) when starting a suite or test via jUnit (on a build server).

On the wiki you have to:
- create a scenario that sets `seconds before timeout` and use that in all script tables (you can then change the scenario to change the timeout), or
- add a line setting `seconds before timeout` in each script table, but use a wiki variable (e.g. `${BROWSERTEST_TIMEOUT}`, which you set at a root level, using `!define BROWSERTEST_TIMEOUT {20}`) to define the timeout (you can then change the timeout by changing the variable's value)

So no easy way such as you were looking for I'm afraid. But really, the 10 seconds timeout is not long enough? I pity the users of the application.

You could, of course, create a pull request to set the default via selenium driver setup. I would merge that in...

**Comment by violinner** [comment]
FWIW, starting FitNesse with this command did not change the default Selenium time-out.
java -DseleniumDefaultTimeout=25 -jar fitnesse-standalone.jar
My users are very patient.

**Comment by fhoeben** [comment]
I know starting the wiki with this command does not change the timeout. The Slim process needs to be started with option (inside a jUnit run there is only one process). Unfortunately I don't believe you can pass system properties to the Slim process when it is started by the wiki

**Comment by violinner** [comment]
Can you advise on an example script that uploads a file using a tag such as:
&lt;input type="file" name="my_upload" &gt;

Thanks.

**Comment by fhoeben** [comment]
Not really the same issue, is it? ;-)

Have you see the documentation rows:

```
*select file <file>*	Selects the supplied file using the first file input on the page. The file may be in the wiki's files section, or on the local file system.
*select file <file> for <file input>*	Selects the supplied file using the indicated input. The file may be in the wiki's files section, or on the local file system.
```
These commands work on inputs of type file.

Sample usage is in HsacAcceptanceTests.SlimTests.BrowserTest.FileUploadTest. There the file to upload is first generated (and placed in the wiki's file section) and then uploaded.

**Comment by violinner** [comment]
Not at all the same.
You are a scholar and a gentleman.
Thank you.

**Comment by dfurmans** [comment]
Hi there ! 

I have an issue with the timeout for Fitnesse Wiki
There are two different thinks

1. !define slim.timeout {120} ; that is oki and that configuration works great
2. The WEB timeout for the WIKI - this is a part when I can not find a solution to extend the timeout on HTTP on the web-browser client

How I can setup-extend the timeout waiting for the WEB part

Thanks!

**Comment by fhoeben** [comment]
@dfurmans are you referring to the timeout used by the `BrowserTest` fixture in this project (which can be configured by using its command `seconds before timeout`), or the timeout for a test run when started from the wiki (independent of what the tests are actually doing)?

**Comment by dfurmans** [comment]
Hi @fhoeben 
The test are running the chunk of the microservice for integration test performing. 
Together with @tcnh we found an issue - the problem is somehow related to the Linux distribution + Firefox browser. 

With the google chrome the global time out for the Slim server works correctly - is respected by the browser. 
So the solution was to change the http client 

Thanks for the support and additional details!
