### ISSUE TITLE
Webdriver issue CHROME 119

### ISSUE THREAD

**Issue by KvdE1994** [fhoeben/hsac-fitnesse-fixtures#554]
Hello,

We are currently receiving the following error after updating CHROME to the 119 version:

`org.openqa.selenium.WebDriverException: unknown error: result.webdriverValue.value list is missing or empty in Runtime.callFunctionOn response
(Session info: chrome=119.0.6045.106)
Build info: version: '4.11.0', revision: '040bc5406b'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.15'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [f0794b5967887a6a56da65a3b09166fc, executeScript {script=return document.readyState, args=[]}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 119.0.6045.106, chrome: {chromedriverVersion: 118.0.5993.70 (e52f33f30b91..., userDataDir: C:\Users\endenk\AppData\Loc...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:60496}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:60496/devtoo..., se:cdpVersion: 119.0.6045.106, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: ignore, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}`

We have te latest HSAC version (5.3.0), and we continue to experience issues with it.

**Comment by fhoeben** [comment]
Apparently Chrome 119 does not work with the chrome driver 118 which is bundled with the project. Upgrading to 119 chrome driver fixes the issue. BUT our GitHub release pipeline uses runners based on Chrome 117, which don't work with the 119 chrome driver.

**Comment by fhoeben** [comment]
A snapshot build fixing this issue is available at: https://github.com/fhoeben/hsac-fitnesse-fixtures/suites/17972581062/artifacts/1033576116, or in https://gitlab.com/hsac-fitnesse/hsac-fitnesse-fixtures/-/jobs/5476529530/artifacts/browse/target/

**Comment by fhoeben** [comment]
Should be fixed with 5.3.1
