### ISSUE TITLE
Gzip via REST

### ISSUE THREAD

**Issue by benjammin17** [fhoeben/hsac-fitnesse-fixtures#56]
Do you support gzip, or plan to in the future? Thnx

**Comment by fhoeben** [comment]
At the moment I've disabled content compression by Apache's http client (in the static initializer in nl.hsac.fitnesse.fixture.util.HttpClient). So I assume no gzip is being used.

I don't have plans to make this configurable, but if you would submit a pull request to allow compression to be switched on and off I would merge it.

**Comment by danielmenezesbr** [comment]
I think I can do PR for gzip support.
There is an example of design (before and after) for this configuration?
