### ISSUE TITLE
Business selector failing

### ISSUE THREAD

**Issue by teunisnl** [fhoeben/hsac-fitnesse-fixtures#57]
```
|script|browser test                                        |
|open  |http://nl.calvinklein.com/store/en                  |
|click |CLOSE                                               |
|click |Sign In/Register                                    |
|click |REGISTER                                            |
|enter |New York              |as       |City *             |
|enter |9999 AA               |as       |Postal code *      |
|show  |take screenshot       |Foto_1                       |
|note  |expected 9999 AA in postal code,result nothing there|

|script|browser test                                             |
|open  |https://www.telfort.nl/persoonlijk/combivoordeel.htm     |
|click |Ja, ik ga akkoord                                        |
|click |Ja, ik heb Telfort producten                             |
|show  |take screenshot                  |Foto_2                 |
|note  |expected Ja, ik heb to be selected,result nothing happend|
```
These might 2 seperated issues

**Comment by fhoeben** [comment]
1st issue: there is an error in the HTML of the page. The label is for `WC_UserRegistrationAddForm_AddressEntryForm_FormInput_zipCode_1` but the input has id `WC_UserRegistrationAddForm_AddressEntryForm_FormInput_zipcode_1` (notice the lowercase C in zipcode).

**Comment by fhoeben** [comment]
2nd issue: another element nested inside the label is on top of the input, the fixture tries to click the input, but fails as Selenium reports the click would hit something else (in Chrome, Firefox says the element is not visible). So the input is not actually clickable for Selenium. Clicking the label, instead of the input, using
`|click|xpath=//label/descendant-or-self::text()[normalize-space(.)='Ja, ik heb Telfort producten']/ancestor-or-self::label|` works, but is quite undesirable maintainability wise....

**Comment by fhoeben** [comment]
I believed I addressed issue 2 in the latest 2.6.0-SNAPSHOT version.
Can you check whether that works for you?

**Comment by teunisnl** [comment]
Yes 2nd works fine here now, great.
1st i understand that difference in id (only capitalization) is to risky to address ?

**Comment by fhoeben** [comment]
1st I cannot address. It is incorrect at HTML level, the reference to id in the `for` attribute must match the `id` attribute value EXACTLY. I believe you will also see that when you manually click the label 'POSTAL CODE' the input will not be activate, where this is the case for the other labels (e.g. 'STREET ADDRESS').

You have a finding on the site that should be addressed by the developers, not by changing the test script :-)

**Comment by teunisnl** [comment]
I agree, and i will post it as bug. ill close this since bost issues are solved
