### ISSUE TITLE
Exercise an unnamed file upload

### ISSUE THREAD

**Issue by violinner** [fhoeben/hsac-fitnesse-fixtures#58]
Is it possible to direct the web driver to use XPath to find an upload input tag and set a file into it?
The application I am testing has no name or id on the &lt;input type="file"/&gt; tag.

Thanks!

**Comment by fhoeben** [comment]
Yes there is (I just saw it is not documented on the GitHub wiki) it is in the project's wiki at:HsacExamples.SlimTests.BrowserTests

> select file <file>	Selects the supplied file using the first file input on the page. The file may be in the wiki's files section, or on the local file system.

Just use:
`|select file|...|`
