### ISSUE TITLE
hsac/fitnesse-fixtures-test-jre11-chrome:5.3.6 is missing expected files

### ISSUE THREAD

**Issue by DLeijenKeylane** [fhoeben/hsac-fitnesse-fixtures#581]
hsac/fitnesse-fixtures-test-jre11-chrome:5.3.6 is at least missing fitnesse/startGridAndRunTests.sh, and comparing the layers between 5.3.5 and 5.3.6 it seems completely different.

We currently override startGridAndRunTests.sh as we need to do some preparations beforehand. Is this an intended change or did something break in the build?

**Comment by fhoeben** [comment]
I fear something broke in the build...

I don't have time to look at it right now. The images are supposed to be build by the GitHub action, but I was wrestling with that for a while so maybe inadvertently messed something up. I believed both 5.3.5 and 5.3.6 were generated using the same action, at least I don't recall what changed...
Can you share the findings regarding the image layers, and maybe see if you can spot the issue in the action definition?

**Comment by DLeijenKeylane** [comment]
I compared them on Dockerhub,
5.3.6: https://hub.docker.com/layers/hsac/fitnesse-fixtures-test-jre11-chrome/5.3.5/images/sha256-529c508e9bf021524bcdb0845d3ec30dc056609d1926a9f9208dd3c0120311f5?context=explore
5.3.5: https://hub.docker.com/layers/hsac/fitnesse-fixtures-test-jre11-chrome/5.3.5/images/sha256-529c508e9bf021524bcdb0845d3ec30dc056609d1926a9f9208dd3c0120311f5?context=explore

I figured to grab fitnesse-fixtures-test-jre11-chrome-with-pdf, but 5.3.6 has the same issue.

Comparing 5.3.6 version of hsac/fitnesse-fixtures-test-jre11, hsac/fitnesse-fixtures-test-jre11-chrome and hsac/fitnesse-fixtures-test-jre11-chrome-with-pdf, they all have the exact same hash (sha256:a57036c6c6b67b7c0ec2b4d1cde21baeb7fe8c68728879655f7f78d513fb337e).

**Comment by fhoeben** [comment]
I've confirmed the problem in the output of the GitHub actions. I believe I've identified what caused it.
I can probably address this for a next release, now see whether I can fix the current images...

**Comment by fhoeben** [comment]
I believe the 5.3.6 and latest images are fixed now
