### ISSUE TITLE
HIGH Vulnerabilities in transitive dependency

### ISSUE THREAD

**Issue by aquddos123** [fhoeben/hsac-fitnesse-fixtures#583]
I'm using "hsac-fitnesse-fixtures" as dependency in our maven project.  I am also using "Mend Advise" plugin with InteliJ IDEA to scan for vulnerabilities and it is showing one HIGH vulnerability in one of the transitive dependencies. Can I request for an upgrade of this transitive dependency shown in the screenshot below?  
I may be able to handle it using maven exclusions, but I thought fixing at its original place might help many other. Also, it'll help a lot if "hsac-fitnesse-fixtures" also performs vulnerability scans on every build because now a days organizations are implementing strict policies in their CI/CD environments.  

![image](https://github.com/fhoeben/hsac-fitnesse-fixtures/assets/4468089/3682e2f9-3895-471c-ad41-32d90c9c652e)

Second, I have a question. 
As I mentioned, we are using your fixtures as dependency. Same just like your project, we also use "exec-maven-plugin" plugin in our project and to avoid any conflicts, I try to use the same version of "exec-maven-plugin" which is used in your project.  In your recent release (I guess after 5.2.45) you've upgraded "exec-maven-plugin" version to 3.1.1. So, when I upgraded "hsac-fitnesse-fixtures" to 5.3.6 and "exec-maven-plugin" to 3.1.1 in my project, it ran into the following error. 
When I demoted "exec-maven-plugin" to 3.0.0 along with "hsac-fitnesse-fixtures" 5.3.6, it is working fine.  Any idea what is conflicting here? 

![image](https://github.com/fhoeben/hsac-fitnesse-fixtures/assets/4468089/bd104231-2f3d-457f-818d-5abfa09e83f5)

**Comment by fhoeben** [comment]
The JNA dependency is a surprise, I didn't get any mention of it from the vulnerability scan I use in the last couple of releases. I will take a look. Did your tool by any chance identify which of my dependencies refers to the outdated version? 

I believe I indeed had to update the maven-exec command some releases ago, maybe you need the same change?
https://github.com/fhoeben/hsac-fitnesse-fixtures/commit/6d43e6d285d099092352ab8fd683b43e5cb11c5d
I'm using the following and don't get that message:
```
						<goals>
							<goal>exec</goal>
						</goals>
						<configuration>
							<executable>java</executable>
							<workingDirectory>wiki</workingDirectory>
							<commandlineArgs>-jar fitnesse-standalone.jar -p ${fitnesse.port}</commandlineArgs>
						</configuration>
```

**Comment by aquddos123** [comment]
Thanks @fhoeben for your quick response. 
Regarding JNA dependency, I ran maven dependdency:tree on your package and found it is coming through "org.apache.httpcomponents:httpclient-win". I see you are using the most resent version of httpclient library which 4.5.14 but somehow that dependency need an exclusion of older JNA. 
![image](https://github.com/fhoeben/hsac-fitnesse-fixtures/assets/4468089/43dda73f-0a36-4b21-a8dc-df9d34c403fa)

Regarding compile issue with 3.1.1 "exec-maven-plugin", I changed the command line arguments configuration as you described and it worked. Surprisingly, I have been using the below configuration for long time without any issue. It just started complaining with the newer version of your package. Do you think I am overlooking anything...

**Old command config (giving issue at compile time)**
![image](https://github.com/fhoeben/hsac-fitnesse-fixtures/assets/4468089/9861d636-226a-48b9-98cb-1b6b37c33536)

**New command config (working fine)** 
![image](https://github.com/fhoeben/hsac-fitnesse-fixtures/assets/4468089/6361da9d-3823-434a-a303-0e9a46bdef4f)

**Comment by fhoeben** [comment]
I have no clue regarding the exec-maven config. I believe I was doing it the same way you were before, but for some reason the `arguments` tag doesn't work that way anymore. Maybe you can file an issue/question at that plugin's project?

Would you please request an update of the JNA dependency at https://github.com/apache/httpcomponents-client/, that would be my preferred approach to get rid of the issue...

Maybe we should see whether we can upgrade to the 5.x version of the http client, or do those also have the problem?

**Comment by fhoeben** [comment]
Exposure based on the vulnerability should be limited. That component is used only when doing HttpTest with Negotiate/NTLM authorization

**Comment by aquddos123** [comment]
> Exposure based on the vulnerability should be limited. That component is used only when doing HttpTest with Negotiate/NTLM authorization

I agree, but unfortunately, organizations don't see security vulnerabilities as we do. They have checks in place and as soon there is a red flag, they stop us proceeding with CI/Cd process. 
Anyway, I'll try with httpclient developers to see what they say and keep you posted.

Thanks for your help

**Comment by aquddos123** [comment]
I've reached out to Apache Security team and got this reply back. As mentioned, I'll post this question in the http client community group and see what we learn. 
![image](https://github.com/fhoeben/hsac-fitnesse-fixtures/assets/4468089/8ea1ce39-4206-4cbf-af07-af5b98e2d8ca)

**Comment by aquddos123** [comment]
No resolution from Apache Security team yet so I am going to manage this manually in my pom.xml
