### ISSUE TITLE
Req: Is Visible on website

### ISSUE THREAD

**Issue by teunisnl** [fhoeben/hsac-fitnesse-fixtures#59]
Simply: ability to check if text/element is visually present anywhere on current page (regardless if its currently on the screen)

Long:
The current | is visible | has its perks if you wanna make sure if an element is on screen.
but its more often I would prefer the option | is visible | would have a build in |scroll to|
for compatibility a |is visible on page| would be great.
and yeah i know i could solve this by addind a scroll to, so it would be more perk then a must have

**Comment by fhoeben** [comment]
I understand what you are looking for, its not very hard to add. Do you have the time to create a pull request? 

As workaround (besides scrolling yourself):
- Would 'is enabled' help you at all? I don't believe that requires the element to be scrolled into view?

**Comment by teunisnl** [comment]
Is enable could invoke false errors, so it not a route i would prefer.
A pull request, time I have, but would be first so it will take some time to figure out how to do it.

**Comment by teunisnl** [comment]
#60
