### ISSUE TITLE
Can we access shadow dom elements in our scripts ?

### ISSUE THREAD

**Issue by pvbemmelen62** [fhoeben/hsac-fitnesse-fixtures#609]
If the webpage contains

&lt;input type="text" name="lastName" value=""&gt;
&nbsp; &nbsp;  #shadow-root
&nbsp;&nbsp;  &nbsp; &nbsp;   &lt;div&gt;Churchill&lt;/div&gt;

then the command

|is visible|Churchill|

will return false.

And command

|is visible|xpath=//input[@name='lastName']//div|

will return false.

Is there a way to specify the div under the shadow-root ?

**Comment by fhoeben** [comment]
Shadow DOM access is possible, but might need some extra attention.
Did you see: [wiki/FitNesseRoot/HsacAcceptanceTests/SlimTests/BrowserTest/AccessShadowDomTest.wiki](https://raw.githubusercontent.com/fhoeben/hsac-fitnesse-fixtures/main/wiki/FitNesseRoot/HsacAcceptanceTests/SlimTests/BrowserTest/AccessShadowDomTest.wiki)

**Comment by pvbemmelen62** [comment]
Thanks for the link ; I hadn't seen that yet.
Wow... no javascript needed in the script (; probably the implementation does use javascript?) .

I noticed that it works with CSS , but not with xpath.

This is accepted, runs okay (strange: shouldn't there be quotes around checkbox) :
`|check|value of|css=input[type=checkbox]     |in|id=shadow_host|true|`

This throws an exception:
`|check|value of|xpath=input[@type="checkbox"]|in|id=shadow_host|true|`

with the exception being
`org.openqa.selenium.InvalidArgumentException: invalid argument: invalid locator`

I also tried `..//input[@type="checkbox"]` ; still an exception.

**Comment by fhoeben** [comment]
@pvbemmelen62 apparently this is a limitation when interacting with the shadow root, one can only use `css`. See also https://stackoverflow.com/questions/55761810/how-to-automate-shadow-dom-elements-using-selenium#answer-71010515
