### ISSUE TITLE
How to reset "pageLoadWait" value?

### ISSUE THREAD

**Issue by aquddos123** [fhoeben/hsac-fitnesse-fixtures#615]
**SeleniumHelper.java**
Where is the below "pageLoadWait = 10000" coming from and how can we overwrite this value?

![image](https://github.com/fhoeben/hsac-fitnesse-fixtures/assets/4468089/a1c0f324-326e-47cb-98f0-3d83e634dfed)

**Comment by fhoeben** [comment]
Doesn't the stack navigator allow you to move up the call stack to see?
I'm guessing from `BrowserTest#secondsBeforePageLoadTimeout()` line 2494 and that is probably being called from a table in your test. Something like
```
|seconds before page load timeout| 10000 |
```

**Comment by aquddos123** [comment]
Thanks
