### ISSUE TITLE
Setting Content-type in MockXmlServerSetup?

### ISSUE THREAD

**Issue by violinner** [fhoeben/hsac-fitnesse-fixtures#62]
Is there a way to set the 'Content-type' header in
nl/hsac/fitnesse/fixture/slim/MockXmlServerSetup ?
A "Content-type" header is required by some FitNesse Fixtures.

desirable, but does not appear to work:
<nowiki>
 !define HTML { {{{
 <!DOCTYPE html>
  &lt;html lang="en"&gt;
  &lt;header&gt;
  &lt;meta http-equiv="content-type" content="text/html; charset=UTF-8"&gt;
  &lt;/header&gt;
  &lt;body&gt;
</nowiki>. . .

**Comment by fhoeben** [comment]
Short answer: no.
Bit longer: not yet, but feel free to make a pull request :-)
