### ISSUE TITLE
The valueOf how get <div> text?

### ISSUE THREAD

**Issue by cmaster007** [fhoeben/hsac-fitnesse-fixtures#621]
eg:<div class="two-line" id="iip_name_cname">divtest</div>,in BrowserTest  value of don't get the text  "divtest"

**Comment by cmaster007** [comment]
The keyword value of cannot get the text between divs, eg: <div class="two-line" id="iip_name_cname"> divtest </div>, how to get the text divtest

**Comment by fhoeben** [comment]
Sorry. Please take some time to review your issues text and how it is rendered by GitHub. I believe you want to show some example HTML but it is not visible.
