### ISSUE TITLE
Feat: Chrome Emulator

### ISSUE THREAD

**Issue by teunisnl** [fhoeben/hsac-fitnesse-fixtures#63]
For mobile website testing (without grids) this would be a nice addition
https://sites.google.com/a/chromium.org/chromedriver/mobile-emulation

in case of you prefer a pull request:
I have quick solution working (1 device) looked at converting this into SeleniumDriverSetup.java
but run out ideas how todo this clean within the current functions.
Could introduce a startChromeEmulator ? or any other ideas

**Comment by fhoeben** [comment]
I have not had the time to look at this yet, sorry.
Can you share (in a fork) your current 'quick solution'?

**Comment by teunisnl** [comment]
https://github.com/teunisnl/hsac-fitnesse-fixtures/tree/ChromeEmulation

no ability to define your own device just only the default list, only way to keep in same line with start driver. but i could add more flexibility to have it more configurable, but as result harder to understand

**Comment by fhoeben** [comment]
I created a branch with a slightly updated version of your idea. It makes it more explicit the profile is (only) for mobile emulation. What do you think of that?

**Comment by teunisnl** [comment]
well that great now it can do with defined devices and custom ones

**Comment by fhoeben** [comment]
Good enough for your needs? I have spent no effort yet to think about/check how this can be used in build server job where Selenium configuration is done outside wiki.
But maybe that's not that important for these jobs (multiple wiki configs are desirable/acceptable)?

**Comment by teunisnl** [comment]
More then enough. 
Seeing its not 100% guaranteed that test that work on desktop will work on mobile, so we use a 2nd suite and symbolic links to cases that are the same for mobile and desktop and make separated for those that don't. 
we are looking into it if we can use normal selenium grid and the same chrome emulator for mobile testing.
For more "realistic" mobile testing we usually use commercial grids

**Comment by teunisnl** [comment]
'''
|script           |map fixture                      |
|set value        |!-Apple iPhone 6-!|for|deviceName|
|$mobileEmulation=|copy map                         |

|script         |map fixture                         |
|set value      |$mobileEmulation|for|mobileEmulation|
|$chromeoptions=|copy map                            |

|script        |map fixture                     |
|set value     |chrome        |for|browserName  |
|set value     |$chromeoptions|for|chromeOptions|
|$capabilities=|copy map                        |

|script              |selenium driver setup                                                                                                                         |
|connect to driver at|${GRID_HUB}         |with capabilities|$capabilities                                                                                          |
|show                |driver description                                                                                                                            |
'''

To use seleniumCapabilities a change is required in the string conversion, ill probally will make pull request for that

**Comment by fhoeben** [comment]
Look forward to the pull request.

To set up the capabilities variable you should be able to combine the 3 map fixtures script tables into one:
```
|script        |map fixture                     |
|set value     |chrome            |for|browserName  |
|set value     |!-Apple iPhone 6-!|for|chromeOptions.mobileEmulation.deviceName|
|$capabilities=|copy map                        |
```

**Comment by fhoeben** [comment]
In #67 you state the map fixture approach I suggest above does not work. This surprises me quite a bit. I would expect exactly the same Map to be created by my table as by your 3 tables. What is the difference Chrome does not like?

**Comment by teunisnl** [comment]
It doesn't look the same on runtime, so it just start chrome without emulation

![c1](https://cloud.githubusercontent.com/assets/9052650/16414279/0d29a96e-3d37-11e6-8819-b921446854a5.PNG)
![c2](https://cloud.githubusercontent.com/assets/9052650/16414280/0e32ac48-3d37-11e6-8cf1-302443666f72.PNG)

**Comment by fhoeben** [comment]
I knew the nested usage of FitNesse's Hash widget is not supported (it creates a `Map<String,String>`). But my MapFixture should have created a separate Map 'mobileEmulation', that's a bug. Thanks for pointing it out.
