### ISSUE TITLE
Browser test action for double click

### ISSUE THREAD

**Issue by binkley** [fhoeben/hsac-fitnesse-fixtures#65]
Selenium supports sending double-click to the driver (`Actions::doubleClick`), but I did not see a way to do that with the `BrowserTest` fixture.  Did I miss something?

**Comment by fhoeben** [comment]
You did not miss it, it's indeed not there (yet). 
I've looked at actions a couple of times in the past (mostly drag 'n drop related) but I have not had a need for them yet. 
If you do need double clicking, or other actions: please submit a pull request.
