### ISSUE TITLE
set-cookie header returned by application is not fully relayed to fitnesse

### ISSUE THREAD

**Issue by lucasvdw** [fhoeben/hsac-fitnesse-fixtures#68]
Situation: Using the http test, sending a get request to the application. 

Expected: the application returns a http code 200, several response headers including a set-cookie-header, containing multiple cookies, and a response body.

Result: response body and http code OK, but the set-cookie header that the application sends back, which exists of two parts, is not completely relayed to fitnesse. Instead, only one part is relayed, making it impossible to check that both cookies are set by the application.

Example: 
These headers are sent:
Content-Type: text/html;charset=UTF-8
Content-Language: nl-NL
Set-Cookie:
ABC=ABC%2DID%3DABC00005%26OFFER%2DID
Set-Cookie: 
ABC-APP-VARIABLES=REQUEST%3DACTIVE
Transfer-Encoding: chunked
etc

The issue here is that the second set-cookie header DOES make it to Fitnesse but the first doesn't.

**Comment by fhoeben** [comment]
Can you provide the actual cookie header value?

**Comment by lucasvdw** [comment]
i've updated the above
