### ISSUE TITLE
testing a web application that opens new browser windows

### ISSUE THREAD

**Issue by violinner** [fhoeben/hsac-fitnesse-fixtures#77]
If my web application opens new web browsers (not modal dialogs), is there a browser test command to switch to the other window, selected by title?

**Comment by fhoeben** [comment]
You can use the 'tab' commands to count, switch between and close windows (Selenium does not distinguish between tabs and windows as far as I know).

There is no command (yet) to select window by title. But when a new window is opened it is considered the 'next' tab, so you can switch to it by using `switch to next tab`, and then go back using `switch to previous tab`
