### ISSUE TITLE
Confirm alert does not work in a storyboard testscript

### ISSUE THREAD

**Issue by pvreeuwijk** [fhoeben/hsac-fitnesse-fixtures#84]
I can not call |confirm alert| when it is in a storyboard test script.
However, when I change it into |script| it works fine.

I would like to have support on alerthandling in storyboard test scripts.

**Comment by fhoeben** [comment]
Never thought of that (luckily most of the environments I test in don't use alerts). Would a solution like in the attached screenshot work for you?

![2016-10-03 at 17 11](https://cloud.githubusercontent.com/assets/5467859/19042561/c8ada8ba-898c-11e6-9688-9c3fa2375bce.png)

**Comment by pvreeuwijk** [comment]
I think that is a nice solution

**Comment by fhoeben** [comment]
Fix included in 2.8.1
