### ISSUE TITLE
hyperlinks can't be used with e.g. a click command

### ISSUE THREAD

**Issue by selichtenberg** [fhoeben/hsac-fitnesse-fixtures#88]
When using e.g. the click command for selecting an e-mail address (which is a hyperlink), Fitnesse will not be able to select it.

In my case, I needed to select an email address out of a dropdown, but this could not be done with the 'click' command. By using '!-_email_-!' it can still be done, but it would be useful if this is done automatically :)

**Comment by fhoeben** [comment]
Will be part of 2.9.1, already addressed in master branch.
