### ISSUE TITLE
Question: How to use WikiSymbols as Variables?

### ISSUE THREAD

**Issue by bzon** [fhoeben/hsac-fitnesse-fixtures#91]
Example:
```bash
!define VAR {!randomBSN}
```
Thanks!

**Comment by fhoeben** [comment]
That should work (although I don't see much added value for `!randomBSN`).

If you want to put it in a Slim variable/symbol (so you can generate a random value once and use it in multiple places) you could use string fixture:
```
|script|string fixture|
|$myBsn=|value of|!randomBSN|
```

**Comment by bzon** [comment]
Awesome! Thanks for the really quick answer! The Symbols are really helpful for generating random data. Cheers!
