### ISSUE TITLE
Question: Adding a response header in Json HTTP call

### ISSUE THREAD

**Issue by bzon** [fhoeben/hsac-fitnesse-fixtures#93]
Hello!

How do we change the response header for a Json Http calls?

My error is:
```bash
"message": "Content type 'application/x-www-form-urlencoded;charset=UTF-8' not supported"
```

Thank you!

**Comment by fhoeben** [comment]
Use `|set value|application/json|for header|Content-Type|`, maybe you'll also need `|set value|application/json|for header|Accept|`

**Comment by bzon** [comment]
Perfect! I wonder if its ok to keep asking here.. Closing this issue. 

We will be using fitnesse with this plugin as replacement for SOAP UI. This is really cool. Thanks man!
