### ISSUE TITLE
Website testing using custom subclass of NgBrowserTest

### ISSUE THREAD

**Issue by danielmenezesbr** [fhoeben/hsac-fitnesse-fixtures#97]
Website testing using custom subclass of NgBrowserTest doesn't work fine when a method call open(...)

Reproduce:

 - Create custom subclass of NgBrowserTest:
```
import nl.hsac.fitnesse.fixture.slim.web.NgBrowserTest;

public class CalcTest extends NgBrowserTest {
	// this method call open(...)
	public void accessMainScreen() {
		open("http://juliemr.github.io/protractor-demo/");
	}
	
	public void fillFirst(String value) {
		enter(value, "css=input[ng-model='first']", true);
		System.out.println("fillFirst");
	}
}

```
 - Go http://localhost:8080/HsacExamples.SlimTests.BrowserTests

 - Add > Test Page

 - Content:
```
!path   C:\eclipse\workspace\myapp\target\test-classes\
|script|Calc Test                          |
|access Main Screen  |
|fill First|50  |
|show |take screenshot       |foto1   |
```

 - Click "Save" button and click "Test".

 - Result:
It's produces a error: "angular could not be found on the window.". See
![hsac_result](https://cloud.githubusercontent.com/assets/5949657/20140258/5c6f9fd0-a671-11e6-9053-31e6e4b0cd2f.png)
![hsac_log](https://cloud.githubusercontent.com/assets/5949657/20140259/5c70bfe6-a671-11e6-8054-42124d41d0cf.png)

PS1: If i replace     |access Main Screen  |      by     |open|http://juliemr.github.io/protractor-demo/  | it's works fine:
![image](https://cloud.githubusercontent.com/assets/5949657/20140357/dd6b5458-a671-11e6-8e33-efbe89c0dfde.png)

**Comment by fhoeben** [comment]
NgBrowserTest does not wait for Angular before it executes `open()` (since the page is not yet loaded). Your method requires similar handling. You can achieve this by overriding `requiresWaitForAngular()` in your subclass. In your override you can check whether 'accessMainScreen' is being called and return `false` if so, otherwise return the value of the superclass' implementation:
```
    @Override
    protected boolean requiresWaitForAngular(Method method) {
        if ("accessMainScreen".equals(method.getName())) {
            return false;
        } else {
            return super.requiresWaitForAngular(method);
        }
    }

```

**Comment by danielmenezesbr** [comment]
@fhoeben, thanks!
It's works fine!

**Comment by danielmenezesbr** [comment]
@fhoeben,
Do you think it's a good idea to create a annotation called NgMethodsNoWait?

Example:
@NgMethodsNoWait("accessMainScreen, method2, method3")
public class CalcTest extends NgBrowserTest {
	// this method call open(...)
	public void accessMainScreen() {
		open("http://juliemr.github.io/protractor-demo/");
	}
	
	public void fillFirst(String value) {
		enter(value, "css=input[ng-model='first']", true);
		System.out.println("fillFirst");
	}
}

The annotation NgMethodsNoWait will work as method requiresWaitForAngular:
    @Override
    protected boolean requiresWaitForAngular(Method method) {
        if ("accessMainScreen".equals(method.getName())) {
            return false;
        } else {
            return super.requiresWaitForAngular(method);
        }
    }

If you like it, I can create PR with this annotation.

**Comment by fhoeben** [comment]
I would suggest you make it an annotation to be placed on the method, instead of on the class.
Other than that, good idea. You can start by creating your own sublass that uses such an annotation for this purpose. When this works to your satisfaction: create a pull request to move this to the NgBrowserTest.

**Comment by danielmenezesbr** [comment]
@fhoeben
I create a PR for annotation @NgMethodNoWait.

Example of use:
```
import nl.hsac.fitnesse.fixture.slim.web.NgBrowserTest;
import nl.hsac.fitnesse.fixture.slim.web.annotation.NgMethodNoWait;

public class MyExample extends NgBrowserTest {
	
	@NgMethodNoWait
	public boolean acessarTela() {
		return open("http://juliemr.github.io/protractor-demo/");
	}
	
}
```

Could you evaluate this PR?
